/**
 * OQCA v1.7 — IMPROVEMENT OBJECTIVES THAT ARISE FROM WHAT ONIQ SAW.
 *
 * Owner directive 2026-09-11 §5: _"Do not use a fixed objective list.
 * Objectives must arise from observed system state."_ And the HARD RULE: _"The
 * test must be able to prove that the decision was generated by the runtime
 * from observed state, rather than being preselected by the test. The system
 * must be able to surprise the test."_
 *
 * THAT IS A CONSTRAINT ON THIS FILE SPECIFICALLY, and it rules out the
 * implementation anyone would write first: a `switch (observation.kind)` with a
 * hand-written objective and a hand-picked importance per arm. That version
 * satisfies every functional test and is a fixed list with extra steps — the
 * ranking it produces is a fact about the table, not about ONIQ. So every
 * factor below is computed from the OBSERVATION'S OWN FIELDS: its severity
 * (which the observer derived from what it read), its state, its measured
 * value, and how many other observations implicate the same subject. Change
 * what ONIQ observes and the objective changes; `selfImprovement.test.ts`
 * proves exactly that by feeding two different worlds and asserting two
 * different choices, neither of them named in advance.
 *
 * AND THE SIX FACTORS ARE THE EXISTING ONES. §6: _"Use the existing six-factor
 * prioritization… Preserve the existing semantics. Do not reintroduce the v1.5
 * freshness mistake."_ So this file builds `Gap`s and hands them to
 * `rankLearningTargets` unchanged; it does not re-derive a score beside the
 * scorer. The §6 extension — capability, cost, reversibility, risk, blocked
 * dependencies, expected improvement — is a SECOND, clamped pass on top, for
 * the same reason `staleness` and `relevance` are clamped in `select.ts`: a
 * multiplied factor that may reach zero is a veto nobody declared, and a veto
 * on capability availability is precisely the thing v1.6 removed.
 */
import type { Gap, GapStatus, Goal } from "../knowledge/gaps.ts";
import { type LearningTarget, MODIFIER_FLOOR, rankLearningTargets } from "./select.ts";
import type { KnowledgeState } from "../knowledge/model.ts";
import { type Capability, type CapabilityState, needsAPerson } from "../loop/capability.ts";
import type { Observation } from "./observation.ts";
import { type SystemWorldState, worldConcerns } from "./world.ts";

/** The concept an improvement objective is about. Stable across ticks. */
export function concernId(o: Observation): string {
  return `${o.kind}:${o.subject}`;
}

/**
 * HOW UNCERTAIN ONIQ IS ABOUT A CONCERN, FROM THE OBSERVATION'S STATE.
 *
 * An UNOBSERVED kind is total ignorance by definition — ONIQ has not looked, so
 * nothing is known and uncertainty is 1. UNKNOWN is nearly as bad and
 * deliberately not identical: the probe ran, so something was learned about the
 * measurement even though nothing was learned about the system. An OBSERVED row
 * with a number is the least uncertain, and an OBSERVED row WITHOUT one sits
 * between: ONIQ knows the fault exists and cannot say how big it is.
 */
export function uncertaintyOf(o: Observation): number {
  if (o.state === "UNOBSERVED") return 1;
  if (o.state === "UNKNOWN") return 0.9;
  return o.value === null ? 0.6 : 0.3;
}

/**
 * WHAT ONE GOOD ANSWER WOULD BUY. Derived, never assigned: connecting an absent
 * observer collapses its uncertainty completely, while investigating a fault
 * ONIQ has already measured buys only the part it cannot currently see.
 */
export function informationGainOf(o: Observation): number {
  if (o.state === "UNOBSERVED") return 1;
  if (o.state === "UNKNOWN") return 0.8;
  return o.value === null ? 0.7 : 0.4;
}

/**
 * HOW MUCH ELSE LEANS ON THIS SUBJECT, counted rather than declared. A module
 * that turns up in four observations is load-bearing in a way a hand-written
 * weight could only guess at — and the count is a fact about the system, which
 * is what the HARD RULE demands of every input to the decision.
 *
 * IT IS A BOOST FROM 1, NOT A FRACTION OF 1, AND THE FIRST DRAFT WAS THE OTHER
 * ONE. That version returned `others / min(total, 6)`, which is ZERO for a
 * subject no other observation mentions — and on a real world state almost no
 * subject is mentioned twice. Six multiplied factors mean one zero annihilates
 * the other five, so EVERY concern scored exactly 0.000000 and `planImprovements`
 * ranked alphabetically by goal id. The whole six-factor machinery was dead and
 * nothing said so: the plan was non-empty, ordered, reproducible and completely
 * uninformed.
 *
 * Found by printing the scores rather than by reading the function — the same
 * shape as v1.2b's IMAGINE scoring the action's own name, where a broken
 * parser read as caution. `detectGaps` had it right all along and is copied
 * here deliberately: `1 + dependents/(n-1)`, which is at least 1, so a
 * well-connected subject is PROMOTED and an isolated one is merely not.
 */
export function dependencyOf(o: Observation, all: readonly Observation[]): number {
  const others = all.filter((x) => x.subject === o.subject && x.id !== o.id).length;
  const total = Math.max(1, all.length - 1);
  return 1 + others / total;
}

/**
 * The `GapStatus` a concern has, in the substrate's own vocabulary so the
 * existing selector needs no special case.
 *
 * TWO OF THE FOUR ARE UNREACHABLE FROM HERE, AND THAT IS THE CORRECT ANSWER
 * RATHER THAN A GAP. `VERIFIED` never appears because a concern IS an open
 * question — `openGaps` would drop it and `actionable` never emits a zero-
 * severity row. And `CONTRADICTED` means, in `detectGaps`'s own definition,
 * evidence on BOTH SIDES of one assertion above `DISPUTE_THRESHOLD`. A single
 * observation is one reading; it cannot disagree with itself. Emitting
 * `CONTRADICTED` for, say, a high-severity fault would put a label on the
 * report that the substrate's vocabulary does not mean, and the number that
 * decided it would be a threshold picked here — which is exactly what the HARD
 * RULE forbids as an input to the decision.
 *
 * So: a kind nobody looked at has no evidence bearing on it at all, which is
 * `UNKNOWN`; everything else — a probe that could not decide, a fault ONIQ can
 * see but does not know how to fix — is `UNCERTAIN`. Both branches are
 * reachable and both are mutation-checked.
 */
export function statusOf(o: Observation): GapStatus {
  return o.state === "UNOBSERVED" ? "UNKNOWN" : "UNCERTAIN";
}

/**
 * An observation becomes a `Gap` in the existing shape. `priority` is left for
 * `rankLearningTargets` to compute — writing one here would be a second scorer.
 */
export function concernGap(o: Observation, all: readonly Observation[]): Gap {
  const importance = o.severity;
  const uncertainty = uncertaintyOf(o);
  const dependency = dependencyOf(o, all);
  const informationGain = informationGainOf(o);
  return {
    conceptId: concernId(o),
    status: statusOf(o),
    importance,
    uncertainty,
    dependency,
    expectedInformationGain: informationGain,
    priority: importance * uncertainty * dependency * informationGain,
    supportingEvidence: o.state === "OBSERVED" ? 1 : 0,
    opposingEvidence: 0,
    reason: `${o.state.toLowerCase()} ${o.kind} on ${o.subject}: ${o.detail}`,
  };
}

/**
 * §6's EXTRA PLANNING FACTORS — they re-rank and they may not veto.
 *
 * Every one is in [MODIFIER_FLOOR, 1] for v1.5's reason, restated by §21: six
 * multiplied terms mean one zero annihilates the other five, and a zero on
 * `capability` would make an unavailable resource delete the objective rather
 * than defer it. ONIQ must still be able to choose an objective it cannot
 * currently execute — that is how the blocker gets recorded and how
 * reconsideration has something to reconsider.
 */
export type PlanningFactors = {
  /** Can ONIQ execute what this objective would need, right now? */
  readonly capability: number;
  /** Cheap work first, all else equal. Never a money bound — see §21. */
  readonly cost: number;
  /** A reversible change outranks one that cannot be undone. */
  readonly reversibility: number;
  /** 1 = harmless. Risk lowers the factor. */
  readonly risk: number;
  /** How much of what this needs is already satisfied. */
  readonly dependencies: number;
  /** How much the metric could move if the hypothesis is right. */
  readonly expectedImprovement: number;
};

export const NEUTRAL_PLANNING: PlanningFactors = {
  capability: 1,
  cost: 1,
  reversibility: 1,
  risk: 1,
  dependencies: 1,
  expectedImprovement: 1,
};

function floor(x: number): number {
  return Math.min(1, Math.max(MODIFIER_FLOOR, x));
}

export function planningModifier(f: PlanningFactors): number {
  return (
    floor(f.capability) *
    floor(f.cost) *
    floor(f.reversibility) *
    floor(f.risk) *
    floor(f.dependencies) *
    floor(f.expectedImprovement)
  );
}

/**
 * WHAT A FAULT IS WORTH WHEN ONLY A PERSON CAN CLEAR IT.
 *
 * `capability` asks "can ONIQ execute this now", and for a self-improvement
 * loop holding three read-only capabilities the answer for any real product
 * fault is permanently no. Treated as a flat discount that made the factor stop
 * discriminating and start expressing a bias: anything about the PRODUCT lost
 * to anything about ONIQ's own file tree, whatever the severity. Measured on
 * the 2026-09-11 story-dispatch outage, a severity-1.0 production outage ranked
 * 14th of 18, behind thirteen "establish how to observe X" chores.
 *
 * The distinction that fixes it already existed and the planner simply never
 * read it. `needsAPerson` splits a shortfall ONIQ's own number controls — an
 * allowance, a rate limit — from one that is somebody else's decision about who
 * ONIQ is. For the first, deferring is right: come back when the number moves.
 * For the second there is nothing to come back for, and the objective's whole
 * value is the REPORT — which is work ONIQ can always do, so it may not be
 * discounted into invisibility. Otherwise the outage can never be SELECTED, so
 * `capability_blocked` can never name it, and v1.6's claim that that stop is
 * "the difference between 'ONIQ is stuck' and 'a credential is missing'" is
 * unreachable in the one case it was built for.
 *
 * BELOW 1 ON PURPOSE. A fault ONIQ can actually fix outranks one it can only
 * report, at equal importance — half the work is available to it, so half is
 * the factor. The two ORDERING properties that matter are asserted in
 * `selfImprovement.test.ts` rather than derived from this number, so a future
 * change to any other factor makes the test fail instead of silently
 * re-burying the report.
 */
export const ESCALATION_CAPABILITY = 0.5;

/**
 * What an improvement objective would need in order to run, derived from the
 * concern and checked against the ledger. A concern whose required capability
 * is refused keeps a `capability` factor at the FLOOR rather than at zero.
 */
export type CapabilityNeed = {
  readonly concept: string;
  /**
   * The RESOURCE kinds this concern's work would consume, in the v1.6 ledger's
   * own vocabulary — not the §12 registered capability ids the observation
   * carries in `requires`. The two are different axes and conflating them would
   * break reconsideration: `reconsider` returns a blocked objective to `pending`
   * once every capability it NAMED is observed working, and what the ledger
   * observes is `model` / `tool` / `research` / `verification`. The host owns
   * the registry, so the host maps `RUN_TEST_SUITE` to `tool`; the kernel never
   * carries that table, because the table is authorization and authorization
   * belongs beside the router.
   */
  readonly needs: readonly Capability[];
};

export function planningFor(
  need: CapabilityNeed,
  ledger: readonly CapabilityState[],
  o: Observation,
): PlanningFactors {
  const byName = new Map(ledger.map((c) => [c.capability, c] as const));
  const met = need.needs.filter((n) => byName.get(n)?.availability === "available").length;
  const escalation = need.needs.some((n) => {
    const state = byName.get(n);
    return state ? needsAPerson(state.availability) : false;
  });
  const capability =
    need.needs.length === 0 || met === need.needs.length
      ? 1
      : escalation
        ? ESCALATION_CAPABILITY
        : met / need.needs.length;
  return {
    capability,
    // A concern ONIQ can read off its own tree costs nothing; one that needs a
    // provider costs more. Derived from whether the observation carried a
    // locator, which is exactly "could this be checked for free".
    cost: o.provenance ? 1 : 0.7,
    // Nothing in this runtime may make an irreversible change — the registered
    // capability set has no such action — so reversibility is 1 and is asserted
    // to be, rather than being a field nobody set.
    reversibility: 1,
    // A fault ONIQ has measured is safer to act on than one it has inferred.
    risk: o.state === "OBSERVED" ? 1 : 0.8,
    // NEUTRAL, DELIBERATELY, AND THAT IS A NARROWING RATHER THAN A FIELD NOBODY
    // SET. It used to be `known / needs.length` — the fraction of the needed
    // resources the ledger had ever heard of — computed over the SAME list
    // `capability` reads. Since met is a subset of known the two were nested
    // measures of one fact, and multiplying them squared the penalty: on a cold
    // ledger a concern scored 0.05 x 0.05 = 0.0025 where an explicit refusal
    // scored 0.05 x 1 = 0.05, so SILENCE was punished twenty times harder than
    // a known refusal. That is backwards — a refusal is strictly more
    // informative than silence — and it is v1.6's "ABSENT IS NOT AVAILABLE"
    // read the wrong way round: absence must be REPORTED, never counted as a
    // second failure. One shortfall, one factor. This stays 1 until it measures
    // something `capability` does not.
    dependencies: 1,
    // The severity IS the expected movement: a 0.9-severity fault has more room
    // to improve than a 0.2 one. Reusing it rather than inventing a second
    // scale keeps the two from disagreeing.
    expectedImprovement: Math.max(o.severity, MODIFIER_FLOOR),
  };
}

export type PlannedConcern = {
  readonly observation: Observation;
  readonly target: LearningTarget;
  readonly planning: PlanningFactors;
  /** The six-factor score times the clamped planning modifier. */
  readonly score: number;
  readonly goal: Goal;
};

/** The statement an objective carries. Reads the observation, not a template. */
export function goalFor(o: Observation): Goal {
  const id = `improve:${concernId(o)}`;
  const verb =
    o.state === "UNOBSERVED"
      ? "establish how to observe"
      : o.state === "UNKNOWN"
        ? "establish how to measure"
        : "establish what would improve";
  return {
    id,
    statement: `${verb} ${o.kind.replace(/_/g, " ")} on ${o.subject}`,
    requires: [{ conceptId: concernId(o), importance: Math.max(o.severity, MODIFIER_FLOOR) }],
  };
}

export type PlanInput = {
  readonly world: SystemWorldState;
  readonly knowledge: KnowledgeState;
  /** Concern id -> demand for fresh evidence, the `select.ts` shape. */
  readonly staleness?: ReadonlyMap<string, number>;
  readonly focus: Goal | null;
  readonly capabilities: readonly CapabilityState[];
  /**
   * Which RESOURCE kinds each concern's work would consume. Supplied by the
   * host, which owns the §12 registry and therefore knows what each registered
   * capability spends — see `CapabilityNeed.needs`.
   */
  readonly needs: (o: Observation) => readonly Capability[];
};

/**
 * THE ONE ENTRY POINT: a world state in, ranked improvement concerns out.
 *
 * Note the order. The six factors run FIRST, over `Gap`s built from the
 * observations, through the untouched `rankLearningTargets`; the planning
 * modifier is applied afterwards to the score it produced. Folding the planning
 * factors into the `Gap` would have silently changed what the existing selector
 * means — `importance` would stop being "how much does this matter" and start
 * being "how much does this matter and can we afford it", and the v1.5 strict-
 * extension property would no longer hold.
 */
export function planImprovements(input: PlanInput): readonly PlannedConcern[] {
  const concerns = worldConcerns(input.world);
  if (concerns.length === 0) return [];
  const gaps = concerns.map((o) => concernGap(o, concerns));
  const targets = rankLearningTargets({
    gaps,
    knowledge: input.knowledge,
    staleness: input.staleness,
    focus: input.focus,
  });
  const byConcept = new Map(concerns.map((o) => [concernId(o), o] as const));

  const planned: PlannedConcern[] = [];
  for (const t of targets) {
    const o = byConcept.get(t.conceptId);
    if (!o) continue;
    const planning = planningFor(
      { concept: t.conceptId, needs: input.needs(o) },
      input.capabilities,
      o,
    );
    planned.push({
      observation: o,
      target: t,
      planning,
      score: t.score * planningModifier(planning),
      goal: goalFor(o),
    });
  }
  return planned.sort((a, b) => b.score - a.score || a.goal.id.localeCompare(b.goal.id));
}

/* ================================================================ *
 * §7 — WHAT MUST ONIQ KNOW BEFORE IT CAN SOLVE THIS?
 * ================================================================ */

export type GapVerdict = "known" | "unknown" | "uncertain" | "contested" | "stale";

export type KnowledgeNeed = {
  readonly concept: string;
  readonly verdict: GapVerdict;
  readonly reason: string;
};

export type ResearchDecision = "SKIP_RESEARCH" | "RESEARCH";

/**
 * COMPARE THE OBJECTIVE AGAINST WHAT IS ALREADY DURABLY KNOWN.
 *
 * `known` is the only verdict that skips research, and reaching it requires a
 * VERIFIED record that is not stale. `contested` does NOT skip: a concept with
 * evidence on both sides is exactly the one where acting on the stored answer
 * is worst, which is why `mayInformDecision` refuses CONTESTED in the substrate
 * and why this mirrors it rather than inventing a softer rule.
 */
export function knowledgeNeeds(
  goal: Goal,
  knowledge: KnowledgeState,
  staleness?: ReadonlyMap<string, number>,
): readonly KnowledgeNeed[] {
  return goal.requires.map((r) => {
    const concept = knowledge.concepts.get(r.conceptId);
    if (!concept) {
      return { concept: r.conceptId, verdict: "unknown" as const, reason: "no record at all" };
    }
    const ev = [...knowledge.evidence.values()].filter((e) =>
      [...knowledge.relations.values()].some(
        (rel) => rel.to === r.conceptId && rel.evidenceIds.includes(e.id),
      ),
    );
    const supporting = ev.filter((e) => e.supports);
    const opposing = ev.filter((e) => !e.supports);
    if (opposing.length > 0 && supporting.length > 0) {
      return {
        concept: r.conceptId,
        verdict: "contested" as const,
        reason: `${supporting.length} for, ${opposing.length} against`,
      };
    }
    const demand = staleness?.get(r.conceptId) ?? 0;
    if (demand >= 1) {
      return {
        concept: r.conceptId,
        verdict: "stale" as const,
        reason: "past its verification interval",
      };
    }
    const best = Math.max(0, ...supporting.map((e) => e.confidence.value));
    if (best >= 0.85) {
      return {
        concept: r.conceptId,
        verdict: "known" as const,
        reason: `verified at ${best.toFixed(2)}`,
      };
    }
    return {
      concept: r.conceptId,
      verdict: "uncertain" as const,
      reason: `best supporting confidence ${best.toFixed(2)}`,
    };
  });
}

export function researchDecision(needs: readonly KnowledgeNeed[]): ResearchDecision {
  return needs.every((n) => n.verdict === "known") ? "SKIP_RESEARCH" : "RESEARCH";
}
