// Find where the VOICE actually is in each scene's narration, as frame spans.
//
//   cd remotion && EPISODE=ep3 node scripts/measure-speech.mjs > src/ep3/speech.ts
//
// WHY THIS EXISTS, AND WHY pauses.ts IS NOT ENOUGH. `measure-ep3-pauses.mjs`
// emits pause CENTRES, because a cut wants to land in the middle of a silence.
// A mouth wants the opposite information and it wants it as SPANS.
//
// Deriving spans from centres does not work, and this is measured rather than
// argued: a centre is a point with no width, so the runs between consecutive
// centres tile the scene end to end. Feeding those to `buildMouthCues` produced
// a mouth that rested for 0% of all sixteen ep3 scenes — moving continuously
// for seven minutes, through every pause, with single shapes stretched as long
// as 18 frames to fill the silence. The shapes were right. The silence was
// simply not represented.
//
// So the same envelope is walked here and the SPEECH runs are emitted directly:
// the complement of the silences, not the gaps between their midpoints.
//
// RE-RUN THIS AFTER ANY CHANGE TO THE NARRATION, exactly like the pause table.
// A stale speech table moves the mouth where there is no longer a voice.
//
// Detection matches measure-ep3-pauses.mjs deliberately — a 20ms RMS envelope
// and a -40 dBFS floor — so the two tables describe the same audio. What
// differs is only the minimum run: a 120ms floor here rather than 220ms,
// because a stop short enough to ignore when placing a CUT is still long
// enough to close a mouth, and a mouth that closes between clauses is most of
// what makes it look like speech.
import fs from 'fs';
import path from 'path';
import { findBin } from './findFfmpeg.mjs';
import { envelope, speechSpans, FPS, WINDOW, FLOOR_DB, MIN_SILENCE, MIN_SPEECH } from './speech.mjs';
import { EPISODE, PUBLIC_DIR, sceneIds } from './episode.mjs';

const ffmpeg = findBin('ffmpeg');
const scenes = sceneIds();
const missing = scenes.filter((id) => !fs.existsSync(path.join(PUBLIC_DIR, `${id}.mp3`)));
if (missing.length > 0) throw new Error(`missing narration: ${missing.join(', ')}`);

const rows = scenes.map((id) => ({
  id,
  spans: speechSpans(envelope(ffmpeg, path.join(PUBLIC_DIR, `${id}.mp3`))),
}));

console.log(`// GENERATED by scripts/measure-speech.mjs — do not hand-edit.`);
console.log(`//`);
console.log(`// Spans of actual VOICE in each scene, as [startFrame, endFrame) at ${FPS}fps`);
console.log(`// from the scene's own start. A span is audio at or above ${FLOOR_DB} dBFS on a`);
console.log(`// ${WINDOW * 1000}ms RMS envelope, with silences under ${MIN_SILENCE * 1000}ms filled in and`);
console.log(`// runs under ${MIN_SPEECH * 1000}ms discarded.`);
console.log(`//`);
console.log(`// This drives the mouth. Re-run after ANY change to the narration mp3s.`);
console.log(``);
console.log(`export const ${EPISODE.toUpperCase()}_SPEECH: Record<string, [number, number][]> = {`);
for (const r of rows) {
  console.log(`  ${r.id}: [${r.spans.map(([a, b]) => `[${a}, ${b}]`).join(', ')}],`);
}
console.log(`};`);
console.log(``);
const totalSpans = rows.reduce((a, r) => a + r.spans.length, 0);
console.log(`// ${totalSpans} speech spans across ${rows.length} scenes.`);
for (const r of rows) {
  if (r.spans.length === 0) console.log(`// WARNING: ${r.id} has no detectable speech.`);
}
