import js from "@eslint/js";
import eslintConfigPrettier from "eslint-config-prettier/flat";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

/**
 * Why the project fences below each have their own rule id instead of all
 * being `no-restricted-syntax`.
 *
 * ESLint flat config REPLACES a rule's options when a later config object sets
 * the same rule id — it does not merge them. Four blocks below previously all
 * set `no-restricted-syntax`, so for any given file only the last matching
 * block survived. Verified with `--print-config`: on
 * src/routes/_authenticated/app.index.tsx the effective rule was the single
 * warn-level hardcoded-string selector, and the media-URL, currency and RTL
 * fences were silently inert across every .tsx under src/routes and
 * src/components. A probe file calling createSignedUrl() and getPublicUrl()
 * with `className="ml-2 text-left"` and a literal ₹ produced zero findings.
 *
 * Distinct rule ids are independent, so each block's own `files` / `ignores`
 * apply exactly as written.
 */
function selectorFence(entries) {
  return {
    meta: { type: "problem", schema: [] },
    create(context) {
      const visitors = {};
      for (const { selector, message } of entries) {
        visitors[selector] = (node) => context.report({ node, message });
      }
      return visitors;
    },
  };
}

const SIGN_MEDIA = "Sign media through src/lib/media/resolveMedia.ts (TTL-capped, cached), not directly.";
const NO_CURRENCY = "i18n: no hardcoded currency symbol — use useFormat().money() or moneyIn().";
const USE_LOGICAL =
  "RTL: use logical properties (ms-/me-/ps-/pe-, start-/end-, text-start/text-end) instead of physical ones.";

const oniq = {
  rules: {
    "media-url-fence": selectorFence([
      { selector: "CallExpression[callee.property.name='createSignedUrl']", message: SIGN_MEDIA },
      { selector: "CallExpression[callee.property.name='createSignedUrls']", message: SIGN_MEDIA },
      {
        selector: "CallExpression[callee.property.name='getPublicUrl']",
        message: "No public media URLs — resolve via src/lib/media/resolveMedia.ts.",
      },
    ]),
    "currency-fence": selectorFence([
      { selector: "JSXText[value=/[\\u20B9\\u00A3\\u20AC]/]", message: NO_CURRENCY },
      { selector: "Literal[value=/[\\u20B9\\u00A3\\u20AC]/]", message: NO_CURRENCY },
      { selector: "TemplateElement[value.raw=/[\\u20B9\\u00A3\\u20AC]/]", message: NO_CURRENCY },
      {
        selector: "CallExpression[callee.property.name='toLocaleString']",
        message: "i18n: use src/lib/format.ts (Intl via CountryConfig), not ad-hoc toLocaleString.",
      },
    ]),
    "rtl-fence": selectorFence([
      {
        selector:
          "JSXAttribute[name.name='className'] Literal[value=/(^|[\\s\"'`])(ml-|mr-|pl-|pr-|left-|right-|text-left|text-right)[0-9a-z]/]",
        message: USE_LOGICAL,
      },
      {
        selector:
          "JSXAttribute[name.name='className'] TemplateElement[value.raw=/(^|[\\s\"'`])(ml-|mr-|pl-|pr-|left-|right-|text-left|text-right)[0-9a-z]/]",
        message: USE_LOGICAL,
      },
    ]),
    "hardcoded-string": selectorFence([
      {
        selector: "JSXText[value=/[A-Za-z]{3,}\\s+[A-Za-z]{3,}\\s+[A-Za-z]{3,}/]",
        message:
          "i18n: hardcoded user-facing string — move it to dictionaries.ts and render via useT().",
      },
    ]),
  },
};

export default tseslint.config(
  {
    ignores: [
      "dist",
      "build",
      "coverage",
      "node_modules",
      ".output",
      ".vinxi",
      // Vendored Capacitor runtime — third-party, regenerated by `cap sync`.
      "android/app/src/main/assets/public/**",
      // Generated, never hand-edited. supabase/types.ts alone accounted for
      // 2,903 of the 7,142 findings (41%) — all of them formatting noise on a
      // file no human writes. routeTree.gen.ts is generated by TanStack Router.
      "src/integrations/supabase/types.ts",
      "**/*.gen.ts",
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
      oniq,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "server-only",
              message:
                "TanStack Start does not use the Next.js `server-only` package. Rename the module to `*.server.ts` or mark it with `@tanstack/react-start/server-only`.",
            },
          ],
        },
      ],
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  // B1 media-URL fence: all NEW code must resolve media via
  // src/lib/media/resolveMedia.ts (short-lived signed URLs). The listed
  // legacy files still sign directly (some with multi-year TTLs stored in
  // rows) — migrating them + their stored URLs is tracked B1 debt.
  {
    files: ["src/**/*.{ts,tsx}"],
    ignores: [
      "src/lib/media/resolveMedia.ts",
      "src/routes/_authenticated/app.clips.tsx",
      "src/components/customize/CustomizeSheet.tsx",
      "src/routes/_authenticated/app.admin.tsx",
      "src/routes/_authenticated/app.chat.updates.tsx",
      "src/components/moments/MomentsFeed.tsx",
      "src/lib/clipThumbs.ts",
      "src/routes/_authenticated/app.chat.$conversationId.tsx",
    ],
    rules: { "oniq/media-url-fence": "error" },
  },

  // i18n-1 — no hardcoded currency symbols in source. Every amount goes through
  // src/lib/format.ts (useFormat().money / moneyIn), which drives Intl from
  // CountryConfig.numberLocale + .currency.
  {
    files: ["src/**/*.{ts,tsx}"],
    ignores: [
      "src/lib/format.ts",
      "src/data/countryRegistry.ts",
      "src/data/appRegistry.ts",            // "₹" is a tile glyph, not an amount
      "src/routes/_authenticated/app.upi.tsx", // frozen: UPI intent internals
      // Was "src/lib/**/__tests__/**". Widened when the fence was un-silenced:
      // a test for formatMoney() cannot assert "₹12,34,567.89" without the
      // literal symbol, and src/data/__tests__/countryRegistry.test.ts does
      // exactly that. The assertion IS the check this rule exists to protect.
      "src/**/__tests__/**",
      // Vendored shadcn/ui. Its two hits are date/number formatting
      // (formatMonthDropdown, a chart tick), not money — and i18n-3 already
      // exempts this directory for the same "not our source" reason.
      "src/components/ui/**",
    ],
    rules: { "oniq/currency-fence": "error" },
  },

  // i18n-2 — RTL: physical CSS properties break mirroring for AE (dir: rtl).
  // Tailwind v4 has logical properties natively: ms-/me-/ps-/pe-,
  // text-start/end, border-s/e, start-/end-. The `rtl:` variant is only for
  // transforms (rtl:-scale-x-100). The ignores list is the pre-existing
  // backlog — NEW files must be logical from the start.
  {
    files: ["src/**/*.{ts,tsx}"],
    ignores: [
      "src/components/DirectionalToaster.tsx",
      "src/components/chat/CallOverlay.tsx",
      "src/components/chat/IncomingCallScreen.tsx",
      "src/components/earn/InviteNotification.tsx",
      "src/components/home/HomeCountryPrompt.tsx",
      "src/components/landing/LiveNewsSection.tsx",
      "src/components/moments/MomentsFeed.tsx",
      "src/components/reels/ReelTile.tsx",
      "src/components/share/ShareSheet.tsx",
      "src/components/ui/alert.tsx",
      "src/components/ui/calendar.tsx",
      "src/components/ui/carousel.tsx",
      "src/components/ui/command.tsx",
      "src/components/ui/context-menu.tsx",
      "src/components/ui/dialog.tsx",
      "src/components/ui/dropdown-menu.tsx",
      "src/components/ui/hover-card.tsx",
      "src/components/ui/menubar.tsx",
      "src/components/ui/navigation-menu.tsx",
      "src/components/ui/pagination.tsx",
      "src/components/ui/popover.tsx",
      "src/components/ui/resizable.tsx",
      "src/components/ui/select.tsx",
      "src/components/ui/sheet.tsx",
      "src/components/ui/sidebar.tsx",
      "src/components/ui/table.tsx",
      "src/components/ui/tooltip.tsx",
      "src/components/vitals/BreathingCard.tsx",
      "src/routes/_authenticated/app.ai.tsx",
      "src/routes/_authenticated/app.chat.$conversationId.tsx",
      "src/routes/_authenticated/app.chat.index.tsx",
      "src/routes/_authenticated/app.chat.me.tsx",
      "src/routes/_authenticated/app.chat.reels.tsx",
      "src/routes/_authenticated/app.chat.tsx",
      "src/routes/_authenticated/app.chat.updates.tsx",
      "src/routes/_authenticated/app.clips.tsx",
      "src/routes/_authenticated/app.faith.tsx",
      "src/routes/_authenticated/app.food.$id.tsx",
      "src/routes/_authenticated/app.index.tsx",
      "src/routes/_authenticated/app.learn.tsx",
      "src/routes/_authenticated/app.profile.tsx",
      "src/routes/_authenticated/app.rides.tsx",
      "src/routes/_authenticated/app.scan.tsx",
      "src/routes/_authenticated/app.study.tsx",
      "src/routes/_authenticated/app.tsx",
      "src/routes/_authenticated/app.u.$userId.tsx",
      "src/routes/_authenticated/app.upi.tsx",
      "src/routes/_authenticated/app.weather.tsx",
      "src/routes/auth.tsx",
      "src/routes/blog.super-apps-in-india.tsx",
      "src/routes/blog.what-is-a-super-app.tsx",
      "src/routes/child-safety.tsx",
      "src/routes/delete-account.tsx",
      "src/routes/index.tsx",
      "src/routes/privacy.tsx",
      "src/routes/terms.tsx",
    ],
    rules: { "oniq/rtl-fence": "error" },
  },

  // i18n-3 — user-facing strings should come from the translation path
  // (useT()/dictionaries.ts, or tileLabel.ts for ONIQ tile names). Warn-only:
  // this is a migration backlog, not a hard gate, and brand names are exempt
  // by design.
  {
    files: ["src/routes/**/*.tsx", "src/components/**/*.tsx"],
    ignores: ["src/components/ui/**"],
    rules: { "oniq/hardcoded-string": "warn" },
  },
  // Formatting is Prettier's job, not ESLint's. We previously ran
  // eslint-plugin-prettier, which reports every unformatted character as an
  // ESLint *error*: 6,503 of 6,630 errors (91%) came from that one rule, and a
  // real react-hooks/rules-of-hooks violation hid in the noise at 1:1,626 while
  // it took production down. ESLint deprecated its own formatting rules in
  // v8.53 for the same reason. `eslint-config-prettier` switches the whole
  // bucket off; `npm run format:check` enforces formatting separately.
  eslintConfigPrettier,
);
