"""
End-to-end chat messaging smoke test.

Signs up two throwaway users via Supabase auth (auto-confirmed), seeds their
sessions into two Playwright browser contexts, then:
  1. User A opens /app/chat, starts a New Chat with User B via username search
  2. User A sends a message containing a unique nonce
  3. User B navigates to the same conversation and asserts the nonce is visible
  4. User B replies; User A asserts B's reply appears (realtime path)

Run:
  python3 scripts/smoke/chat-messaging.py
"""
import asyncio
import json
import os
import time
import uuid
from pathlib import Path
from urllib.parse import urlparse

import requests
from playwright.async_api import async_playwright, expect

SUPABASE_URL = "https://bqwttemnnoexadpwifcj.supabase.co"
ANON_KEY = "sb_publishable_9_6W6SZU0dKts3ZUjYC0wA_QL8jpKym"
APP_URL = "http://localhost:8080"
STORAGE_KEY = f"sb-{urlparse(SUPABASE_URL).hostname.split('.')[0]}-auth-token"

SCREENSHOTS = Path("/tmp/browser/chat-messaging")
SCREENSHOTS.mkdir(parents=True, exist_ok=True)


def signup_user(tag: str) -> dict:
    """Create a fresh auto-confirmed test user and return {session, username, email}."""
    ts = int(time.time() * 1000)
    uniq = uuid.uuid4().hex[:6]
    email = f"chat-{tag}-{ts}-{uniq}@oniq.dev"
    password = f"Passw0rd!{uniq}"
    username = f"chat{tag}{ts}{uniq}"[:24].lower()
    r = requests.post(
        f"{SUPABASE_URL}/auth/v1/signup",
        headers={"apikey": ANON_KEY, "Content-Type": "application/json"},
        json={
            "email": email,
            "password": password,
            "data": {"username": username, "full_name": f"Chat Test {tag.upper()}"},
        },
        timeout=30,
    )
    r.raise_for_status()
    body = r.json()
    session = body if "access_token" in body else body.get("session")
    if not session or "access_token" not in session:
        raise RuntimeError(f"no session in signup response: {body}")
    # profiles.username is generated by handle_new_user trigger from user_metadata.username
    return {"session": session, "username": username, "email": email}


async def seed_session(context, session: dict):
    page = await context.new_page()
    await page.goto(APP_URL, wait_until="domcontentloaded")
    await page.evaluate(
        f"window.localStorage.setItem({json.dumps(STORAGE_KEY)}, {json.dumps(json.dumps(session))})"
    )
    await page.close()


async def open_chat_list(context):
    page = await context.new_page()
    page.on("console", lambda m: print(f"[console:{m.type}]", m.text) if m.type == "error" else None)
    await page.goto(f"{APP_URL}/app/chat", wait_until="domcontentloaded")
    await page.wait_for_selector("h1:has-text('Chats')", timeout=15000)
    return page


async def main():
    print("→ creating two throwaway users…")
    a = signup_user("a")
    b = signup_user("b")
    print(f"  A={a['username']}  B={b['username']}")

    # Wait a beat for the handle_new_user trigger to write profile row
    await asyncio.sleep(1.5)

    nonce_a = f"HELLO-{uuid.uuid4().hex[:8]}"
    nonce_b = f"REPLY-{uuid.uuid4().hex[:8]}"

    async with async_playwright() as pw:
        browser = await pw.chromium.launch(headless=True)
        try:
            ctx_a = await browser.new_context(viewport={"width": 420, "height": 900})
            ctx_b = await browser.new_context(viewport={"width": 420, "height": 900})

            await seed_session(ctx_a, a["session"])
            await seed_session(ctx_b, b["session"])

            # --- USER A: open chat list, start new chat with B ---
            page_a = await open_chat_list(ctx_a)
            await page_a.screenshot(path=str(SCREENSHOTS / "1_a_list.png"))

            await page_a.get_by_role("button", name="New chat").first.click()
            await page_a.get_by_placeholder("Search @username").fill(b["username"])
            # Wait for the user row to appear
            user_button = page_a.locator("button", has_text=f"@{b['username']}")
            await expect(user_button.first).to_be_visible(timeout=10000)
            await page_a.screenshot(path=str(SCREENSHOTS / "2_a_search.png"))
            await user_button.first.click()

            # Should navigate to /app/chat/<uuid>
            await page_a.wait_for_url("**/app/chat/**", timeout=10000)
            conv_url = page_a.url
            conv_id = conv_url.rsplit("/", 1)[-1]
            print(f"  conversation id: {conv_id}")

            # --- USER A sends first message ---
            input_a = page_a.get_by_placeholder("Message")
            await input_a.fill(nonce_a)
            await page_a.locator("button[type='submit']").click()
            try:
                await expect(page_a.get_by_text(nonce_a)).to_be_visible(timeout=10000)
            except Exception:
                await page_a.screenshot(path=str(SCREENSHOTS / "3_a_sent_FAIL.png"))
                print("A page HTML tail:", (await page_a.content())[-2000:])
                raise
            await page_a.screenshot(path=str(SCREENSHOTS / "3_a_sent.png"))
            print(f"  A sent: {nonce_a}")

            # --- USER B opens the same conversation, asserts A's message shows ---
            page_b = await open_chat_list(ctx_b)
            await page_b.goto(f"{APP_URL}/app/chat/{conv_id}", wait_until="domcontentloaded")
            await expect(page_b.get_by_text(nonce_a)).to_be_visible(timeout=15000)
            await page_b.screenshot(path=str(SCREENSHOTS / "4_b_received.png"))
            print(f"  B sees A's message ✓")

            # --- USER B replies; USER A must see it (realtime) ---
            await page_b.get_by_placeholder("Message").fill(nonce_b)
            await page_b.locator("button[type='submit']").click()
            await expect(page_b.get_by_text(nonce_b)).to_be_visible(timeout=10000)

            await expect(page_a.get_by_text(nonce_b)).to_be_visible(timeout=15000)
            await page_a.screenshot(path=str(SCREENSHOTS / "5_a_realtime.png"))
            print(f"  A sees B's reply via realtime ✓")

            print("\n✅ PASS — chat messaging works end-to-end for both users")
        finally:
            await browser.close()


if __name__ == "__main__":
    asyncio.run(main())
