// The cinema lexicon — thesaurus-grade vocabulary for the video pipeline.
//
// GENERATED FROM VERIFIED RESEARCH, 2026-08-11: the published prompt guides
// for Veo 3.1 (Google Cloud), Runway Gen-3/Gen-4 (official), Kling (official
// + MushroomFleet), Wan2.2, LTX-Video and the snubroot/LichAmnesia prompt
// repositories — every source URL fetched and confirmed on-topic before a
// term was kept. VFX terms are constrained to what a video model can ADD to
// an existing frame (atmosphere, particles, light, optics, motion) — never
// object transformations. See movieGrammar.ts for why that line exists.
//
// USED BY SAMPLING, NEVER BY DUMPING. ~550 terms would crowd a plan prompt
// out of its own token budget; story-plot draws a small deterministic palette
// per film (seeded by the user's prompt) so different films reach different
// corners of the vocabulary while any one prompt stays bounded.

/** Prompt grammar from the published guides: camera, framing, lens, lighting, grade, pacing, Veo audio syntax. */
export const PROMPT_GRAMMAR: Record<string, readonly string[]> = {
  camera_moves_and_rigs: [
    "dolly in",
    "dolly out",
    "dolly shot",
    "push-in",
    "pull back",
    "pull-back",
    "slow dolly-in",
    "tracking shot",
    "camera tracks / follows the subject",
    "pan left",
    "pan right",
    "slow pan",
    "whip pan",
    "tilt up",
    "tilt down",
    "crane shot",
    "crane-up",
    "high-angle crane shot",
    "orbit",
    "arc",
    "smooth 180-degree arc shot",
    "360-degree orbit",
    "aerial view",
    "drone / aerial shot",
    "FPV",
    "continuous hyperspeed FPV footage",
    "hand held / handheld",
    "subtle handheld shake, documentary feel",
    "SnorriCam",
    "camcorder",
    "locked-off",
    "static shot",
    "low angle static shot",
    "camera holds completely static",
    "zoom in",
    "zoom out",
    "drift",
  ],
  shot_framing: [
    "extreme wide shot (EWS)",
    "wide shot (WS)",
    "establishing wide",
    "medium shot (MS)",
    "close-up (CU)",
    "extreme close-up (ECU)",
    "ultra-wide angle",
    "two-shot",
    "over the shoulder",
    "POV shot",
    "reverse shot",
    "low angle",
    "high angle",
    "overhead",
    "low hero angle",
    "three-quarter",
    "eye level",
    "framing from waist up",
    "(thats where the camera is)",
  ],
  lens_language: [
    "50mm lens",
    "100mm",
    "macro lens",
    "macro cinematography",
    "wide-angle lens",
    "telephoto",
    "telephoto compression (flattens background)",
    "shallow depth of field",
    "deep focus",
    "soft focus",
    "rack focus",
    "bokeh",
    "razor-sharp at f2.8",
    "anamorphic flare",
    "lens flare",
    "extreme macro push-in",
  ],
  lighting_setups: [
    "diffused lighting",
    "silhouette",
    "back lit / backlight",
    "side lit",
    "colored gel lighting",
    "lens flare",
    "three-point lighting",
    "warm key light",
    "subtle fill",
    "rim lighting / rim light",
    "hard key",
    "softbox / diffused overhead softbox",
    "side-window light",
    "edge light",
    "practicals",
    "Rembrandt lighting",
    "butterfly lighting",
    "chiaroscuro",
    "golden hour",
    "single, dramatic spotlight",
    "harsh fluorescent overhead lights",
    "green glow of the monochrome monitor",
    "soft morning light",
    "ambient lighting",
    "morning light",
    "sunset light",
    "artificial lighting",
    "Tyndall effect",
    "top light rakes the surface",
    "dewy specular highlights",
  ],
  film_stock_and_grade: [
    "shot as if on 1980s color film",
    "slightly grainy",
    "35mm grain",
    "retro aesthetic",
    "photorealistic",
    "cinematic",
    "moody",
    "glitchcore",
    "film noir",
    "cinematic color grading",
    "warm orange tones in highlights, cool blue shadows",
    "desaturated color palette with selective color emphasis",
    "vibrant colors with high saturation",
    "warm golden",
    "cool cyan",
    "rich saturated",
    "neutral grade",
    "cool blue tones",
    "melancholic mood",
    "realistic style",
    "realistic documentary",
  ],
  motion_pacing: [
    "slow motion",
    "hyperspeed",
    "timelapse",
    "grows",
    "emerges",
    "explodes",
    "slow",
    "smooth",
    "gentle",
    "fast",
    "crisp",
    "deliberate",
    "natural movement, realistic physics",
    "slow and deliberate movement",
    "smooth, flowing motion",
    "dynamic, high-energy actions",
    "building to a crescendo",
    "settle / logo reveal (final beat)",
    "beads trembling and sliding",
    "dust hanging in the still air",
  ],
  audio_dialogue_syntax_veo: [
    'A woman says, "We have to leave now."',
    "(Tone: weary, delivery style)",
    "SFX: thunder cracks in the distance",
    "SFX: the rustle of dense leaves, distant exotic bird calls",
    "Ambient noise: the quiet hum of a starship bridge",
    "A swelling, gentle orchestral score begins to play",
    "Audio: uplifting orchestral music with strings and brass, building to an inspiring crescendo",
    "Audio: sizzling pan, chopping vegetables, boiling water, utensils clinking, kitchen cooking ambiance",
    "Implied sound: faint glass chimes, distant birdsong, one slow breath",
    "no subtitles, no watermarks, no text overlays (negative prompt)",
    "dialogue under 8 seconds (~20-25 syllables)",
  ],
  prompt_structure_formulas: [
    "[Cinematography] + [Subject] + [Action] + [Context] + [Style & Ambiance] (Veo)",
    "Subject / Action / Scene / Style / Dialogue / Sounds / Technical-Negative (Veo, snubroot)",
    "[camera movement]: [establishing scene]. [additional details]. (Runway Gen-3)",
    "natural-language motion direction, positive phrasing only (Runway Gen-4)",
    "Prompt = Subject (Description) + Subject Movement + Scene (Description) + (Camera Language + Lighting + Atmosphere) (Kling)",
    "Subject + Scene + Motion + Aesthetic Control + Stylization (Wan2.2)",
    "Aesthetic Control = Light Source + Lighting Environment + Shot Size + Camera Angle + Lens + Camera Movement (Wan2.2)",
    "single-sentence action first, chronological shot list, <200 words (LTX-Video)",
    "(6s · 9:16 · tags) parenthetical spec (LichAmnesia)",
    "no warping, drift, melting, duplication, or flicker (fidelity guard)",
  ],
};

/** Atmosphere/effects a video model can add to a frame, by category. */
export const VFX_LEXICON: Record<string, readonly string[]> = {
  particles: [
    "drifting dust motes",
    "dust motes swirling in a light shaft",
    "fine suspended particulate catching the light",
    "glowing embers rising",
    "ember shower drifting on the wind",
    "sparks scattering upward",
    "flakes of ash falling",
    "volcanic ash drifting",
    "pollen drifting on the breeze",
    "dandelion seeds floating past",
    "cottonwood fluff drifting",
    "cherry blossom petals falling",
    "rose petals swirling",
    "gently falling snowflakes",
    "fat snowflakes tumbling",
    "wind-driven snow flurries",
    "diamond dust glittering in the air",
    "frost particles sparkling",
    "drifting luminous spores",
    "bioluminescent spores floating",
    "fireflies blinking in the dusk",
    "a swarm of fireflies drifting",
    "confetti raining down",
    "confetti cannon burst",
    "ticker tape fluttering down",
    "gold glitter particles suspended in the air",
    "shimmering glitter dust",
    "iridescent soap bubbles drifting",
    "chalk dust puffing into the air",
    "colored powder bursting midair",
    "flour dust hanging in the light",
    "feathers drifting down slowly",
    "backlit insect swarm shimmering",
    "moths fluttering around a lamp",
    "static motes hanging in still air",
    "sawdust drifting in workshop light",
  ],
  weather: [
    "light drizzle misting down",
    "steady rainfall",
    "torrential downpour",
    "driving rain lashing sideways",
    "rain sheeting off rooftops",
    "backlit rain streaks",
    "raindrops splashing on pavement",
    "rain dripping from eaves",
    "monsoon rain hammering down",
    "sun shower sparkling",
    "freezing rain glazing surfaces",
    "sleet falling",
    "hail bouncing off the ground",
    "fine misting rain",
    "ground fog rolling in",
    "thick fog bank swallowing the scene",
    "morning mist rising off fields",
    "sea fog drifting ashore",
    "valley fog pooling below",
    "patchy fog drifting",
    "swirling mist",
    "gusting wind",
    "howling gale-force wind",
    "wind rippling across tall grass",
    "wind-whipped dust racing along the ground",
    "dust storm rolling in",
    "towering haboob dust wall approaching",
    "sandstorm scouring the landscape",
    "dust devil spinning across the flats",
    "blizzard whiteout",
    "snow flurries swirling",
    "spindrift blowing off snow crests",
    "distant lightning flickering",
    "forked lightning splitting the sky",
    "sheet lightning pulsing inside clouds",
    "heat lightning on the horizon",
    "storm front rolling overhead",
    "virga trailing beneath distant clouds",
    "rainbow emerging after the rain",
  ],
  fire_and_light: [
    "flickering candlelight",
    "guttering candle flame",
    "dancing campfire flames",
    "roaring bonfire glow",
    "crackling hearth fire",
    "flames licking at the edge of frame",
    "smoldering embers pulsing",
    "glowing coals breathing with heat",
    "fire whirl spiraling upward",
    "torchlight flickering on stone walls",
    "lantern glow swaying",
    "warm firelight flicker playing across faces",
    "gaslight flicker",
    "neon glow washing the scene",
    "neon sign buzzing and flickering",
    "sodium vapor streetlight glow",
    "warm window glow at dusk",
    "god rays breaking through clouds",
    "crepuscular rays fanning across the sky",
    "volumetric light shafts through dusty air",
    "sunbeams filtering through the forest canopy",
    "dappled light shifting through leaves",
    "rippling water caustics playing on walls",
    "shimmering pool caustics",
    "specular glints flashing off surfaces",
    "sun glare flaring off glass",
    "rim light glow outlining the subject",
    "halo of backlight",
    "searchlight beams sweeping",
    "strobe light flashes",
    "paparazzi flashbulbs popping",
    "shower of welding sparks",
    "spark burst scattering",
    "moonbeams slanting through mist",
    "soft moonlight glow",
    "light spill blooming from a doorway",
  ],
  water: [
    "concentric ripples spreading outward",
    "rain rings dimpling a pond",
    "gentle ripples catching the light",
    "shimmering water surface",
    "glassy reflections trembling on water",
    "dancing light reflections off the harbor",
    "sea spray bursting off rocks",
    "drifting ocean spray mist",
    "whitecaps rolling across the bay",
    "churning foam",
    "sea foam washing up the sand",
    "waves lapping at the shore",
    "breakers crashing in slow rhythm",
    "rolling ocean swell",
    "cascading waterfall",
    "waterfall mist drifting downstream",
    "plunge-pool spray billowing",
    "rushing whitewater rapids",
    "splashing droplets frozen mid-air",
    "water droplets beading and racing down glass",
    "condensation trickling down a cold bottle",
    "slow dripping water rings",
    "puddle splashes rippling",
    "rain-slicked streets mirroring neon",
    "underwater light rays wavering",
    "streams of bubbles rising underwater",
    "swirling underwater sediment",
    "drifting underwater particulate",
    "morning dew glistening on grass",
    "backlit spray glittering in the sun",
    "fountain spray arcing and misting",
    "fine irrigation mist hanging over fields",
    "steam rising off a hot spring",
  ],
  magic_energy_vfx: [
    "soft magical glow",
    "pulsing arcane aura",
    "radiant halo of light",
    "shimmering aura outlining the figure",
    "glowing particle trail",
    "trailing streaks of light",
    "sparkling pixie dust cascading",
    "drifting motes of golden light",
    "glowing runes hovering in the air",
    "floating glyphs of light",
    "luminous sigils slowly rotating",
    "swirling energy wisps",
    "wisps of glowing vapor curling",
    "ethereal light tendrils reaching",
    "crackling electricity",
    "electric arcs jumping between points",
    "static sparks snapping",
    "tesla-coil arcs writhing",
    "lightning tendrils crawling",
    "plasma glow rippling",
    "filaments of plasma weaving",
    "ribbons of energy undulating",
    "luminous orbs drifting lazily",
    "will-o'-the-wisp lights bobbing",
    "spectral glow seeping in",
    "ghostly luminescence",
    "bioluminescent shimmer",
    "iridescent shimmer washing over surfaces",
    "prismatic light refracting",
    "heat-shimmer energy distortion",
    "shockwave ripple distorting the air",
    "force-field shimmer",
    "stardust sparkle drifting",
    "comet-like trail of light",
    "embers of magic floating upward",
  ],
  optical_lens_effects: [
    "shallow depth of field with creamy bokeh",
    "bokeh balls of out-of-focus city lights",
    "swirly vintage-lens bokeh",
    "hexagonal bokeh highlights",
    "oval anamorphic bokeh",
    "cinematic lens flare",
    "anamorphic lens flare",
    "horizontal blue anamorphic streak flare",
    "veiling flare washing the frame",
    "ghosting flare artifacts trailing the light source",
    "polygonal aperture ghosts",
    "starburst highlights",
    "sunstar glinting at frame edge",
    "highlight bloom",
    "soft blooming highlights",
    "halation glow around bright lights",
    "warm red halation edges",
    "dreamy diffusion filter glow",
    "pro-mist filter softness",
    "chromatic aberration fringing at the edges",
    "subtle purple fringing on highlights",
    "gentle vignette darkening the corners",
    "heavy vignetting",
    "fine 35mm film grain",
    "coarse 16mm film grain",
    "film gate weave",
    "film dust and scratches flickering",
    "warm light leaks at the frame edges",
    "flickering projector shutter effect",
    "subtle rolling-shutter wobble",
    "streaking motion blur",
    "long-exposure light trails",
    "lens breathing during focus shift",
    "slow rack focus pull",
    "tilt-shift miniature blur",
    "dreamlike soft focus",
    "double-exposure ghosting",
    "glimmerglass sparkle diffusion",
  ],
  atmosphere_haze: [
    "soft atmospheric haze",
    "volumetric haze catching the light",
    "diffusion haze hanging in the room",
    "thin smoke haze layering the air",
    "golden hour haze",
    "heat haze shimmering above asphalt",
    "mirage shimmer on the horizon",
    "humid tropical haze",
    "dusty desert haze",
    "urban smog layer on the skyline",
    "aerial perspective fading the distant hills",
    "layered mountain haze receding",
    "misty depth layers between trees",
    "morning haze glowing",
    "blue hour atmosphere",
    "twilight gloom settling in",
    "moody overcast gloom",
    "dense atmosphere revealing light beams",
    "tyndall scattering in the still air",
    "milky backlit haze",
    "moonlit haze",
    "ethereal glow suffusing the air",
    "cool damp cellar murk",
    "smoke-laden tavern air",
    "shimmering aurora borealis overhead",
    "hazy sun disc glowing through overcast",
  ],
  smoke_vapor: [
    "wispy smoke tendrils curling",
    "cigarette smoke coiling in a shaft of light",
    "incense smoke spiraling upward",
    "thin wisps of smoke drifting",
    "billowing smoke clouds",
    "thick smoke rolling low",
    "black oily smoke churning",
    "white steam plumes rising",
    "steam venting from a manhole",
    "steam curling off a coffee cup",
    "steam swirling above street food stalls",
    "visible breath fogging in cold air",
    "theatrical fog drifting across the stage",
    "colored smoke plumes unfurling",
    "smoke grenade plume drifting",
    "chimney smoke drifting into the sky",
    "campfire smoke curling through trees",
    "smoldering smoke seeping upward",
    "dry-ice fog spilling low across the floor",
    "ground-hugging fog creeping",
    "cryo fog jets bursting",
    "swirling vapor eddies",
    "turbulent smoke curls",
    "backlit smoke swirling in slow motion",
    "smoke rings drifting apart",
    "mist wafting off wet pavement",
    "vapor rising from rain-soaked ground",
    "fog machine haze diffusing the light",
    "gunpowder smoke hanging after the blast",
    "pyrotechnic smoke burst",
  ],
  debris_environment_motion: [
    "autumn leaves swirling in the wind",
    "leaves skittering across pavement",
    "dead leaves tumbling end over end",
    "petals scattering on the breeze",
    "tumbleweed rolling past",
    "grass rippling in waves",
    "wheat field swaying in the wind",
    "reeds bending and swaying",
    "tree branches swaying overhead",
    "foliage rustling in the gusts",
    "curtains billowing at an open window",
    "sheer drapes drifting in the breeze",
    "banners rippling",
    "flags snapping in the wind",
    "pennants fluttering",
    "laundry flapping on a line",
    "cloth billowing in slow motion",
    "a cloak billowing dramatically",
    "hair lifting in the wind",
    "loose papers swirling upward",
    "newspaper pages tumbling down the street",
    "book pages fluttering open",
    "a plastic bag drifting on the wind",
    "dust kicked up by passing footsteps",
    "dust puffs bursting on impact",
    "trickles of dust falling from ceiling cracks",
    "plaster dust sifting down",
    "straw and chaff drifting",
    "streamers waving overhead",
    "ribbons trailing in the wind",
    "paper lanterns swaying",
    "hanging signs swinging gently",
    "snow sliding off burdened branches",
  ],
  crowd_background_motion: [
    "bustling crowd milling in the background",
    "pedestrians streaming past out of focus",
    "blurred passersby crossing the frame",
    "commuters crisscrossing the concourse",
    "distant figures strolling",
    "silhouetted crowd swaying",
    "crowd swaying in unison to the music",
    "hands waving above a concert crowd",
    "phone flashlights swaying in the dark",
    "cheering crowd surging",
    "traffic streaming past in the background",
    "headlights streaking along the avenue",
    "distant traffic flowing across the bridge",
    "cyclists gliding through frame",
    "a flock of birds wheeling overhead",
    "pigeons scattering into flight",
    "butterflies fluttering through the garden",
    "market stalls bustling with activity",
    "background diners chatting and gesturing softly",
    "children chasing each other in the far background",
  ],
  time_effects: [
    "timelapse clouds streaming overhead",
    "cloud shadows sweeping across the landscape",
    "day-to-night timelapse transition",
    "stars wheeling in a night-sky timelapse",
    "star trails circling the pole star",
    "the milky way drifting across the sky",
    "sunlight sweeping across the valley",
    "shadows creeping across the floor",
    "a slow light sweep across the scene",
    "golden light crawling over rooftops at dawn",
    "dreamy slow motion drift",
    "ultra slow motion droplet impact",
    "speed-ramped motion",
    "frozen bullet-time moment",
    "traffic light trails at night",
    "city lights twinkling in timelapse",
    "tide receding in timelapse",
    "fog rolling through in timelapse",
    "moonrise timelapse over the ridge",
    "hyperlapse rush through the streets",
  ],
  color_grade_moods: [
    "teal and orange blockbuster grade",
    "warm golden hour grade",
    "amber tungsten warmth",
    "cool steel-blue grade",
    "moody desaturated grade",
    "bleach bypass look",
    "high-contrast film noir grade",
    "low-key chiaroscuro mood",
    "silvery moonlit grade",
    "pastel dawn palette",
    "rosy magic-hour glow",
    "sepia-toned nostalgia",
    "faded vintage film look",
    "kodachrome color palette",
    "technicolor saturation",
    "cross-processed color shift",
    "day-for-night blue wash",
    "neon-soaked cyberpunk palette",
    "sodium-vapor orange cast",
    "sickly fluorescent green cast",
    "candy-colored hyper-saturation",
    "muted earth-tone grade",
    "overcast grey palette",
    "misty blue-grey melancholy",
    "emerald forest tones",
    "honeyed backlit warmth",
    "crushed blacks with deep contrast",
    "lifted milky shadows",
    "35mm film print emulation",
    "vhs color bleed and soft noise",
    "dreamy overexposed whites",
  ],
};

/** Deterministic 32-bit hash — the palette seed. Same prompt, same palette. */
export function seedOf(text: string): number {
  let h = 2166136261;
  for (let i = 0; i < text.length; i++) {
    h ^= text.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

function pick(seed: number, arr: readonly string[], n: number): string[] {
  const out: string[] = [];
  const taken = new Set<number>();
  let s = seed || 1;
  const want = Math.min(n, arr.length);
  while (out.length < want) {
    s = (Math.imul(s, 1664525) + 1013904223) >>> 0;
    const i = s % arr.length;
    if (taken.has(i)) continue;
    taken.add(i);
    out.push(arr[i]);
  }
  return out;
}

/**
 * The per-film palette: a bounded sample of the lexicon, seeded by the user's
 * prompt so re-planning the same idea explores the same corner while
 * different ideas get different vocabulary. Sized to stay a small fraction of
 * the plan prompt.
 */
export function paletteFor(promptText: string): string {
  const seed = seedOf(promptText);
  const cam = pick(seed ^ 0x1, PROMPT_GRAMMAR.camera_moves_and_rigs, 10);
  const light = pick(seed ^ 0x2, PROMPT_GRAMMAR.lighting_setups, 8);
  const lens = pick(seed ^ 0x3, PROMPT_GRAMMAR.lens_language, 5);
  const grade = pick(seed ^ 0x4, PROMPT_GRAMMAR.film_stock_and_grade, 5);
  const vfxCats = Object.values(VFX_LEXICON);
  const vfx: string[] = [];
  vfxCats.forEach((catTerms, i) => {
    vfx.push(...pick(seed ^ (0x10 + i), catTerms, 2));
  });
  return [
    "PALETTE for this film — draw motion, lighting and vfx language from these",
    "(they are suggestions of register, not a checklist):",
    `- camera: ${cam.join("; ")}`,
    `- light: ${light.join("; ")}`,
    `- lens: ${lens.join("; ")}`,
    `- grade: ${grade.join("; ")}`,
    `- atmosphere & effects: ${pick(seed ^ 0x99, vfx, 14).join("; ")}`,
  ].join("\n");
}
