// Story engine — THE CAST THE GENERATOR CAN ACTUALLY SEE.
//
// The 74-entry casting manifest and the 55 uploaded house-style frames lived
// in src/data/ from the day they arrived (2026-08-18) and were imported by
// nothing but their own test. Everything that spends money on a generation —
// story-plot, story-still, the worker — ran without ever knowing a cast
// existed, so a user asking for "a shepherd on a ridge" got whatever the
// model invented that minute, while a matching hand-painted frame sat unused
// in the repo.
//
// This is that catalogue, mirrored where the generator runs. Every entry is
// the owner's manifest description; `frame` is the in-repo picture of that
// same subject when one exists (37 of 74 — the rest have an id in the
// external tool but no picture here yet).
//
// `attachable` is false on every entry, and that is not an oversight.
// StoryStyleRef types it as the literal `false`: the whole library is 2D, and
// the ep3/ep4 runbook lets only 3D sheets reach a generation as an attachment.
// This field exists so the rule travels with the data — the day a 3D frame is
// uploaded, it is the one place that has to change.
//
// GENERATED BY scripts/gen-story-cast.mjs, NOT HAND-WRITTEN. src/data/__tests__/storyCastMemory.test.ts
// re-derives this file from src/data/storyCharacterRefs.ts and
// src/data/storyStyleRefs.ts and fails if the two drift apart. Edit the
// source catalogues, never this mirror.

export type StoryCastMember = {
  region: string;
  description: string;
  /** Relative path of the in-repo frame of this subject, when one exists. */
  frame?: string;
  /** False for every 2D frame. Only a 3D sheet could ever be attached. */
  attachable?: boolean;
};

export const STORY_CAST: readonly StoryCastMember[] = [
  {
    region: "Jamaica",
    description: "Fishmonger woman arranging fresh fish, Port Antonio coastal market",
    frame:
      "/__l5e/assets-v1/f38f998a-f2ec-4a41-99d0-726a89b2edb7/story-style-caribbean-fish-market.png",
    attachable: false,
  },
  {
    region: "Mexico",
    description: "Oaxacan weaver working a backstrap loom in a sunlit courtyard",
    frame:
      "/__l5e/assets-v1/ab8469a7-5727-48b6-b3ba-afac56d03acf/story-style-oaxacan-weaver-sheet.png",
    attachable: false,
  },
  {
    region: "Haiti",
    description: "Young girl skipping rope in a Jacmel schoolyard",
    frame: "/__l5e/assets-v1/b255dfb5-c412-43b8-9dbc-21b1e2ddbfe4/jacmel-skipping-girl.jpg",
    attachable: false,
  },
  {
    region: "Guatemala",
    description: "Maya teenage boy carrying maize basket near Lake Atitlan",
    frame: "/__l5e/assets-v1/0fa54632-c833-457b-8e56-c9a9071f3d6a/atitlan-maize-boy.jpg",
    attachable: false,
  },
  {
    region: "Cuba",
    description: "Elderly musician playing guitar on a Havana balcony",
    frame: "/__l5e/assets-v1/422f778f-a6d6-4974-b2af-c9918a886d85/havana-balcony-musician.jpg",
    attachable: false,
  },
  {
    region: "Panama",
    description: "Guna Yala woman arranging mola textiles, San Blas Islands",
    frame: "/__l5e/assets-v1/12f929c8-394d-4dc0-8da4-b5b7afb15649/guna-yala-mola-sheet.jpg",
    attachable: false,
  },
  {
    region: "Brazil",
    description: "Carnival samba dancer mid-motion, Salvador street parade",
    frame: "/__l5e/assets-v1/669819e3-d9b1-49f9-900b-3b300d540be2/salvador-samba-dancer.jpg",
    attachable: false,
  },
  {
    region: "Colombia",
    description: "Coffee farmer hand-picking cherries, Zona Cafetera",
    frame: "/__l5e/assets-v1/8264919b-46a7-47c6-88e6-846555956006/zona-cafetera-coffee-picker.jpg",
    attachable: false,
  },
  {
    region: "Peru",
    description: "Amazonian shaman-healer arranging medicinal plants, Iquitos",
    frame: "/__l5e/assets-v1/d923b0ef-3ba6-4284-a3b6-301f0f9cd42a/iquitos-shaman-healer.jpg",
    attachable: false,
  },
  {
    region: "Venezuela",
    description: "Warao woman weaving a hammock, Orinoco Delta",
    frame: "/__l5e/assets-v1/c1119c91-d808-4dcb-8e8f-92b65e5cd7fa/warao-hammock-weaver-sheet.jpg",
    attachable: false,
  },
  {
    region: "Bolivia",
    description: "Aymara market vendor with layered textiles, El Alto",
    frame: "/__l5e/assets-v1/17ce178b-72b2-455b-8a7f-c2e926c0403e/bolivian-aymara-sheet.png",
    attachable: false,
  },
  {
    region: "Ecuador",
    description: "Kichwa river guide paddling a canoe, Napo River",
    frame: "/__l5e/assets-v1/082ec13f-ae4b-41fe-b920-86143315e8c1/amazon-canoe.png",
    attachable: false,
  },
  {
    region: "Chile",
    description: "Patagonian shepherd guiding sheep, Torres del Paine",
    frame:
      "/__l5e/assets-v1/1012184c-aee6-4d03-aa9d-63285cd87513/story-style-patagonian-shepherd.png",
    attachable: false,
  },
  {
    region: "United States",
    description: "Diner cook flipping food on a griddle, rural Louisiana",
    frame: "/__l5e/assets-v1/3db00542-11be-46c7-9bed-7960c22eb5ca/story-style-diner-cook-night.png",
    attachable: false,
  },
  {
    region: "United States",
    description: "Navajo healer grinding herbs outside a hogan, Arizona",
    frame: "/__l5e/assets-v1/aff51fb2-826d-43e1-b503-d06e9828965d/navajo-healer-hogan.jpg",
    attachable: false,
  },
  { region: "Australia", description: "Outback stockman mustering cattle near Alice Springs" },
  {
    region: "United States (Alaska)",
    description: "Yupik carver shaping walrus ivory by lamplight, Bethel",
  },
  {
    region: "Canada (Arctic)",
    description: "Inuit grandmother telling a story inside an iglu",
    frame:
      "/__l5e/assets-v1/f68744e1-3a45-4347-bbcd-1f61e170b1fc/iglu-storytelling-grandmother.jpg",
    attachable: false,
  },
  {
    region: "United States (Hawaii)",
    description: "Native Hawaiian carver shaping a tiki figure, Hilo",
    frame: "/__l5e/assets-v1/8ad00499-b6db-4221-804d-8fd751e009bb/hilo-tiki-carver.jpg",
    attachable: false,
  },
  {
    region: "Egypt",
    description: "Boatman steering a felucca sailboat on the Nile, Aswan",
    frame:
      "/__l5e/assets-v1/0c8241d8-21e6-4e53-b29f-2bdab7dabba3/story-style-nile-felucca-sailor.png",
    attachable: false,
  },
  {
    region: "Ethiopia",
    description: "Coffee ceremony host pouring from a jebena pot, Lalibela",
    frame: "/__l5e/assets-v1/f369eba0-3369-4f43-87f4-3eeb04e377e5/story-style-ethiopian-coffee.png",
    attachable: false,
  },
  {
    region: "South Africa",
    description: "Zulu beadwork artist threading a loom, KwaZulu-Natal",
    frame: "/__l5e/assets-v1/730b533f-f848-41af-9d42-c0d8581e341f/zulu-beadwork-artist-sheet.png",
    attachable: false,
  },
  {
    region: "Nigeria",
    description: "Yoruba drummer playing a talking drum, Lagos street celebration",
    frame: "/__l5e/assets-v1/46b77b1d-eca9-42ef-8d86-74c0bf50f707/lagos-talking-drummer.png",
    attachable: false,
  },
  {
    region: "Madagascar",
    description: "Rice farmer planting terraced paddies in the highlands",
    frame: "/__l5e/assets-v1/99c70ef7-1c89-4dfd-a349-00456cac582d/madagascar-rice-planter.png",
    attachable: false,
  },
  {
    region: "Morocco",
    description: "Spice merchant scooping spices at a Marrakech market stall",
    frame: "/__l5e/assets-v1/c67badf9-c9e3-4e32-aa92-83dfce924e34/marrakech-spice-merchant.jpg",
    attachable: false,
  },
  { region: "Morocco", description: "Desert guide with a camel atop a Sahara dune at sunset" },
  {
    region: "Ghana",
    description: "Kente weaver at a narrow-strip loom, Kumasi",
    frame: "/__l5e/assets-v1/47a4417d-fb58-493d-a4a0-5bf40e5d714f/kumasi-kente-weaver.jpg",
    attachable: false,
  },
  {
    region: "Tanzania",
    description: "Clove harvester on a spice plantation, Zanzibar",
    frame: "/__l5e/assets-v1/b81e3ee1-a57d-4c41-ae98-baf5ea8a3ec7/zanzibar-clove-harvester.jpg",
    attachable: false,
  },
  {
    region: "Papua New Guinea",
    description: "Boy running with a hoop on a jungle-fringed beach, Madang",
    frame: "/__l5e/assets-v1/f5b40e2b-011b-479d-a9dd-9a70c44eda98/madang-hoop-boy.jpg",
    attachable: false,
  },
  {
    region: "Greece",
    description: "Fisherman mending nets on a whitewashed harbor, Cyclades",
    frame: "/__l5e/assets-v1/dec667e1-3536-4c9b-a30a-3a22c9585c6c/story-style-greek-fisherman.png",
    attachable: false,
  },
  {
    region: "Italy",
    description: "Glassblower shaping molten glass, Murano, Venice",
    frame:
      "/__l5e/assets-v1/88e87f3f-f7a6-49c4-8cf3-1de0b38762eb/story-style-glassblower-night.png",
    attachable: false,
  },
  {
    region: "Poland",
    description: "Elderly woodcarver at a snow-covered cottage, Zakopane",
    frame: "/__l5e/assets-v1/572fffff-294b-472d-8356-15f30965e09c/story-style-woodcarver-snow.png",
    attachable: false,
  },
  {
    region: "Turkey",
    description: "Tea house owner pouring tulip-glass tea, Istanbul",
    frame: "/__l5e/assets-v1/a3bbf43f-37a0-4fda-aded-577159c00d58/anatolian-tea-house.png",
    attachable: false,
  },
  {
    region: "Germany",
    description: "Glass-ornament maker painting details, Ore Mountains",
    frame: "/__l5e/assets-v1/d44e3bfe-1ce3-4dff-b533-aa6cd133d382/bavarian-ornament-painter.png",
    attachable: false,
  },
  {
    region: "Ireland",
    description: "Fiddler performing in a stone pub, County Clare",
    frame: "/__l5e/assets-v1/931e9f6d-b615-4205-a5a7-0cb7a4319f33/irish-pub-fiddler.png",
    attachable: false,
  },
  {
    region: "Iceland",
    description: "Sheep farmer beside a geothermal spring under midnight sun",
    frame: "/__l5e/assets-v1/2d34fb08-47d4-405c-a07c-8252bbd48ffc/icelandic-shepherd.png",
    attachable: false,
  },
  {
    region: "Russia",
    description: "Siberian trapper checking a fur trap line, Lake Baikal",
    frame: "/__l5e/assets-v1/aaa241f5-7b39-40d1-a1b3-b4778f0ba36b/siberian-trapper.png",
    attachable: false,
  },
  {
    region: "Wales",
    description: "Blacksmith hammering glowing metal at a forge, Cardiff",
    frame: "/__l5e/assets-v1/3f5cc2af-f338-4e64-bf96-543a595a73f2/welsh-blacksmith.png",
    attachable: false,
  },
  {
    region: "Spain",
    description: "Flamenco dancer mid-spin in a Seville courtyard",
    frame: "/__l5e/assets-v1/64ea4730-b593-4217-a5f5-3b74d4e830f6/seville-flamenco-dancer.jpg",
    attachable: false,
  },
  {
    region: "Netherlands",
    description: "Tulip farmer walking fields at dawn, Lisse",
    frame: "/__l5e/assets-v1/b35ac521-cd8d-4c49-a31c-059775becff1/lisse-tulip-farmer.jpg",
    attachable: false,
  },
  {
    region: "Portugal",
    description: "Fisherman's wife mending nets, Nazare",
    frame: "/__l5e/assets-v1/15b6681b-1b87-4fe1-a6c2-b56d5df22d11/nazare-net-mender.jpg",
    attachable: false,
  },
  { region: "France", description: "Vintner inspecting grapes in a Bordeaux vineyard" },
  { region: "Croatia", description: "Fisherman hauling in nets at a stone harbor, Hvar" },
  {
    region: "Denmark",
    description: "Baker arranging pastries in a Copenhagen shop window",
    frame: "/__l5e/assets-v1/1c9d753c-b1dc-418f-8cca-1e846c650249/copenhagen-pastry-baker.jpg",
    attachable: false,
  },
  {
    region: "Switzerland",
    description: "Alpine cheesemaker stirring curd in a copper cauldron, Zermatt",
  },
  {
    region: "Austria",
    description: "Woodcutter splitting logs outside an alpine cabin, Salzburg",
    frame: "/__l5e/assets-v1/4ea709fb-d5bb-4a99-8e16-ae689c3547e1/salzburg-woodcutter.jpg",
    attachable: false,
  },
  {
    region: "Georgia",
    description: "Polyphonic singer at a village feast, Svaneti",
    frame: "/__l5e/assets-v1/68af067c-99ee-4799-812e-c5a90ab830e8/svaneti-polyphonic-singer.jpg",
    attachable: false,
  },
  {
    region: "Armenia",
    description: "Stonemason carving a khachkar cross-stone, Lake Sevan",
    frame:
      "/__l5e/assets-v1/0125f489-ed7e-489b-b390-18aa17dc4629/story-style-armenian-stonemason-sheet.png",
    attachable: false,
  },
  {
    region: "Uzbekistan",
    description: "Ceramicist painting blue glaze patterns, Samarkand",
    frame: "/__l5e/assets-v1/5f25285e-328c-4b0b-81c6-b2b171982cc4/story-style-uzbek-ceramicist.png",
    attachable: false,
  },
  {
    region: "South Korea",
    description: "Potter shaping clay on a wheel, Icheon",
    frame:
      "/__l5e/assets-v1/874f0d2f-98d8-4556-a04e-4580affad423/story-style-korean-potter-sheet.png",
    attachable: false,
  },
  {
    region: "Mongolia",
    description: "Herder standing before a ger tent on the steppe",
    frame: "/__l5e/assets-v1/f41d1df5-dc2c-4091-8059-90ce431f9c84/story-style-mongolian-herder.png",
    attachable: false,
  },
  {
    region: "Tibet",
    description: "Monk spinning a prayer wheel at dawn, Lhasa",
    frame:
      "/__l5e/assets-v1/444b8473-2c5c-4d76-b067-f4426f2b17df/story-style-tibetan-monk-sheet.png",
    attachable: false,
  },
  {
    region: "Thailand",
    description: "Longtail boat driver steering through karst waters, Krabi",
    frame: "/__l5e/assets-v1/5e7e3acd-ea26-4556-bf83-07035ef1ef3d/story-style-thai-longtail.png",
    attachable: false,
  },
  {
    region: "Indonesia",
    description: "Balinese dancer mid-pose in a temple courtyard, Ubud",
    frame: "/__l5e/assets-v1/64c3777b-7b9d-4d42-bf26-d0063451680a/story-style-balinese-dancer.png",
    attachable: false,
  },
  {
    region: "Sri Lanka",
    description: "Tea picker on a misty highland plantation",
    frame: "/__l5e/assets-v1/f900cee2-4603-47df-8450-9f5b5422f90a/story-style-tea-picker-sheet.png",
    attachable: false,
  },
  {
    region: "Kashmir",
    description: "Shawl weaver at a handloom, Srinagar",
    frame: "/__l5e/assets-v1/e6dd13a9-8cc0-44b5-91b7-cfb25509ad61/kashmiri-carpet-weaver.png",
    attachable: false,
  },
  {
    region: "Myanmar",
    description: "Novice monk carrying an alms bowl at dawn, Bagan",
    frame: "/__l5e/assets-v1/a805e9de-f24c-46d9-8de2-1cf70776701b/bagan-alms-round.png",
    attachable: false,
  },
  {
    region: "Cambodia",
    description: "Stone carver working sandstone reliefs, Angkor Wat",
    frame: "/__l5e/assets-v1/c13ab392-779f-4373-a365-290e6aeebe79/khmer-stone-carver.png",
    attachable: false,
  },
  {
    region: "Singapore",
    description: "Hawker cook tossing noodles in a flaming wok",
    frame: "/__l5e/assets-v1/ad8c3231-da69-454d-812c-83288e6000bc/singapore-hawker.png",
    attachable: false,
  },
  {
    region: "Kurdistan region",
    description: "Shepherd on a ridge overlooking a valley, Zagros mountains",
    frame: "/__l5e/assets-v1/b3b2b11f-101c-42f7-8f78-e2a1dc6762d7/anatolian-shepherd.png",
    attachable: false,
  },
  {
    region: "Lebanon",
    description: "Baker pulling manakish from a stone oven, Beirut",
    frame: "/__l5e/assets-v1/4dddfcc7-a664-416c-9306-a3b2b98da066/mediterranean-baker.png",
    attachable: false,
  },
  { region: "China", description: "Astronomer gazing through an armillary sphere, Beijing" },
  {
    region: "India",
    description: "Bharatanatyam dancer mid-pose, Chennai temple stage",
    frame: "/__l5e/assets-v1/18feebf4-1906-42d8-b467-d0e5ae3fbaa0/chennai-bharatanatyam.jpg",
    attachable: false,
  },
  {
    region: "Bhutan",
    description: "Archer drawing a bamboo bow at a village contest, Paro",
    frame: "/__l5e/assets-v1/47f7ff03-4a28-4915-9e36-f54129e8c7c7/paro-archery-contest.jpg",
    attachable: false,
  },
  {
    region: "Fiji",
    description: "Outrigger sailor at the bow, skimming a turquoise lagoon",
    frame: "/__l5e/assets-v1/87ed804d-a564-46b1-9dbd-d3c7de4a0218/polynesian-outrigger.png",
    attachable: false,
  },
  {
    region: "Fantasy",
    description: "Polynesian wave-caller commanding a spirit-shark wave",
    frame: "/__l5e/assets-v1/6e63b9df-c046-4935-82eb-22961a771f80/polynesian-wave-caller.jpg",
    attachable: false,
  },
  {
    region: "Fantasy",
    description: "Sahel griot-mage summoning firefly-spirits at night",
    frame:
      "/__l5e/assets-v1/0c056167-9532-4512-b4c0-0d8a8878f92d/story-style-griot-spirit-night.png",
    attachable: false,
  },
  {
    region: "Fantasy",
    description: "Andean sky-sorceress channeling energy on a floating platform",
    frame:
      "/__l5e/assets-v1/2940ea1b-8f36-42d0-b6a6-911f688a2e39/story-style-andean-sky-temple.png",
    attachable: false,
  },
  {
    region: "Fantasy",
    description: "Dragon-tamer girl reaching toward a cloud-dragon",
    frame: "/__l5e/assets-v1/6ddf85ca-986f-44cb-98ce-d532dbf9678f/dragon-tamer-cloud.jpg",
    attachable: false,
  },
  {
    region: "Fantasy",
    description: "Nordic rune-wizard before a glacier ice palace",
    frame: "/__l5e/assets-v1/74ca8247-b45c-42d4-80e1-d7d094a605d6/nordic-rune-wizard.jpg",
    attachable: false,
  },
  {
    region: "Fantasy",
    description: "Glowing brass astrolabe artifact on a scholar's desk",
    frame: "/__l5e/assets-v1/bc78e413-8c2d-4cc4-b541-0b8dba356f18/brass-astrolabe-artifact.jpg",
    attachable: false,
  },
  {
    region: "Fantasy",
    description: "West African iron-forged guardian spirit in a sacred grove",
    frame: "/__l5e/assets-v1/de79cdc8-26ef-49b8-b513-206b250669f9/iron-forged-guardian.jpg",
    attachable: false,
  },
  {
    region: "Fantasy",
    description: "Celestial librarian among towering glowing scrolls",
    frame: "/__l5e/assets-v1/9bdca0bb-89f7-412a-8d9f-50033569f3cb/celestial-librarian.jpg",
    attachable: false,
  },
  {
    region: "Fantasy",
    description: "Slavic firebird keeper cradling a glowing chick",
    frame: "/__l5e/assets-v1/8b33159f-17ff-43f5-9929-9c8938753429/slavic-firebird-keeper.jpg",
    attachable: false,
  },
];

/**
 * Words too common to identify anybody. Without this list "a woman in the
 * market" scores against every market entry in the manifest at once.
 */
const STOP = new Set([
  "with",
  "from",
  "that",
  "this",
  "near",
  "into",
  "over",
  "under",
  "atop",
  "onto",
  "a",
  "an",
  "the",
  "and",
  "at",
  "on",
  "in",
  "of",
  "his",
  "her",
  "their",
  "its",
  "young",
  "elderly",
  "old",
  "man",
  "woman",
  "boy",
  "girl",
  "people",
  "person",
]);

const words = (s: string) =>
  s
    .toLowerCase()
    .split(/[^a-z]+/)
    .filter((w) => w.length >= 4 && !STOP.has(w));

/** Every cast member's identifying words, computed once at module load. */
const KEYS: readonly (readonly string[])[] = STORY_CAST.map((c) => [
  ...new Set([...words(c.region), ...words(c.description)]),
]);

/**
 * The cast this prompt is asking for, best match first.
 *
 * Deterministic and offline — the same prompt picks the same people on every
 * retry, which is what keeps a re-run of a failed shot looking like the shots
 * around it. Scoring is plain word overlap; two matching words is the floor,
 * because one shared word ("market", "boat") is a coincidence, not a casting.
 */
export function castFor(prompt: string, limit = 4): StoryCastMember[] {
  const asked = new Set(words(prompt));
  if (asked.size === 0) return [];
  const scored: { i: number; score: number }[] = [];
  for (let i = 0; i < KEYS.length; i++) {
    let score = 0;
    for (const k of KEYS[i]) if (asked.has(k)) score++;
    if (score >= 2) scored.push({ i, score });
  }
  // Ties break by manifest order, so the result never depends on sort stability.
  scored.sort((a, b) => b.score - a.score || a.i - b.i);
  return scored.slice(0, limit).map((s) => STORY_CAST[s.i]);
}

/**
 * The cast block for a plan prompt — empty string when nobody matches, so a
 * caller can concatenate it unconditionally.
 *
 * This is DIRECTION, not a constraint: the manifest describes people ONIQ has
 * already drawn, and a story set among them should look like them. A story
 * that matches nobody is left entirely alone.
 */
export function castBlock(prompt: string): string {
  const cast = castFor(prompt);
  if (cast.length === 0) return "";
  const rows = cast.map((c) => `- ${c.region}: ${c.description}`).join("\n");
  return (
    "ONIQ HOUSE CAST. These people are already part of ONIQ's world and are " +
    "drawn in the house style. Where the story allows one of them, cast them " +
    "instead of inventing someone new, and carry the description into the " +
    "character's lock so every still of them matches:\n" +
    rows
  );
}
