// Story engine — THE CAST THE GENERATOR CAN ACTUALLY SEE.
//
// The 74-entry casting manifest and the 55 uploaded house-style frames lived
// in src/data/ from the day they arrived (2026-08-18) and were imported by
// nothing but their own test. Everything that spends money on a generation —
// story-plot, story-still, the worker — ran without ever knowing a cast
// existed, so a user asking for "a shepherd on a ridge" got whatever the
// model invented that minute, while a matching hand-painted frame sat unused
// in the repo.
//
// This is that catalogue, mirrored where the generator runs. Every entry is
// the owner's manifest description; `frame` is the in-repo picture of that
// same subject when one exists (37 of 74 — the rest have an id in the
// external tool but no picture here yet).
//
// `attachable` follows the ep3/ep4 runbook rule already written into
// storyStyleRefs.ts: a finished SCENE may be handed to a generation as a look
// reference; a 2D character SHEET may not, ever. It carries multiple views on
// one canvas, and a model handed one paints the sheet, not the shot.
//
// GENERATED BY scripts/gen-story-cast.mjs, NOT HAND-WRITTEN. src/data/__tests__/storyCastMemory.test.ts
// re-derives this file from src/data/storyCharacterRefs.ts and
// src/data/storyStyleRefs.ts and fails if the two drift apart. Edit the
// source catalogues, never this mirror.

export type StoryCastMember = {
  region: string;
  description: string;
  /** Relative path of the in-repo frame of this subject, when one exists. */
  frame?: string;
  /** Scenes may be attached to a generation; character sheets never may. */
  attachable?: boolean;
};

export const STORY_CAST: readonly StoryCastMember[] = [
  {
    region: "Jamaica",
    description: "Fishmonger woman arranging fresh fish, Port Antonio coastal market",
    frame:
      "/__l5e/assets-v1/f38f998a-f2ec-4a41-99d0-726a89b2edb7/story-style-caribbean-fish-market.png",
    attachable: true,
  },
  {
    region: "Mexico",
    description: "Oaxacan weaver working a backstrap loom in a sunlit courtyard",
    frame:
      "/__l5e/assets-v1/ab8469a7-5727-48b6-b3ba-afac56d03acf/story-style-oaxacan-weaver-sheet.png",
    attachable: false,
  },
  { region: "Haiti", description: "Young girl skipping rope in a Jacmel schoolyard" },
  { region: "Guatemala", description: "Maya teenage boy carrying maize basket near Lake Atitlan" },
  { region: "Cuba", description: "Elderly musician playing guitar on a Havana balcony" },
  { region: "Panama", description: "Guna Yala woman arranging mola textiles, San Blas Islands" },
  { region: "Brazil", description: "Carnival samba dancer mid-motion, Salvador street parade" },
  { region: "Colombia", description: "Coffee farmer hand-picking cherries, Zona Cafetera" },
  { region: "Peru", description: "Amazonian shaman-healer arranging medicinal plants, Iquitos" },
  { region: "Venezuela", description: "Warao woman weaving a hammock, Orinoco Delta" },
  {
    region: "Bolivia",
    description: "Aymara market vendor with layered textiles, El Alto",
    frame: "/__l5e/assets-v1/17ce178b-72b2-455b-8a7f-c2e926c0403e/bolivian-aymara-sheet.png",
    attachable: false,
  },
  {
    region: "Ecuador",
    description: "Kichwa river guide paddling a canoe, Napo River",
    frame: "/__l5e/assets-v1/082ec13f-ae4b-41fe-b920-86143315e8c1/amazon-canoe.png",
    attachable: true,
  },
  {
    region: "Chile",
    description: "Patagonian shepherd guiding sheep, Torres del Paine",
    frame:
      "/__l5e/assets-v1/1012184c-aee6-4d03-aa9d-63285cd87513/story-style-patagonian-shepherd.png",
    attachable: true,
  },
  {
    region: "United States",
    description: "Diner cook flipping food on a griddle, rural Louisiana",
    frame: "/__l5e/assets-v1/3db00542-11be-46c7-9bed-7960c22eb5ca/story-style-diner-cook-night.png",
    attachable: true,
  },
  { region: "United States", description: "Navajo healer grinding herbs outside a hogan, Arizona" },
  { region: "Australia", description: "Outback stockman mustering cattle near Alice Springs" },
  {
    region: "United States (Alaska)",
    description: "Yupik carver shaping walrus ivory by lamplight, Bethel",
  },
  { region: "Canada (Arctic)", description: "Inuit grandmother telling a story inside an iglu" },
  {
    region: "United States (Hawaii)",
    description: "Native Hawaiian carver shaping a tiki figure, Hilo",
  },
  {
    region: "Egypt",
    description: "Boatman steering a felucca sailboat on the Nile, Aswan",
    frame:
      "/__l5e/assets-v1/0c8241d8-21e6-4e53-b29f-2bdab7dabba3/story-style-nile-felucca-sailor.png",
    attachable: true,
  },
  {
    region: "Ethiopia",
    description: "Coffee ceremony host pouring from a jebena pot, Lalibela",
    frame: "/__l5e/assets-v1/f369eba0-3369-4f43-87f4-3eeb04e377e5/story-style-ethiopian-coffee.png",
    attachable: true,
  },
  {
    region: "South Africa",
    description: "Zulu beadwork artist threading a loom, KwaZulu-Natal",
    frame: "/__l5e/assets-v1/730b533f-f848-41af-9d42-c0d8581e341f/zulu-beadwork-artist-sheet.png",
    attachable: false,
  },
  {
    region: "Nigeria",
    description: "Yoruba drummer playing a talking drum, Lagos street celebration",
    frame: "/__l5e/assets-v1/46b77b1d-eca9-42ef-8d86-74c0bf50f707/lagos-talking-drummer.png",
    attachable: true,
  },
  {
    region: "Madagascar",
    description: "Rice farmer planting terraced paddies in the highlands",
    frame: "/__l5e/assets-v1/99c70ef7-1c89-4dfd-a349-00456cac582d/madagascar-rice-planter.png",
    attachable: true,
  },
  { region: "Morocco", description: "Spice merchant scooping spices at a Marrakech market stall" },
  { region: "Morocco", description: "Desert guide with a camel atop a Sahara dune at sunset" },
  { region: "Ghana", description: "Kente weaver at a narrow-strip loom, Kumasi" },
  { region: "Tanzania", description: "Clove harvester on a spice plantation, Zanzibar" },
  {
    region: "Papua New Guinea",
    description: "Boy running with a hoop on a jungle-fringed beach, Madang",
  },
  {
    region: "Greece",
    description: "Fisherman mending nets on a whitewashed harbor, Cyclades",
    frame: "/__l5e/assets-v1/dec667e1-3536-4c9b-a30a-3a22c9585c6c/story-style-greek-fisherman.png",
    attachable: true,
  },
  {
    region: "Italy",
    description: "Glassblower shaping molten glass, Murano, Venice",
    frame:
      "/__l5e/assets-v1/88e87f3f-f7a6-49c4-8cf3-1de0b38762eb/story-style-glassblower-night.png",
    attachable: true,
  },
  {
    region: "Poland",
    description: "Elderly woodcarver at a snow-covered cottage, Zakopane",
    frame: "/__l5e/assets-v1/572fffff-294b-472d-8356-15f30965e09c/story-style-woodcarver-snow.png",
    attachable: true,
  },
  {
    region: "Turkey",
    description: "Tea house owner pouring tulip-glass tea, Istanbul",
    frame: "/__l5e/assets-v1/a3bbf43f-37a0-4fda-aded-577159c00d58/anatolian-tea-house.png",
    attachable: true,
  },
  {
    region: "Germany",
    description: "Glass-ornament maker painting details, Ore Mountains",
    frame: "/__l5e/assets-v1/d44e3bfe-1ce3-4dff-b533-aa6cd133d382/bavarian-ornament-painter.png",
    attachable: true,
  },
  {
    region: "Ireland",
    description: "Fiddler performing in a stone pub, County Clare",
    frame: "/__l5e/assets-v1/931e9f6d-b615-4205-a5a7-0cb7a4319f33/irish-pub-fiddler.png",
    attachable: true,
  },
  {
    region: "Iceland",
    description: "Sheep farmer beside a geothermal spring under midnight sun",
    frame: "/__l5e/assets-v1/2d34fb08-47d4-405c-a07c-8252bbd48ffc/icelandic-shepherd.png",
    attachable: true,
  },
  {
    region: "Russia",
    description: "Siberian trapper checking a fur trap line, Lake Baikal",
    frame: "/__l5e/assets-v1/aaa241f5-7b39-40d1-a1b3-b4778f0ba36b/siberian-trapper.png",
    attachable: true,
  },
  {
    region: "Wales",
    description: "Blacksmith hammering glowing metal at a forge, Cardiff",
    frame: "/__l5e/assets-v1/3f5cc2af-f338-4e64-bf96-543a595a73f2/welsh-blacksmith.png",
    attachable: true,
  },
  { region: "Spain", description: "Flamenco dancer mid-spin in a Seville courtyard" },
  { region: "Netherlands", description: "Tulip farmer walking fields at dawn, Lisse" },
  { region: "Portugal", description: "Fisherman's wife mending nets, Nazare" },
  { region: "France", description: "Vintner inspecting grapes in a Bordeaux vineyard" },
  { region: "Croatia", description: "Fisherman hauling in nets at a stone harbor, Hvar" },
  { region: "Denmark", description: "Baker arranging pastries in a Copenhagen shop window" },
  {
    region: "Switzerland",
    description: "Alpine cheesemaker stirring curd in a copper cauldron, Zermatt",
  },
  { region: "Austria", description: "Woodcutter splitting logs outside an alpine cabin, Salzburg" },
  { region: "Georgia", description: "Polyphonic singer at a village feast, Svaneti" },
  {
    region: "Armenia",
    description: "Stonemason carving a khachkar cross-stone, Lake Sevan",
    frame:
      "/__l5e/assets-v1/0125f489-ed7e-489b-b390-18aa17dc4629/story-style-armenian-stonemason-sheet.png",
    attachable: false,
  },
  {
    region: "Uzbekistan",
    description: "Ceramicist painting blue glaze patterns, Samarkand",
    frame: "/__l5e/assets-v1/5f25285e-328c-4b0b-81c6-b2b171982cc4/story-style-uzbek-ceramicist.png",
    attachable: true,
  },
  {
    region: "South Korea",
    description: "Potter shaping clay on a wheel, Icheon",
    frame:
      "/__l5e/assets-v1/874f0d2f-98d8-4556-a04e-4580affad423/story-style-korean-potter-sheet.png",
    attachable: false,
  },
  {
    region: "Mongolia",
    description: "Herder standing before a ger tent on the steppe",
    frame: "/__l5e/assets-v1/f41d1df5-dc2c-4091-8059-90ce431f9c84/story-style-mongolian-herder.png",
    attachable: true,
  },
  {
    region: "Tibet",
    description: "Monk spinning a prayer wheel at dawn, Lhasa",
    frame:
      "/__l5e/assets-v1/444b8473-2c5c-4d76-b067-f4426f2b17df/story-style-tibetan-monk-sheet.png",
    attachable: false,
  },
  {
    region: "Thailand",
    description: "Longtail boat driver steering through karst waters, Krabi",
    frame: "/__l5e/assets-v1/5e7e3acd-ea26-4556-bf83-07035ef1ef3d/story-style-thai-longtail.png",
    attachable: true,
  },
  {
    region: "Indonesia",
    description: "Balinese dancer mid-pose in a temple courtyard, Ubud",
    frame: "/__l5e/assets-v1/64c3777b-7b9d-4d42-bf26-d0063451680a/story-style-balinese-dancer.png",
    attachable: true,
  },
  {
    region: "Sri Lanka",
    description: "Tea picker on a misty highland plantation",
    frame: "/__l5e/assets-v1/f900cee2-4603-47df-8450-9f5b5422f90a/story-style-tea-picker-sheet.png",
    attachable: false,
  },
  {
    region: "Kashmir",
    description: "Shawl weaver at a handloom, Srinagar",
    frame: "/__l5e/assets-v1/e6dd13a9-8cc0-44b5-91b7-cfb25509ad61/kashmiri-carpet-weaver.png",
    attachable: true,
  },
  {
    region: "Myanmar",
    description: "Novice monk carrying an alms bowl at dawn, Bagan",
    frame: "/__l5e/assets-v1/a805e9de-f24c-46d9-8de2-1cf70776701b/bagan-alms-round.png",
    attachable: true,
  },
  {
    region: "Cambodia",
    description: "Stone carver working sandstone reliefs, Angkor Wat",
    frame: "/__l5e/assets-v1/c13ab392-779f-4373-a365-290e6aeebe79/khmer-stone-carver.png",
    attachable: true,
  },
  {
    region: "Singapore",
    description: "Hawker cook tossing noodles in a flaming wok",
    frame: "/__l5e/assets-v1/ad8c3231-da69-454d-812c-83288e6000bc/singapore-hawker.png",
    attachable: true,
  },
  {
    region: "Kurdistan region",
    description: "Shepherd on a ridge overlooking a valley, Zagros mountains",
    frame: "/__l5e/assets-v1/b3b2b11f-101c-42f7-8f78-e2a1dc6762d7/anatolian-shepherd.png",
    attachable: true,
  },
  {
    region: "Lebanon",
    description: "Baker pulling manakish from a stone oven, Beirut",
    frame: "/__l5e/assets-v1/4dddfcc7-a664-416c-9306-a3b2b98da066/mediterranean-baker.png",
    attachable: true,
  },
  { region: "China", description: "Astronomer gazing through an armillary sphere, Beijing" },
  { region: "India", description: "Bharatanatyam dancer mid-pose, Chennai temple stage" },
  { region: "Bhutan", description: "Archer drawing a bamboo bow at a village contest, Paro" },
  {
    region: "Fiji",
    description: "Outrigger sailor at the bow, skimming a turquoise lagoon",
    frame: "/__l5e/assets-v1/87ed804d-a564-46b1-9dbd-d3c7de4a0218/polynesian-outrigger.png",
    attachable: true,
  },
  { region: "Fantasy", description: "Polynesian wave-caller commanding a spirit-shark wave" },
  {
    region: "Fantasy",
    description: "Sahel griot-mage summoning firefly-spirits at night",
    frame:
      "/__l5e/assets-v1/0c056167-9532-4512-b4c0-0d8a8878f92d/story-style-griot-spirit-night.png",
    attachable: true,
  },
  {
    region: "Fantasy",
    description: "Andean sky-sorceress channeling energy on a floating platform",
    frame:
      "/__l5e/assets-v1/2940ea1b-8f36-42d0-b6a6-911f688a2e39/story-style-andean-sky-temple.png",
    attachable: true,
  },
  { region: "Fantasy", description: "Dragon-tamer girl reaching toward a cloud-dragon" },
  { region: "Fantasy", description: "Nordic rune-wizard before a glacier ice palace" },
  { region: "Fantasy", description: "Glowing brass astrolabe artifact on a scholar's desk" },
  { region: "Fantasy", description: "West African iron-forged guardian spirit in a sacred grove" },
  { region: "Fantasy", description: "Celestial librarian among towering glowing scrolls" },
  { region: "Fantasy", description: "Slavic firebird keeper cradling a glowing chick" },
];

/**
 * Words too common to identify anybody. Without this list "a woman in the
 * market" scores against every market entry in the manifest at once.
 */
const STOP = new Set([
  "with",
  "from",
  "that",
  "this",
  "near",
  "into",
  "over",
  "under",
  "atop",
  "onto",
  "a",
  "an",
  "the",
  "and",
  "at",
  "on",
  "in",
  "of",
  "his",
  "her",
  "their",
  "its",
  "young",
  "elderly",
  "old",
  "man",
  "woman",
  "boy",
  "girl",
  "people",
  "person",
]);

const words = (s: string) =>
  s
    .toLowerCase()
    .split(/[^a-z]+/)
    .filter((w) => w.length >= 4 && !STOP.has(w));

/** Every cast member's identifying words, computed once at module load. */
const KEYS: readonly (readonly string[])[] = STORY_CAST.map((c) => [
  ...new Set([...words(c.region), ...words(c.description)]),
]);

/**
 * The cast this prompt is asking for, best match first.
 *
 * Deterministic and offline — the same prompt picks the same people on every
 * retry, which is what keeps a re-run of a failed shot looking like the shots
 * around it. Scoring is plain word overlap; two matching words is the floor,
 * because one shared word ("market", "boat") is a coincidence, not a casting.
 */
export function castFor(prompt: string, limit = 4): StoryCastMember[] {
  const asked = new Set(words(prompt));
  if (asked.size === 0) return [];
  const scored: { i: number; score: number }[] = [];
  for (let i = 0; i < KEYS.length; i++) {
    let score = 0;
    for (const k of KEYS[i]) if (asked.has(k)) score++;
    if (score >= 2) scored.push({ i, score });
  }
  // Ties break by manifest order, so the result never depends on sort stability.
  scored.sort((a, b) => b.score - a.score || a.i - b.i);
  return scored.slice(0, limit).map((s) => STORY_CAST[s.i]);
}

/**
 * The cast block for a plan prompt — empty string when nobody matches, so a
 * caller can concatenate it unconditionally.
 *
 * This is DIRECTION, not a constraint: the manifest describes people ONIQ has
 * already drawn, and a story set among them should look like them. A story
 * that matches nobody is left entirely alone.
 */
export function castBlock(prompt: string): string {
  const cast = castFor(prompt);
  if (cast.length === 0) return "";
  const rows = cast.map((c) => `- ${c.region}: ${c.description}`).join("\n");
  return (
    "ONIQ HOUSE CAST. These people are already part of ONIQ's world and are " +
    "drawn in the house style. Where the story allows one of them, cast them " +
    "instead of inventing someone new, and carry the description into the " +
    "character's lock so every still of them matches:\n" +
    rows
  );
}
