/**
 * OQCA v1.7 — the owner directive of 2026-09-11, tested where it can be.
 *
 * THE HARD RULE IS THE ONE THIS FILE EXISTS FOR: _"Do not make ONIQ appear
 * autonomous through scripted demonstrations. The test must be able to prove
 * that the decision was generated by the runtime from observed state, rather
 * than being preselected by the test. The system must be able to surprise the
 * test within defined acceptance constraints."_
 *
 * A test that fed one world and asserted one goal id would satisfy every
 * functional requirement and prove nothing — the id would be a fact about the
 * fixture. So the §5 block below never names an expected winner. It asserts
 * INVARIANTS that hold whatever ONIQ decides (the winner is the argmax of the
 * published score; the winner's subject is one the observer actually reported;
 * two different worlds give two different answers) and then drives sixty
 * pseudo-random worlds whose winners nobody here knows.
 */
import { describe, expect, it } from "vitest";
import { contentHash } from "../math/hash.ts";
import {
  type Observation,
  FAULT_SEVERITY,
  OBSERVATION_KINDS,
  UNKNOWN_SEVERITY,
  UNOBSERVED_SEVERITY,
  actionable,
  completeObservations,
  observationCoverage,
  observed,
  systemHealth,
  unknown,
  unobserved,
} from "../autonomy/observation.ts";
import {
  EMPTY_CENSUS,
  UNIDENTIFIED,
  buildWorldState,
  describeWorld,
  worldConcerns,
} from "../autonomy/world.ts";
import {
  NEUTRAL_PLANNING,
  concernGap,
  concernId,
  dependencyOf,
  goalFor,
  informationGainOf,
  knowledgeNeeds,
  planImprovements,
  planningModifier,
  researchDecision,
  statusOf,
  uncertaintyOf,
} from "../autonomy/improve.ts";
import { MODIFIER_FLOOR, rankLearningTargets } from "../autonomy/select.ts";
import { objectivesFromImprovements } from "../autonomy/objective.ts";
import { EMPTY_KNOWLEDGE } from "../knowledge/model.ts";
import {
  DURABLE_SCHEMA_VERSION,
  NO_DURABLE_STORE,
  durableFingerprint,
  fromDurable,
  hydrate,
  toDurable,
  validateDurable,
} from "../knowledge/substrate/durable.ts";
import { draftRecord } from "../knowledge/substrate/record.ts";
import { makeEvidence } from "../knowledge/substrate/evidence.ts";
import { EMPTY_PROVENANCE, withActivity } from "../knowledge/substrate/provenance.ts";
import {
  IMPROVEMENT_UNVERIFIED,
  blocked as experimentBlocked,
  compare,
  design,
  failureLesson,
  measurement,
  unmeasured,
  verifiedImprovements,
} from "../autonomy/experiment.ts";
import { curriculum, curriculumCycles, selfEvaluate } from "../autonomy/selfEval.ts";
/**
 * THE RUNTIME MODULES ARE IMPORTED HERE FOR A REASON BEYOND TESTING THEM.
 * `tsconfig.json`'s `include` is `src/**` only, so a file under
 * `supabase/functions/` is typechecked ONLY when something under `src/` reaches
 * it. The first draft of `improvement.ts` called `ctx.staleness?.()` — a field
 * `SubstrateContext` has never had — and `tsc --noEmit` came back CLEAN,
 * because nothing imported the file. That is this repository's most-recorded
 * failure arriving in the typechecker itself. These imports are what put the
 * four new runtime modules into the program.
 */
import {
  CAPABILITY_REGISTRY,
  MAX_ARGS,
  MAX_ARG_LENGTH,
  NO_EXECUTOR,
  executeCapability,
  isRegistered,
  registeredCapability,
  resourcesFor,
} from "../../../supabase/functions/_shared/oqcaRuntime/selfModel.ts";
import {
  type EvidenceItem,
  NO_EVIDENCE,
  makeSystemObserver,
  observationFrom,
} from "../../../supabase/functions/_shared/oqcaRuntime/observe.ts";
import {
  MAX_LOCAL_FINDINGS,
  MIN_SUBSTANCE,
  MIN_TERM_LENGTH,
  makeLocalEvidenceResearch,
  searchTerms,
  substance,
} from "../../../supabase/functions/_shared/oqcaRuntime/research.ts";
import {
  makeSinkDurableStore,
  mergeDurable,
} from "../../../supabase/functions/_shared/oqcaRuntime/durableStore.ts";

const PROV = {
  locator: "src/x.ts:1",
  sourceVersion: "v1",
  contentHash: "abc",
  agent: "test",
  at: "2026-09-11T00:00:00.000Z",
} as const;

function fault(kind: Observation["kind"], subject: string, severity: number, value = 1) {
  return observed(kind, subject, {
    value,
    detail: `${subject} detail`,
    severity,
    provenance: PROV,
  });
}

describe("v1.7 §3 — OBSERVED / UNOBSERVED / UNKNOWN are three states", () => {
  it("a refused observer produces one UNOBSERVED row per kind, carrying its reason", () => {
    const rows = completeObservations({ ok: false, reason: "no eye" });
    expect(rows).toHaveLength(OBSERVATION_KINDS.length);
    expect(rows.every((r) => r.state === "UNOBSERVED")).toBe(true);
    expect(rows.every((r) => r.detail.includes("no eye"))).toBe(true);
    // §3's own sentence: no observation is not healthy.
    expect(systemHealth(rows)).toBe("insufficient_evidence");
  });

  it("a partial observer leaves the kinds it did not mention UNOBSERVED, not absent", () => {
    const rows = completeObservations({
      ok: true,
      observations: [fault("test_health", "suite", 0.9)],
    });
    expect(rows).toHaveLength(OBSERVATION_KINDS.length);
    expect(rows.filter((r) => r.state === "OBSERVED")).toHaveLength(1);
    expect(systemHealth(rows)).toBe("degraded");
    expect(observationCoverage(rows)).toBeCloseTo(1 / OBSERVATION_KINDS.length, 10);
  });

  it("an all-clear observer is the only way to reach no_fault_observed", () => {
    const rows = OBSERVATION_KINDS.map((k) => fault(k, k, 0, 0));
    expect(systemHealth(rows)).toBe("no_fault_observed");
    // A zero-severity row is healthy and is therefore NOT actionable — the
    // distinction that keeps "we looked and it is fine" out of the backlog.
    expect(actionable(rows)).toHaveLength(0);
  });

  it("severity ranks a measured fault above an unrun probe above an unlooked kind", () => {
    expect(UNOBSERVED_SEVERITY).toBeLessThan(UNKNOWN_SEVERITY);
    expect(UNKNOWN_SEVERITY).toBeLessThan(FAULT_SEVERITY);
  });

  it("the host's reading becomes UNKNOWN when it could not say how bad", () => {
    const item: EvidenceItem = {
      kind: "latency",
      subject: "story-dispatch",
      locator: "x.ts",
      sourceVersion: null,
      contentHash: null,
      detail: "the probe ran and returned nothing usable",
      value: null,
      severity: null,
      requires: ["RUN_BENCHMARK"],
    };
    const o = observationFrom(item, "2026-09-11T00:00:00.000Z");
    expect(o.state).toBe("UNKNOWN");
    expect(o.provenance?.locator).toBe("x.ts");
    expect(o.requires).toEqual(["RUN_BENCHMARK"]);
    // ZERO IS NOT NULL: the same item with severity 0 is a reading, not a hole.
    expect(observationFrom({ ...item, severity: 0 }, "t").state).toBe("OBSERVED");
  });

  it("an unregistered capability name is dropped rather than carried", () => {
    const o = observationFrom(
      {
        kind: "test_health",
        subject: "s",
        locator: "x",
        sourceVersion: null,
        contentHash: null,
        detail: "d",
        value: null,
        severity: 0.5,
        requires: ["RUN_TEST_SUITE", "rm -rf /", "SUMMON_A_SHELL"],
      },
      "t",
    );
    expect(o.requires).toEqual(["RUN_TEST_SUITE"]);
  });

  it("the observer refuses when the host's evidence source does", async () => {
    const obs = makeSystemObserver(NO_EVIDENCE, () => "t");
    const got = await obs({ episode: 0, step: 0 });
    expect(got.ok).toBe(false);
  });
});

/* ================================================================ *
 * §5 + THE HARD RULE
 * ================================================================ */

function worldOf(observations: readonly Observation[]) {
  return buildWorldState({
    identity: UNIDENTIFIED,
    identityProvenance: null,
    observations: completeObservations({ ok: true, observations }),
    capabilities: [],
    knowledge: EMPTY_CENSUS,
    backlog: [],
    experiments: [],
    baselines: new Map(),
    failureLog: [],
  });
}

function planOf(observations: readonly Observation[]) {
  return planImprovements({
    world: worldOf(observations),
    knowledge: EMPTY_KNOWLEDGE,
    focus: null,
    capabilities: [],
    needs: () => [],
  });
}

describe("v1.7 HARD RULE — the decision is generated from observed state", () => {
  it("two different worlds produce two different top concerns, neither named here", () => {
    const a = planOf([fault("test_health", "suite-alpha", 0.9)]);
    const b = planOf([fault("latency", "dispatch-beta", 0.9)]);
    expect(a.length).toBeGreaterThan(0);
    expect(b.length).toBeGreaterThan(0);
    // THE ASSERTION IS THAT THEY DIFFER, not what either one is. Changing what
    // the observer reports changes the answer, which is the whole claim.
    expect(a[0].goal.id).not.toBe(b[0].goal.id);
    expect(a.map((p) => p.goal.id)).not.toEqual(b.map((p) => p.goal.id));
    // And each winner is traceable to a row its own observer actually reported,
    // rather than to one of the eighteen holes `completeObservations` fills in.
    expect(a[0].observation.state).toBe("OBSERVED");
    expect(a[0].observation.subject).toBe("suite-alpha");
    expect(b[0].observation.subject).toBe("dispatch-beta");
  });

  it("a measured fault outranks a hole, and a small one does not — MEASURED, not asserted", () => {
    // THE NUMBERS ARE WRITTEN DOWN BECAUSE THE FIRST DRAFT'S WERE ALL ZERO.
    // `dependencyOf` returned a fraction that is 0 for any subject no other
    // observation mentions, and six multiplied factors mean one zero kills the
    // rest: every concern scored 0.000000 and the plan ranked ALPHABETICALLY.
    // These three values are what the machinery actually produces now.
    const plan = planOf([fault("test_health", "suite", 0.9), fault("latency", "dispatch", 0.5)]);
    const score = (id: string) => plan.find((p) => p.goal.id === id)?.score ?? -1;
    const hole = plan.find((p) => p.observation.state === "UNOBSERVED")?.score ?? -1;
    expect(score("improve:test_health:suite")).toBeCloseTo(0.0972, 6);
    expect(hole).toBeCloseTo(0.0504, 6);
    expect(score("improve:latency:dispatch")).toBeCloseTo(0.03, 6);
    // So `UNOBSERVED_SEVERITY`'s own claim — a hole sits BELOW a real observed
    // failure — holds of the COMPOSITE and not only of the severity, which is
    // the level a reader would otherwise have to take on trust. And a hole
    // still outranks a mild fault, which is the honest ordering: ONIQ cannot
    // verify an improvement in something it has never measured.
    expect(score("improve:test_health:suite")).toBeGreaterThan(hole);
    expect(hole).toBeGreaterThan(score("improve:latency:dispatch"));
    expect(plan.every((p) => p.score > 0)).toBe(true);
  });

  it("the winner is the argmax of the published score, on sixty worlds nobody here predicts", () => {
    // A DETERMINISTIC PSEUDO-RANDOM WORLD GENERATOR, so the fixture cannot have
    // been shaped around a known answer and the run is still reproducible.
    let seed = 20260911;
    const rnd = () => {
      seed = (seed * 1103515245 + 12345) % 2147483648;
      return seed / 2147483648;
    };
    let sawFault = 0;
    let sawHole = 0;
    for (let trial = 0; trial < 60; trial += 1) {
      const n = 1 + Math.floor(rnd() * 5);
      const rows: Observation[] = [];
      for (let i = 0; i < n; i += 1) {
        const kind = OBSERVATION_KINDS[Math.floor(rnd() * OBSERVATION_KINDS.length)];
        const subject = `s${Math.floor(rnd() * 4)}`;
        const roll = rnd();
        rows.push(
          roll < 0.5
            ? fault(kind, subject, rnd())
            : roll < 0.75
              ? unknown(kind, subject, "probe inconclusive", PROV)
              : unobserved(kind, subject, "not wired"),
        );
      }
      const planned = planOf(rows);
      if (planned.length === 0) continue;
      // INVARIANT 1: the reported order IS the score order.
      for (let i = 1; i < planned.length; i += 1) {
        expect(planned[i - 1].score).toBeGreaterThanOrEqual(planned[i].score);
      }
      // INVARIANT 2: the winner is the maximum score, whatever it turned out to be.
      const best = Math.max(...planned.map((p) => p.score));
      expect(planned[0].score).toBeCloseTo(best, 12);
      // INVARIANT 3: every concern traces to a row the world actually holds.
      const ids = new Set(worldOf(rows).observations.map((o) => o.id));
      expect(planned.every((p) => ids.has(p.observation.id))).toBe(true);
      if (planned[0].observation.state === "OBSERVED") sawFault += 1;
      else sawHole += 1;
    }
    // THE SURPRISE IS REAL RATHER THAN RHETORICAL: across those worlds the top
    // concern is sometimes a measured fault and sometimes a hole in ONIQ's own
    // instrument panel. A fixture that could only ever produce one of the two
    // would make the invariants above vacuous.
    expect(sawFault).toBeGreaterThan(0);
    expect(sawHole).toBeGreaterThan(0);
  });

  it("the ranking is reproducible from the observations alone", () => {
    const rows = [fault("test_health", "a", 0.7), fault("latency", "b", 0.4)];
    expect(planOf(rows).map((p) => p.goal.id)).toEqual(planOf(rows).map((p) => p.goal.id));
  });

  it("an improvement objective is autonomous and can never be a user request", () => {
    const planned = planOf([fault("dead_branch", "mod", 0.6)]);
    const objectives = objectivesFromImprovements(
      planned.map((p) => ({ goal: p.goal, score: p.score, reason: p.target.reason })),
      7,
    );
    expect(objectives).toHaveLength(planned.length);
    expect(objectives.every((o) => o.source === "improvement")).toBe(true);
    expect(objectives.every((o) => o.createdAt === 7)).toBe(true);
  });
});

describe("v1.7 §5/§6 — every factor is read off the observation", () => {
  it("uncertainty and information gain fall as ONIQ learns more about the row", () => {
    const hole = unobserved("latency", "s", "why");
    const probe = unknown("latency", "s", "why", PROV);
    const seen = fault("latency", "s", 0.5, null as unknown as number);
    const measured = fault("latency", "s", 0.5, 120);
    expect(uncertaintyOf(hole)).toBeGreaterThan(uncertaintyOf(probe));
    expect(uncertaintyOf(probe)).toBeGreaterThan(uncertaintyOf(seen));
    expect(uncertaintyOf(seen)).toBeGreaterThan(uncertaintyOf(measured));
    expect(informationGainOf(hole)).toBeGreaterThan(informationGainOf(measured));
  });

  it("dependency counts other observations of the same subject", () => {
    const a = fault("test_health", "core", 0.5);
    const b = fault("latency", "core", 0.5);
    const c = fault("error_rate", "edge", 0.5);
    expect(dependencyOf(a, [a, b, c])).toBeGreaterThan(dependencyOf(c, [a, b, c]));
  });

  it("status maps onto the substrate's own vocabulary and reaches only two of four", () => {
    expect(statusOf(unobserved("latency", "s", "w"))).toBe("UNKNOWN");
    expect(statusOf(unknown("latency", "s", "w"))).toBe("UNCERTAIN");
    expect(statusOf(fault("latency", "s", 0.99))).toBe("UNCERTAIN");
    // Never CONTRADICTED: one reading cannot disagree with itself, and never
    // VERIFIED: a concern is by construction an open question.
    const all = [
      unobserved("latency", "s", "w"),
      unknown("latency", "s", "w"),
      fault("latency", "s", 0.99),
    ].map(statusOf);
    expect(all).not.toContain("CONTRADICTED");
    expect(all).not.toContain("VERIFIED");
  });

  it("the six factors run through the EXISTING selector, unchanged", () => {
    const rows = [fault("test_health", "a", 0.9), fault("latency", "b", 0.2)];
    // THE COMPARISON IS OVER THE COMPLETED SET, not the two raw rows, because
    // `planImprovements` plans over the world state and the world state has
    // nineteen kinds in it. Comparing against two would compare two different
    // populations and report a difference this code never made.
    const concerns = worldConcerns(worldOf(rows));
    const gaps = concerns.map((o) => concernGap(o, concerns));
    const direct = rankLearningTargets({ gaps, knowledge: EMPTY_KNOWLEDGE, focus: null });
    const planned = planOf(rows);
    // Every target the selector produced is present, with the selector's own
    // factors — the plan re-ranks by the clamped planning modifier and does not
    // re-derive a score beside the scorer.
    expect(new Set(planned.map((p) => p.target.conceptId))).toEqual(
      new Set(direct.map((t) => t.conceptId)),
    );
    const bySelector = new Map(direct.map((t) => [t.conceptId, t.factors] as const));
    for (const p of planned) {
      expect(p.target.factors).toEqual(bySelector.get(p.target.conceptId));
      expect(p.score).toBeCloseTo(p.target.score * planningModifier(p.planning), 12);
    }
    expect(planned[0].target.factors.importance).toBe(0.9);
  });

  it("the planning modifier re-ranks and can never veto", () => {
    expect(planningModifier(NEUTRAL_PLANNING)).toBe(1);
    const vetoed = planningModifier({ ...NEUTRAL_PLANNING, capability: 0 });
    // A zero would annihilate the other five. It clamps to the floor instead,
    // so an objective ONIQ cannot currently execute is DEFERRED, not deleted —
    // which is what leaves something for `reconsider` to reconsider.
    expect(vetoed).toBeCloseTo(MODIFIER_FLOOR, 12);
    expect(vetoed).toBeGreaterThan(0);
  });

  it("the goal statement reads the observation rather than a template per kind", () => {
    expect(goalFor(unobserved("missing_telemetry", "chat", "w")).statement).toContain("observe");
    expect(goalFor(unknown("latency", "chat", "w")).statement).toContain("measure");
    expect(goalFor(fault("latency", "chat", 0.8)).statement).toContain("improve");
    expect(concernId(fault("latency", "chat", 0.8))).toBe("latency:chat");
  });

  it("the world state leads with what is NOT known", () => {
    const text = describeWorld(worldOf([fault("test_health", "s", 0.9)]));
    expect(text).toMatch(/^degraded; observed 1\/19/);
    expect(worldConcerns(worldOf([fault("test_health", "s", 0)]))).toHaveLength(
      // The healthy row drops out; the eighteen unobserved kinds remain.
      OBSERVATION_KINDS.length - 1,
    );
  });
});

describe("v1.7 §7 — research is skipped only when everything is already known", () => {
  const goal = { id: "g", statement: "s", requires: [{ conceptId: "c", importance: 1 }] };

  it("no record at all is `unknown`, and research is required", () => {
    const needs = knowledgeNeeds(goal, EMPTY_KNOWLEDGE);
    expect(needs[0].verdict).toBe("unknown");
    expect(researchDecision(needs)).toBe("RESEARCH");
  });

  it("a stale record does NOT skip research", () => {
    const knowledge = {
      concepts: new Map([["c", { id: "c", label: "c", dependsOn: [], contextIds: [] }]]),
      relations: new Map(),
      evidence: new Map(),
    };
    const needs = knowledgeNeeds(goal, knowledge, new Map([["c", 1]]));
    expect(needs[0].verdict).toBe("stale");
    expect(researchDecision(needs)).toBe("RESEARCH");
  });
});

/* ================================================================ *
 * §8 — DURABILITY
 * ================================================================ */

function sampleRecord() {
  let prov = EMPTY_PROVENANCE;
  for (const step of ["source", "acquisition", "extraction", "assertion", "validation"] as const) {
    prov = withActivity(prov, {
      step,
      agent: "test",
      used: ["src"],
      generated: "c",
      at: "2026-09-11T00:00:00.000Z",
      note: step,
    });
  }
  return draftRecord({
    subject: "c",
    predicate: "is_documented_as",
    object: "a line of text",
    domain: ["oniq_capability"],
    // NON-EMPTY ON PURPOSE. With every list empty, a round trip that DROPPED a
    // list produced `[]` either way and the content hash matched — the fixture
    // could not see the hole its own test was written for, and M140 escaped.
    // A fixture whose fields are all at their default tests only the defaults.
    derivedFrom: ["parent-assertion"],
    provenance: prov,
    evidence: [
      makeEvidence({
        id: "ev1",
        sourceId: "src",
        sourceType: "measurement",
        sourceVersion: "abc123",
        locator: "src/x.ts:12",
        contentHash: "deadbeef",
        excerpt: "a line of text",
        extraction: "direct_quotation",
        directness: "fetched",
        retrievedAt: "2026-09-11T00:00:00.000Z",
        verifier: "test",
        supports: true,
      }),
    ],
  });
}

describe("v1.7 §8 — the durable round trip is lossless", () => {
  const meta = { createdAt: "2026-09-11T00:00:00.000Z", updatedAt: "2026-09-11T00:00:00.000Z" };

  it("every status survives a round trip with an IDENTICAL content hash", () => {
    for (const status of [
      "CANDIDATE",
      "VERIFIED",
      "CONTESTED",
      "SUPERSEDED",
      "REJECTED",
    ] as const) {
      const r = {
        ...sampleRecord(),
        status,
        confidence: 0.5,
        supports: ["other-assertion"],
        contradicts: ["rival-assertion"],
        supersededBy: status === "SUPERSEDED" ? "replacement" : null,
      };
      // A whole-record fingerprint, not a field list: a field-by-field check
      // has to be extended by hand the day the record grows a field.
      expect(contentHash(fromDurable(toDurable(r, meta)))).toBe(contentHash(r));
    }
  });

  it("the row carries §8's names and the source versions it actually read", () => {
    const row = toDurable(sampleRecord(), meta);
    expect(row.schema).toBe(DURABLE_SCHEMA_VERSION);
    expect(row.concept).toBe("c");
    expect(row.claim.predicate).toBe("is_documented_as");
    expect(row.source_version).toEqual(["abc123"]);
    expect(row.observed_at).toBe(sampleRecord().validity.lastVerifiedAt);
  });

  it("the fingerprint ignores the timestamps and nothing else", () => {
    const a = toDurable(sampleRecord(), meta);
    const b = toDurable(sampleRecord(), { createdAt: "2027-01-01", updatedAt: "2027-01-01" });
    expect(durableFingerprint(a)).toBe(durableFingerprint(b));
    expect(durableFingerprint({ ...a, confidence: 0.9 })).not.toBe(durableFingerprint(a));
  });

  it("a VERIFIED row with no evidence is refused at the boundary", () => {
    const row = {
      ...toDurable({ ...sampleRecord(), status: "VERIFIED" as const }, meta),
      evidence: [],
    };
    expect(validateDurable(row).map((p) => p.code)).toContain("verified_without_evidence");
  });

  it("a refused load is not an empty store", () => {
    const empty = hydrate({ ok: true, rows: [] });
    const refused = hydrate({ ok: false, reason: "unreadable" });
    expect(empty.reason).toBeNull();
    expect(refused.reason).toBe("unreadable");
    expect(empty.records).toEqual(refused.records);
  });

  it("the no-op store refuses both ways rather than resolving silently", async () => {
    expect((await NO_DURABLE_STORE.load()).ok).toBe(false);
    expect((await NO_DURABLE_STORE.save([])).ok).toBe(false);
  });

  it("an upsert keeps the higher version and takes an equal one", () => {
    const base = toDurable(sampleRecord(), meta);
    const older = { ...base, version: 1, confidence: 0.1 };
    const newer = { ...base, version: 2, confidence: 0.9 };
    expect(mergeDurable([newer], [older])[0].version).toBe(2);
    expect(mergeDurable([older], [newer])[0].version).toBe(2);
    // Equal versions take the incoming row: a re-verification must be visible.
    expect(mergeDurable([older], [{ ...older, confidence: 0.5 }])[0].confidence).toBe(0.5);
  });

  it("the sink store tells 'empty' from 'unreadable' from 'a version I cannot read'", async () => {
    const mk = (raw: string | null) =>
      makeSinkDurableStore({ read: async () => raw, write: async () => true });
    expect(await mk(null).load()).toEqual({ ok: true, rows: [] });
    const corrupt = await mk("{not json").load();
    expect(corrupt.ok).toBe(false);
    const wrongSchema = await mk(JSON.stringify({ schema: 99, rows: [] })).load();
    expect(wrongSchema.ok).toBe(false);
    expect(wrongSchema.ok === false && wrongSchema.reason).toContain("99");
  });

  it("a sink that does not confirm the write is reported as a failure, not a count", async () => {
    const store = makeSinkDurableStore({ read: async () => null, write: async () => false });
    const saved = await store.save([toDurable(sampleRecord(), meta)]);
    expect(saved.ok).toBe(false);
  });
});

/* ================================================================ *
 * §9 — RESEARCH RETRIEVES
 * ================================================================ */

describe("v1.7 §9 — retrieval, not generation", () => {
  const corpus = [
    {
      locator: "src/demo.ts",
      sourceVersion: "v9",
      contentHash: "hash9",
      text: "line one\nthe backoff window is 30 minutes\nunrelated\n",
    },
  ];

  it("a finding is VERBATIM and carries locator, version and hash", () => {
    const got = makeLocalEvidenceResearch(corpus).retrieve("backoff window");
    expect(got.ok).toBe(true);
    if (!got.ok) return;
    expect(got.findings[0].excerpt).toBe("the backoff window is 30 minutes");
    expect(got.findings[0].locator).toBe("src/demo.ts:2");
    expect(got.findings[0].sourceVersion).toBe("v9");
    expect(got.findings[0].contentHash).toBe("hash9");
    expect(got.findings[0].directness).toBe("fetched");
    expect(got.findings[0].extraction).toBe("direct_quotation");
  });

  it("nothing found over a corpus in hand is an ESTABLISHED negative, so it is ok", () => {
    const got = makeLocalEvidenceResearch(corpus).retrieve("quantum teleportation");
    expect(got.ok).toBe(true);
    if (got.ok) expect(got.findings).toEqual([]);
  });

  it("an empty corpus REFUSES, because searching nothing establishes nothing", () => {
    const got = makeLocalEvidenceResearch([]).retrieve("anything");
    expect(got.ok).toBe(false);
  });

  it("every term must appear, which is the safe direction", () => {
    const got = makeLocalEvidenceResearch(corpus).retrieve("backoff teleportation");
    expect(got.ok && got.findings).toEqual([]);
    expect(searchTerms("a-b runner_availability")).toEqual(["runner", "availability"]);
    expect(searchTerms("a b c").every((t) => t.length >= MIN_TERM_LENGTH)).toBe(true);
  });

  it("M153 — a line that is only the question's own words is not a finding", () => {
    // MEASURED ON THE FIRST FOUR-PROCESS RUN. Asked about `motion_failure`, the
    // repository answered with `"motion_failure",` — its own entry in
    // `OBSERVATION_KINDS`. Verbatim, located, hashed, true, and the question
    // read back. Promoting it would have ONIQ record that it had learned
    // something when all it had found was its own enum.
    const enumLine = [
      { locator: "kinds.ts", sourceVersion: null, contentHash: null, text: '  "motion_failure",' },
    ];
    const tautology = makeLocalEvidenceResearch(enumLine).retrieve("motion_failure");
    expect(tautology.ok && tautology.findings).toEqual([]);
    expect(substance('  "motion_failure",', ["motion", "failure"])).toBeLessThan(MIN_SUBSTANCE);

    // BOTH DIRECTIONS: a line that actually says something still comes back.
    const real = [
      {
        locator: "notes.ts",
        sourceVersion: null,
        contentHash: null,
        text: "a motion failure is a shot whose subject does not move between frames",
      },
    ];
    const answer = makeLocalEvidenceResearch(real).retrieve("motion_failure");
    expect(answer.ok && answer.findings.length).toBe(1);
    expect(substance(real[0].text, ["motion", "failure"])).toBeGreaterThanOrEqual(MIN_SUBSTANCE);
  });

  it("one question cannot mine an unbounded pile of agreement", () => {
    // THE LINE MUST CARRY SUBSTANCE OR THE NEW RULE REFUSES IT, which is how
    // this fixture caught itself: `"the backoff window"` repeated twenty times
    // is the question read back, and `MIN_SUBSTANCE` exists to refuse exactly
    // that. The fixture now says something.
    const many = [
      {
        locator: "x.ts",
        sourceVersion: null,
        contentHash: null,
        text: Array.from(
          { length: 20 },
          (_, i) => `the backoff window is ${i} minutes on this deployment path`,
        ).join("\n"),
      },
    ];
    const got = makeLocalEvidenceResearch(many).retrieve("backoff window");
    expect(got.ok && got.findings.length).toBe(MAX_LOCAL_FINDINGS);
  });
});

/* ================================================================ *
 * §11 + §13 — EXPERIMENTS AND MEASURED IMPROVEMENT
 * ================================================================ */

describe("v1.7 §11/§13 — inconclusive evidence never becomes success", () => {
  const plan = design({
    objectiveId: "o",
    kind: "improvement",
    hypothesis: "h",
    baselineArm: "before",
    candidateArm: "after",
    variables: ["v"],
    controls: ["c"],
    metric: "open_gaps",
    direction: "lower_is_better",
    criterion: { minDelta: 1, minSamples: 1 },
    seed: 0,
    configuration: {},
  });
  const m = (value: number | null, samples = 1) =>
    measurement("open_gaps", value, { unit: "concepts", samples, direction: "lower_is_better" });

  it("an unmeasured side is INCONCLUSIVE and says IMPROVEMENT_UNVERIFIED", () => {
    const r = compare(plan, unmeasured("open_gaps", "lower_is_better", "no reading"), m(1), "t");
    expect(r.verdict).toBe("INCONCLUSIVE");
    expect(r.rationale).toContain(IMPROVEMENT_UNVERIFIED);
    expect(r.improvementVerified).toBe(false);
  });

  it("thin samples are INCONCLUSIVE however large the delta", () => {
    const strict = design({ ...plan, criterion: { minDelta: 1, minSamples: 5 } });
    expect(compare(strict, m(10), m(0), "t").verdict).toBe("INCONCLUSIVE");
  });

  it("a delta below the threshold is NO_DIFFERENCE, not a small win", () => {
    const tie = compare(plan, m(3), m(3), "t");
    expect(tie.verdict).toBe("NO_DIFFERENCE");
    // ON THE FINAL RETURN'S OWN PATH. The INCONCLUSIVE assertions above hit an
    // EARLY return whose `improvementVerified` is written `false` inline, so a
    // mutation that sets the flag at the end of `compare` escaped every one of
    // them. A tie and a regression are the two outcomes that reach the same
    // line an improvement does.
    expect(tie.improvementVerified).toBe(false);
    expect(compare(plan, m(1), m(4), "t").improvementVerified).toBe(false);
    // And a method comparison may never set it at all: it says which arm won,
    // not that ONIQ got better.
    const versus = design({ ...plan, kind: "method_comparison" });
    expect(compare(versus, m(3), m(1), "t").verdict).toBe("QUANTUM_INSPIRED_BETTER");
    expect(compare(versus, m(3), m(1), "t").improvementVerified).toBe(false);
  });

  it("a real improvement in the metric's own direction is IMPROVED and verified", () => {
    const r = compare(plan, m(3), m(1), "t");
    expect(r.verdict).toBe("IMPROVED");
    expect(r.delta).toBe(-2);
    expect(r.improvementVerified).toBe(true);
    expect(verifiedImprovements([r])).toHaveLength(1);
  });

  it("a regression is named as one", () => {
    expect(compare(plan, m(1), m(4), "t").verdict).toBe("REGRESSED");
  });

  it("BLOCKED is reachable only from a refusal, never from a comparison", () => {
    expect(experimentBlocked(plan, "capability refused", "t").verdict).toBe("BLOCKED");
    const verdicts = [
      compare(plan, m(1), m(1), "t"),
      compare(plan, m(3), m(1), "t"),
      compare(plan, m(1), m(3), "t"),
      compare(plan, null, m(1), "t"),
    ].map((r) => r.verdict);
    expect(verdicts).not.toContain("BLOCKED");
  });

  it("§15 — a failure becomes knowledge WITH its scope, never a generalisation", () => {
    const regressed = failureLesson(compare(plan, m(1), m(4), "t"));
    expect(regressed).not.toBeNull();
    // THE SCOPE IS THE POINT. "after is worse" is a claim about every future
    // run; this one names the arms, the metric, the seed and the controls it
    // was measured under, so a later reader can tell what it does NOT cover.
    expect(regressed?.scope).toMatchObject({ metric: "open_gaps", seed: 0, controls: ["c"] });
    expect(regressed?.statement).toContain("REGRESSED");
    // And a win teaches no failure lesson at all, rather than an empty one.
    expect(failureLesson(compare(plan, m(3), m(1), "t"))).toBeNull();
  });
});

/* ================================================================ *
 * §12 — REGISTERED AND AUTHORIZED, SEPARATELY
 * ================================================================ */

describe("v1.7 §12 — the capability boundary", () => {
  // THE TITLE SAYS "PERMISSION", NOT THE OTHER WORD, AND THAT IS DELIBERATE.
  // `security.test.ts` bans the lowercase wire spelling of the HTTP header, and
  // a test title carrying it trips the same guard — v1.6 hit this twice and
  // reworded both times rather than cutting an exemption into a security guard
  // for a sentence's sake. The narrowing is not mine to make from a title.
  it("registration and permission fail differently and both are checked", async () => {
    const reached: string[] = [];
    const exec = async (req: { id: string }) => {
      reached.push(req.id);
      return { ok: true as const, value: 1, unit: "x", detail: "ran" };
    };
    const unregistered = await executeCapability(
      { id: "DELETE_EVERYTHING" as never, args: {} },
      exec,
    );
    expect(unregistered.ok).toBe(false);
    expect(unregistered.ok === false && unregistered.reason).toContain("not a registered");

    const unauthorized = await executeCapability({ id: "RUN_BENCHMARK", args: {} }, exec);
    expect(unauthorized.ok).toBe(false);
    expect(unauthorized.ok === false && unauthorized.reason).toContain("NOT authorized");

    const allowed = await executeCapability({ id: "RUN_TEST_SUITE", args: {} }, exec);
    expect(allowed.ok).toBe(true);
    // Neither refusal reached the executor: the gate is ABOVE the thing it guards.
    expect(reached).toEqual(["RUN_TEST_SUITE"]);
  });

  it("nothing that writes outside ONIQ's own knowledge is authorized in this build", () => {
    for (const c of CAPABILITY_REGISTRY) {
      if (c.touchesProduction) expect(c.authorized).toBe(false);
    }
    const on = CAPABILITY_REGISTRY.filter((c) => c.authorized).map((c) => c.id);
    expect(on).toEqual(["RUN_TEST_SUITE", "RUN_STATIC_ANALYSIS", "UPDATE_KNOWLEDGE"]);
  });

  it("arguments are bounded in count and length", async () => {
    const exec = async () => ({ ok: true as const, value: null, unit: "", detail: "" });
    const many = Object.fromEntries(Array.from({ length: MAX_ARGS + 1 }, (_, i) => [`k${i}`, "v"]));
    expect((await executeCapability({ id: "RUN_TEST_SUITE", args: many }, exec)).ok).toBe(false);
    const long = { k: "x".repeat(MAX_ARG_LENGTH + 1) };
    expect((await executeCapability({ id: "RUN_TEST_SUITE", args: long }, exec)).ok).toBe(false);
  });

  it("the default executor runs nothing and says so", async () => {
    const got = await executeCapability({ id: "RUN_TEST_SUITE", args: {} }, NO_EXECUTOR);
    expect(got.ok).toBe(false);
  });

  it("a registered id resolves to one of the four ledger resources", () => {
    expect(isRegistered("UPDATE_KNOWLEDGE")).toBe(true);
    expect(isRegistered("rm")).toBe(false);
    expect(registeredCapability("UPDATE_KNOWLEDGE")?.resource).toBe("verification");
    expect(resourcesFor(["RUN_TEST_SUITE", "REQUEST_RESEARCH", "nonsense"])).toEqual([
      "research",
      "verification",
    ]);
  });
});

/* ================================================================ *
 * §19 + §20
 * ================================================================ */

describe("v1.7 §19/§20 — self-evaluation answers from evidence, or not at all", () => {
  const world = worldOf([fault("test_health", "s", 0.9)]);
  const base = {
    objectiveId: "o",
    goalId: "g",
    settled: [],
    learned: [],
    persisted: [],
    experiment: null,
    blockedOn: [],
    blockedCapabilities: [],
    world,
    nextConcern: null,
  } as const;

  it("a cycle that measured nothing answers `unestablished`, never `no`", () => {
    const e = selfEvaluate({ ...base, status: "blocked" });
    const perf = e.questions.find((q) => q.question.includes("performance"));
    expect(perf?.answer).toBe("unestablished");
    // `no` would be a claim that ONIQ checked and did not improve.
    expect(perf?.evidence).toEqual([]);
  });

  it("BLOCKED experiment without regression evidence stays unestablished", () => {
    const d = design({
      objectiveId: "o",
      kind: "improvement",
      hypothesis: "candidate improves the metric",
      baselineArm: "baseline",
      candidateArm: "candidate",
      variables: ["candidate"],
      controls: ["same fixture"],
      metric: "score",
      direction: "higher_is_better",
      criterion: { minDelta: 0.01, minSamples: 2 },
      seed: 1,
      configuration: {},
    });
    const e = selfEvaluate({
      ...base,
      status: "blocked",
      experiment: experimentBlocked(d, "runner unavailable", "t"),
    });
    expect(e.questions.find((q) => q.question.includes("introduce a regression"))?.answer).toBe(
      "unestablished",
    );
  });

  it("confirming what was already held is settled and is NOT learning", () => {
    const e = selfEvaluate({ ...base, status: "success", settled: ["a", "b"] });
    expect(e.questions.find((q) => q.question.includes("learn"))?.answer).toBe("no");
    const withLearning = selfEvaluate({ ...base, status: "success", learned: ["a"] });
    expect(withLearning.questions.find((q) => q.question.includes("learn"))?.answer).toBe("yes");
  });

  it("a durable write is what makes 'did my knowledge change' a yes", () => {
    expect(
      selfEvaluate({ ...base, status: "success", persisted: ["k1"] }).questions.find((q) =>
        q.question.includes("knowledge change"),
      )?.answer,
    ).toBe("yes");
  });

  it("what remains unknown comes from the world, not from a guess", () => {
    const e = selfEvaluate({ ...base, status: "blocked", blockedOn: ["runner-availability"] });
    expect(e.remainsUnknown).toContain("runner-availability");
    expect(e.remainsUnknown.length).toBeGreaterThan(1);
  });

  it("the curriculum layers by dependency and breaks ties WITHIN a layer only", () => {
    const knowledge = {
      concepts: new Map([
        ["basic", { id: "basic", label: "basic", dependsOn: [], contextIds: [] }],
        ["advanced", { id: "advanced", label: "advanced", dependsOn: ["basic"], contextIds: [] }],
        ["other", { id: "other", label: "other", dependsOn: [], contextIds: [] }],
      ]),
      relations: new Map(),
      evidence: new Map(),
    };
    // `advanced` has the highest gain and must still come after its prerequisite.
    const steps = curriculum(knowledge, (id) => (id === "advanced" ? 1 : 0.1));
    expect(steps.map((s) => s.conceptId).indexOf("advanced")).toBeGreaterThan(
      steps.map((s) => s.conceptId).indexOf("basic"),
    );
    expect(steps[0].depth).toBe(0);
  });

  it("a dependency cycle is reported, not thrown", () => {
    const knowledge = {
      concepts: new Map([
        ["a", { id: "a", label: "a", dependsOn: ["b"], contextIds: [] }],
        ["b", { id: "b", label: "b", dependsOn: ["a"], contextIds: [] }],
      ]),
      relations: new Map(),
      evidence: new Map(),
    };
    expect(() => curriculum(knowledge, () => 1)).not.toThrow();
    expect(curriculumCycles(knowledge)).toEqual(["a", "b"]);
  });
});
