// P4 — provenance READER (never a pixel-based "AI detector").
// Scans a just-uploaded object for machine-readable provenance:
//   1. C2PA / Content Credentials markers (JUMBF boxes, manifest strings) —
//      digitalSourceType trainedAlgorithmicMedia => AI,
//      compositeWithTrainedAlgorithmicMedia => AI-edited.
//      NOTE: full COSE signature + cert-chain validation needs a C2PA
//      library (zero-new-deps constraint), so C2PA hits are reported as
//      "likely", never "confirmed". Confirmed is reserved for media
//      generated by ONIQ's own tools (server-known origin).
//   2. Weaker fallbacks: XMP/IPTC digitalSourceType, EXIF Software /
//      CreatorTool naming a known generator => "possible".
// Every scan result is appended to the media_provenance ledger.
// Absence of a manifest is NOT evidence — most re-encodes strip metadata.
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

const SCAN_BYTES = 2 * 1024 * 1024; // manifests/metadata live near the start
const ALLOWED_BUCKETS = new Set(["moments", "clips", "chat-media"]);

const GENERATORS = [
  "midjourney", "dall-e", "dall·e", "dalle", "stable diffusion", "sdxl",
  "adobe firefly", "firefly", "gpt-image", "gpt-4o", "imagen", "ideogram",
  "leonardo.ai", "runway", "flux.1", "flux-1", "grok image", "meta ai",
  "gemini", "recraft", "nano banana",
];

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  const json = (body: unknown, status = 200) =>
    new Response(JSON.stringify(body), {
      status,
      headers: { ...corsHeaders, "content-type": "application/json" },
    });
  if (req.method !== "POST") return json({ error: "method not allowed" }, 405);

  const token = (req.headers.get("Authorization") ?? "").replace(/^Bearer\s+/i, "").trim();
  if (!token) return json({ error: "unauthorized" }, 401);

  const admin = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
    { auth: { persistSession: false } },
  );
  const { data: userRes, error: userErr } = await admin.auth.getUser(token);
  if (userErr || !userRes?.user) return json({ error: "unauthorized" }, 401);
  const uid = userRes.user.id;

  let body: { bucket?: string; path?: string; content_type?: string; content_id?: string } = {};
  try { body = await req.json(); } catch { /* ignore */ }
  const bucket = String(body.bucket ?? "");
  const path = String(body.path ?? "").replace(/^\/+/, "");
  const contentType = ["moment", "clip", "avatar", "chat", "other"].includes(String(body.content_type))
    ? String(body.content_type)
    : "other";
  if (!ALLOWED_BUCKETS.has(bucket) || !path || path.includes("..")) {
    return json({ error: "bad target" }, 400);
  }
  // Only the uploader may scan their own object (folder = uid).
  if (!path.startsWith(`${uid}/`)) return json({ error: "forbidden" }, 403);

  // Pull the head of the object.
  let bytes: Uint8Array;
  try {
    const { data: signed, error: sErr } = await admin.storage.from(bucket).createSignedUrl(path, 120);
    if (sErr || !signed) return json({ error: "object not found" }, 404);
    const res = await fetch(signed.signedUrl, { headers: { Range: `bytes=0-${SCAN_BYTES - 1}` } });
    if (!res.ok && res.status !== 206) return json({ error: "fetch failed" }, 502);
    bytes = new Uint8Array(await res.arrayBuffer());
  } catch {
    return json({ error: "fetch failed" }, 502);
  }

  // Marker scan over a latin1 projection (binary-safe for ASCII markers).
  let text = "";
  for (let i = 0; i < bytes.length; i++) text += String.fromCharCode(bytes[i]);
  const lower = text.toLowerCase();

  const evidence: string[] = [];
  const hasC2pa = lower.includes("c2pa") || lower.includes("jumbf") || lower.includes("contentauth");
  if (hasC2pa) evidence.push("c2pa_manifest_marker");
  const composite = lower.includes("compositewithtrainedalgorithmicmedia");
  const tam = lower.includes("trainedalgorithmicmedia");
  if (composite) evidence.push("digitalSourceType=compositeWithTrainedAlgorithmicMedia");
  else if (tam) evidence.push("digitalSourceType=trainedAlgorithmicMedia");
  const gens = GENERATORS.filter((g) => lower.includes(g));
  for (const g of gens) evidence.push(`generator_marker:${g}`);

  let verdict: "none" | "possible" | "likely" = "none";
  let kind: "ai" | "ai_edited" | null = null;
  if (tam || composite) {
    verdict = "likely"; // C2PA-shaped claim present; signature NOT validated
    kind = composite ? "ai_edited" : "ai";
  } else if (gens.length > 0) {
    verdict = "possible";
    kind = "ai";
  }

  // Append the scan to the provenance ledger (service role; append-only).
  try {
    const digest = await crypto.subtle.digest("SHA-256", bytes.slice().buffer as ArrayBuffer);
    const sha = Array.from(new Uint8Array(digest)).map((b) => b.toString(16).padStart(2, "0")).join("");
    await admin.from("media_provenance").insert({
      uploader_id: uid,
      content_type: contentType,
      content_id: body.content_id ?? null,
      sha256: sha,
      origin: "provenance_scan",
      declared_synthetic: verdict !== "none",
      confidence: verdict,
      evidence: {
        signals: evidence,
        scanned_bytes: bytes.length,
        partial: bytes.length >= SCAN_BYTES,
        bucket,
        note: "C2PA signature not cryptographically validated (no library); hash covers scanned range only when partial",
      },
    });
  } catch (e) {
    console.warn("provenance-scan: ledger insert failed", (e as Error).message);
  }

  return json({ verdict, kind, evidence });
});
