/**
 * The 50 promo shots — data, not code, so adding shot 51 is a row.
 *
 * Aspects map to where they upload:
 *   v  1080x1920  Reels / Shorts / TikTok / WhatsApp status
 *   s  1080x1080  Instagram feed / WhatsApp forwards
 *   l  1920x1080  YouTube / X / website embeds
 *
 * Copy discipline: every line describes something the app actually does
 * today. Nothing here promises what is not shipped — the wallet's demo
 * credits, for instance, are deliberately absent.
 */
export type Aspect = 'v' | 's' | 'l';

export type Shot = {
  id: string;
  aspect: Aspect;
  /** Duration in frames at 30fps. */
  dur: number;
  template: 'wordmark' | 'feature' | 'stat' | 'chat' | 'call' | 'worlds' | 'cta';
  eyebrow?: string;
  /** Headline lines, stacked. */
  head?: string[];
  sub?: string;
  /** Big glyph for feature shots — emoji renders everywhere, ships nothing. */
  glyph?: string;
  /** Stat template. */
  stat?: string;
  statLabel?: string;
  /** Chat template: bubbles appear in order; `mine` renders right/teal. */
  bubbles?: Array<{ text: string; mine?: boolean }>;
  /** Accent override; teal otherwise. */
  accent?: string;
};

export const DIMS: Record<Aspect, { width: number; height: number }> = {
  v: { width: 1080, height: 1920 },
  s: { width: 1080, height: 1080 },
  l: { width: 1920, height: 1080 },
};

const TAG = 'One app. Every world.';

export const SHOTS: Shot[] = [
  // ---------- vertical: Reels / Shorts / TikTok / status (30) ----------
  { id: 'v01-hook', aspect: 'v', dur: 210, template: 'wordmark', sub: TAG },
  {
    id: 'v02-chat',
    aspect: 'v',
    dur: 180,
    template: 'chat',
    eyebrow: 'Chat',
    head: ['Chat that', 'feels alive'],
    bubbles: [
      { text: 'yo where are you rn' },
      { text: 'omw 🛵', mine: true },
      { text: 'bring snacks pls' },
      { text: 'already did 😌', mine: true },
    ],
  },
  {
    id: 'v03-calls',
    aspect: 'v',
    dur: 180,
    template: 'call',
    eyebrow: 'Calls',
    head: ['Video calls', 'that just work'],
    sub: 'Voice and video, straight from any chat',
  },
  {
    id: 'v04-groupcall',
    aspect: 'v',
    dur: 180,
    template: 'call',
    eyebrow: 'Group calls',
    head: ['The whole crew,', 'one screen'],
    sub: 'Add people mid-call. No links, no apps.',
  },
  {
    id: 'v05-lenses',
    aspect: 'v',
    dur: 170,
    template: 'feature',
    glyph: '🤪',
    eyebrow: 'Face lenses',
    head: ['Big eyes.', 'Big head.', 'Big mood.'],
    sub: 'Face-tracked lenses, live in your calls',
  },
  {
    id: 'v06-filters',
    aspect: 'v',
    dur: 170,
    template: 'feature',
    glyph: '👽',
    eyebrow: 'Call filters',
    head: ['Alien. Thermal.', 'Noir. Neon.'],
    sub: 'Switch your look mid-call',
    accent: '#8B5CF6',
  },
  {
    id: 'v07-stickers',
    aspect: 'v',
    dur: 170,
    template: 'chat',
    eyebrow: 'Stickers',
    head: ['Say it', 'without saying it'],
    bubbles: [{ text: '💀' }, { text: '🦄', mine: true }, { text: '🫡' }],
  },
  {
    id: 'v08-doodles',
    aspect: 'v',
    dur: 170,
    template: 'feature',
    glyph: '🎨',
    eyebrow: 'Doodles',
    head: ['33 hand-drawn', 'doodles'],
    sub: 'A picture you send instead of a sentence',
    accent: '#F7B955',
  },
  {
    id: 'v09-voice',
    aspect: 'v',
    dur: 170,
    template: 'feature',
    glyph: '🎙️',
    eyebrow: 'Voice notes',
    head: ['Hold. Speak.', 'Send.'],
    sub: 'Up to two minutes of you',
  },
  {
    id: 'v10-videonotes',
    aspect: 'v',
    dur: 170,
    template: 'feature',
    glyph: '📹',
    eyebrow: 'Video notes',
    head: ['Round little', 'video moments'],
    sub: 'A minute of face, WhatsApp-style',
  },
  {
    id: 'v11-translate',
    aspect: 'v',
    dur: 180,
    template: 'chat',
    eyebrow: 'Translate',
    head: ['Every language,', 'one tap'],
    bubbles: [
      { text: '¿Nos vemos mañana?' },
      { text: 'See you tomorrow? · translated', mine: false },
      { text: 'yes!! 🎉', mine: true },
    ],
  },
  {
    id: 'v12-scout',
    aspect: 'v',
    dur: 170,
    template: 'stat',
    stat: '56',
    statLabel: 'languages in Scout',
    sub: 'Learn a language inside the app you already open',
  },
  {
    id: 'v13-ting',
    aspect: 'v',
    dur: 180,
    template: 'chat',
    eyebrow: 'Ting AI',
    head: ['An AI that knows', "what's happening"],
    bubbles: [
      { text: 'Ting, cheapest ride to Park Street rn?', mine: true },
      { text: 'Comparing your options now 🛵' },
    ],
  },
  {
    id: 'v14-study',
    aspect: 'v',
    dur: 180,
    template: 'feature',
    glyph: '📚',
    eyebrow: 'Study',
    head: ['Board papers,', 'ready to print'],
    sub: 'Your board. Your class. Papers ready.',
  },
  {
    id: 'v15-quiz',
    aspect: 'v',
    dur: 170,
    template: 'feature',
    glyph: '✅',
    eyebrow: 'Study',
    head: ['Quiz yourself', 'before the exam does'],
    sub: 'Practice built from your syllabus',
  },
  {
    id: 'v16-rides',
    aspect: 'v',
    dur: 170,
    template: 'feature',
    glyph: '🛺',
    eyebrow: 'Rides',
    head: ['Compare rides', 'before you book'],
    sub: 'Uber, Ola, Rapido — one search',
    accent: '#F7B955',
  },
  {
    id: 'v17-upi',
    aspect: 'v',
    dur: 170,
    template: 'feature',
    glyph: '💸',
    eyebrow: 'Payments',
    head: ['Any UPI app,', 'one tap away'],
    sub: 'GPay, PhonePe, Paytm — straight from ONIQ',
  },
  {
    id: 'v18-moments',
    aspect: 'v',
    dur: 170,
    template: 'feature',
    glyph: '✨',
    eyebrow: 'Moments',
    head: ['Your feed.', 'Your people.'],
    sub: 'Post it, react to it, talk about it',
  },
  {
    id: 'v19-channels',
    aspect: 'v',
    dur: 170,
    template: 'feature',
    glyph: '📢',
    eyebrow: 'Channels',
    head: ['Broadcast to', 'everyone at once'],
    sub: 'Channels with @mentions and subscribers',
  },
  {
    id: 'v20-watch',
    aspect: 'v',
    dur: 170,
    template: 'feature',
    glyph: '📺',
    eyebrow: 'Watch',
    head: ['Every stream,', 'one directory'],
    sub: 'Find where it plays, jump straight there',
    accent: '#8B5CF6',
  },
  {
    id: 'v21-originals',
    aspect: 'v',
    dur: 180,
    template: 'feature',
    glyph: '🎬',
    eyebrow: 'ONIQ Originals',
    head: ['Films made', 'inside the app'],
    sub: 'AI-crafted retellings, episodes in the Lores hub',
    accent: '#FF8A3D',
  },
  {
    id: 'v22-story',
    aspect: 'v',
    dur: 180,
    template: 'feature',
    glyph: '🪄',
    eyebrow: 'Story Studio',
    head: ['Your story,', 'turned into a film'],
    sub: 'Narration, motion, music — from your words',
    accent: '#FF8A3D',
  },
  {
    id: 'v23-creator',
    aspect: 'v',
    dur: 180,
    template: 'feature',
    glyph: '💰',
    eyebrow: 'Creator Program',
    head: ['Views become', 'payouts'],
    sub: 'The 70/20/10 split, paid to creators',
  },
  {
    id: 'v24-earn',
    aspect: 'v',
    dur: 170,
    template: 'stat',
    stat: '1M',
    statLabel: 'views unlocks the Creator Program',
    sub: 'Grow on ONIQ, earn on ONIQ',
  },
  {
    id: 'v25-light',
    aspect: 'v',
    dur: 170,
    template: 'feature',
    glyph: '🌗',
    eyebrow: 'Themes',
    head: ['Light or dark.', 'Your call.'],
    sub: 'Flip it once, it remembers',
  },
  { id: 'v26-worlds', aspect: 'v', dur: 200, template: 'worlds', eyebrow: '16 worlds' },
  {
    id: 'v27-countries',
    aspect: 'v',
    dur: 170,
    template: 'stat',
    stat: '7',
    statLabel: 'countries supported',
    sub: 'Rides, weather and more, wherever you are',
  },
  {
    id: 'v28-onelogin',
    aspect: 'v',
    dur: 170,
    template: 'stat',
    stat: '16',
    statLabel: 'worlds. one login.',
    sub: 'Stop juggling apps',
  },
  {
    id: 'v29-doodlepaper',
    aspect: 'v',
    dur: 170,
    template: 'feature',
    glyph: '📝',
    eyebrow: 'Chat wallpaper',
    head: ['Chats on', 'doodle paper'],
    sub: 'Open Doodles under every conversation',
    accent: '#F7B955',
  },
  { id: 'v30-cta', aspect: 'v', dur: 210, template: 'cta', sub: 'oniqhub.com' },

  // ---------- square: Instagram feed / forwards (10) ----------
  { id: 's01-hook', aspect: 's', dur: 200, template: 'wordmark', sub: TAG },
  {
    id: 's02-chat',
    aspect: 's',
    dur: 180,
    template: 'chat',
    eyebrow: 'Chat',
    head: ['Chat that feels alive'],
    bubbles: [
      { text: 'movie tonight?' },
      { text: 'obviously 🍿', mine: true },
    ],
  },
  {
    id: 's03-calls',
    aspect: 's',
    dur: 170,
    template: 'call',
    eyebrow: 'Calls',
    head: ['Voice & video, built in'],
    sub: 'From any chat, with anyone',
  },
  {
    id: 's04-ting',
    aspect: 's',
    dur: 170,
    template: 'feature',
    glyph: '🤖',
    eyebrow: 'Ting AI',
    head: ['Ask Ting anything'],
    sub: "An AI that actually knows what's happening now",
  },
  {
    id: 's05-study',
    aspect: 's',
    dur: 170,
    template: 'feature',
    glyph: '📚',
    eyebrow: 'Study',
    head: ['Papers ready 📄'],
    sub: 'Your board · your class · print it',
  },
  {
    id: 's06-scout',
    aspect: 's',
    dur: 170,
    template: 'stat',
    stat: '56',
    statLabel: 'languages in Scout',
    sub: 'Learn where you already scroll',
  },
  { id: 's07-worlds', aspect: 's', dur: 200, template: 'worlds', eyebrow: '16 worlds' },
  {
    id: 's08-originals',
    aspect: 's',
    dur: 180,
    template: 'feature',
    glyph: '🎬',
    eyebrow: 'ONIQ Originals',
    head: ['Films made in-app'],
    sub: 'AI-crafted episodes in the Lores hub',
    accent: '#FF8A3D',
  },
  {
    id: 's09-creator',
    aspect: 's',
    dur: 180,
    template: 'feature',
    glyph: '💰',
    eyebrow: 'Creator Program',
    head: ['Views become payouts'],
    sub: '70/20/10, paid to creators',
  },
  { id: 's10-cta', aspect: 's', dur: 200, template: 'cta', sub: 'oniqhub.com' },

  // ---------- landscape: YouTube / X / embeds (10) ----------
  { id: 'l01-hook', aspect: 'l', dur: 210, template: 'wordmark', sub: TAG },
  {
    id: 'l02-chat',
    aspect: 'l',
    dur: 180,
    template: 'chat',
    eyebrow: 'Chat',
    head: ['Chat that feels alive'],
    bubbles: [
      { text: 'did you see the new episode' },
      { text: 'watching it RIGHT now 🎬', mine: true },
      { text: 'no spoilers.' },
    ],
  },
  {
    id: 'l03-calls',
    aspect: 'l',
    dur: 180,
    template: 'call',
    eyebrow: 'Calls',
    head: ['Calls that just work'],
    sub: 'Voice, video, groups, lenses — built in',
  },
  {
    id: 'l04-study',
    aspect: 'l',
    dur: 170,
    template: 'feature',
    glyph: '📚',
    eyebrow: 'Study',
    head: ['Board papers, ready to print'],
    sub: 'Your board. Your class. Papers ready.',
  },
  {
    id: 'l05-ting',
    aspect: 'l',
    dur: 170,
    template: 'feature',
    glyph: '🤖',
    eyebrow: 'Ting AI',
    head: ["An AI that knows what's happening"],
    sub: 'Ask about rides, prices, plans — get answers',
  },
  {
    id: 'l06-rides',
    aspect: 'l',
    dur: 170,
    template: 'feature',
    glyph: '🛺',
    eyebrow: 'Rides',
    head: ['Compare rides before you book'],
    sub: 'Uber, Ola, Rapido — one search',
    accent: '#F7B955',
  },
  {
    id: 'l07-originals',
    aspect: 'l',
    dur: 180,
    template: 'feature',
    glyph: '🎬',
    eyebrow: 'ONIQ Originals',
    head: ['Films made inside the app'],
    sub: 'AI-crafted retellings — episodes in the Lores hub',
    accent: '#FF8A3D',
  },
  {
    id: 'l08-story',
    aspect: 'l',
    dur: 180,
    template: 'feature',
    glyph: '🪄',
    eyebrow: 'Story Studio',
    head: ['Your story, turned into a film'],
    sub: 'Narration, motion, music — from your words',
    accent: '#FF8A3D',
  },
  { id: 'l09-worlds', aspect: 'l', dur: 200, template: 'worlds', eyebrow: '16 worlds' },
  { id: 'l10-cta', aspect: 'l', dur: 210, template: 'cta', sub: 'oniqhub.com' },
];

/** The worlds ticker's roster — the app's own vocabulary. */
export const WORLDS = [
  'Chat',
  'Calls',
  'Study',
  'Ting AI',
  'Rides',
  'Pay',
  'Moments',
  'Watch',
  'Scout',
  'Originals',
  'Stories',
  'Channels',
  'Food',
  'Weather',
  'Earn',
  'Mini apps',
];
