// Google Play policy positions, kept in code so they can be tested rather
// than remembered.
//
// Play is the nearest-term risk in this whole loop — faster and blunter than
// any regulator, and a removal is not appealable on a useful timescale. The
// three policies that actually bite an app shaped like ONIQ are Minimum
// Functionality, AI-Generated Content, and Data safety.

/**
 * MINIMUM FUNCTIONALITY.
 *
 * A directory of links is exactly the shape Play removes as webview spam.
 * ONIQ's defence is that the link-outs sit inside an app that does substantial
 * native work of its own — these are the things that are not links.
 */
export const NATIVE_CAPABILITIES = [
  "Two-axis country model: home country drives identity, currency and legal regime; current region drives emergency numbers, crisis lines and territorial availability.",
  // DO NOT restore the old wording here: "On-device health data — health
  // readings never leave the device." That was false, and falsest in the place
  // it mattered most. app.vitals.tsx writes mood, sleep and cycle logs to the
  // health_profiles, health_checkins and cycle_logs tables, and there is real
  // data in them in production. Health data IS collected and MUST be declared
  // as such in Play Data safety. The safety plan is the only genuinely
  // device-only health surface (localStorage, oniq.safetyplan.v1).
  "Health tracking with a two-axis UAE block enforced in the database — health_data_allowed() combines the home-country check with a cf-ipcountry region check read off the request itself, so a client that lies about its region still cannot persist a reading.",
  "Row-level security on every health table: a user can read and write only their own rows, enforced in Postgres rather than in the UI.",
  "A safety plan that is genuinely device-only — held in localStorage and wiped whenever health data becomes barred.",
  "Hash-chained, append-only consent and audit ledgers with cryptographic verification.",
  "DPDP age gate: is_adult_18 enforced in RESTRICTIVE row-level security, not just in the UI.",
  "Data-subject-request handling with a 30-day SLA, soft delete and a 30-day grace hard purge.",
  "CV builder with anti-fabrication validation against the user's own declared facts.",
  "Country-aware exam-paper generation with vector PDF export.",
  "Real-time chat with WebRTC voice and video.",
  // The Watch library (owner mission, 2026-09-03): the part of Watch that is
  // ONIQ's own work rather than anybody's player — a personal library of
  // references across providers with progress, an inbox, explainable
  // resurfacing, a time-budgeted queue, collections, threads, moments,
  // notes, rights metadata and search, all row-level-secured per user.
  "Watch library: cross-provider saved references with resume positions, an inbox, an explainable resurface engine, a time-budgeted smart queue, collections, threads, saved moments, notes, Internet Archive rights metadata and library search — ONIQ's own organisation layer, not a player.",
  // UPI IS NOT DECLARED — owner directive, 2026-09-06 (evening): "hide upi".
  // The line that stood here moves out with the entry points, in the same
  // commit, which is the discipline the previous version of this comment named
  // and is now being followed in the other direction: a declared capability a
  // reviewer cannot navigate to draws questions, and a reachable capability
  // that is NOT declared is the same mismatch pointing the other way. With
  // `oniq-upi` carrying `hidden: true` and no Home tile or site card, there is
  // nothing to navigate to, so there is nothing to declare.
  //
  // It will come back if the surfaces do. `/app/upi` still resolves, so this
  // is one line and not a rebuild.
  //
  // THE DATA SAFETY ANSWER IS UNCHANGED AND WAS NEVER COUPLED TO THIS:
  // "Financial info" stays undeclared because ONIQ collects nothing financial
  // — that was true while UPI was declared and is true now.
  // Card and netbanking checkout for FOOD ORDERS, via Razorpay. Physical goods
  // and services only — Play permits a third-party processor for those and
  // requires Play Billing for digital content, so this is deliberately wired
  // to `orders` and to nothing digital. Payment status is written only by an
  // edge function that has verified an HMAC; no client path can set it.
  "Card and netbanking payment for food orders through Razorpay.",
  "Job-scam alerts with region-correct reporting channels.",
] as const;

/**
 * AI-GENERATED CONTENT.
 *
 * Play requires generative output to be labelled AND reportable from inside
 * the app. An email address on a policy page does not satisfy it. Every
 * surface here renders AI_OUTPUT_LABEL and an <AiOutputReport />.
 */
export const AI_SURFACES = [
  {
    // Create — My Creations, the one place that gathers a person's generated
    // films and songs. Everything on it is generated by definition.
    id: "creations_ai_output",
    screen: "Create — My Creations",
    file: "src/routes/_authenticated/app.creations.tsx",
  },
  {
    // Create — Music. Declared BEFORE the screen shipped, which is the ordering
    // Lores got wrong: a hub of generated video went out with no label because
    // the guard had nothing to grep for until someone remembered to add it.
    id: "music_ai_output",
    screen: "Create — Music",
    file: "src/routes/_authenticated/app.music.tsx",
  },
  {
    // Create — Image. Same ordering as Music: declared with the screen, not
    // after it.
    id: "image_ai_output",
    screen: "Create — Image",
    file: "src/routes/_authenticated/app.image.tsx",
  },
  {
    // Create — Voice. A synthetic voice is generated content even when every
    // word is the person's own — the label is about who SPOKE, not who wrote.
    id: "voice_ai_output",
    screen: "Create — Voice",
    file: "src/routes/_authenticated/app.voice.tsx",
  },
  {
    // THE RESULT SCREENS. One route serves all three, so all three ids are
    // declared against the same file — the mirror of the GPU tool below,
    // where one id is declared against three files.
    //
    // A RESULT SCREEN IS ITS OWN SURFACE, not a continuation of the screen
    // that made the thing. It survives a reload and a shared link, so it can
    // be the FIRST place a person meets a generated picture or song, with no
    // memory of a prompt having been typed. That is precisely the screen
    // somebody could pass off as filmed or recorded, which is what the label
    // is for.
    id: "image_ai_output",
    screen: "Create — Your Image (result)",
    file: "src/routes/_authenticated/app.made.$kind.$id.tsx",
  },
  {
    id: "music_ai_output",
    screen: "Create — Your Music (result)",
    file: "src/routes/_authenticated/app.made.$kind.$id.tsx",
  },
  {
    id: "voice_ai_output",
    screen: "Create — Your Voice (result)",
    file: "src/routes/_authenticated/app.made.$kind.$id.tsx",
  },
  {
    id: "cv_ai_output",
    screen: "Jobs — CV builder",
    file: "src/routes/_authenticated/app.jobs.tsx",
  },
  {
    id: "study_ai_output",
    screen: "Study Buddy tutor",
    file: "src/routes/_authenticated/app.study.tsx",
  },
  { id: "ting_ai_output", screen: "Ting assistant", file: "src/routes/_authenticated/app.ai.tsx" },
  {
    id: "lores_ai_output",
    screen: "Lores — ONIQ Originals",
    file: "src/routes/_authenticated/app.lores.tsx",
  },
  {
    // The Stories tab under Lores. A user's OWN prompt drives this one, which
    // makes the label more necessary rather than less: the output is generated
    // whoever wrote the prompt, and a video someone made themselves is exactly
    // the one they are most likely to pass off as filmed.
    id: "stories_ai_output",
    screen: "Lores — Stories studio",
    file: "src/components/stories/StoryStudio.tsx",
  },
  {
    // The USER-FACING half of the in-house GPU generation path (LTX-Video on
    // ONIQ's own rented A5000): the video-clips panel on the Stories studio,
    // opened to signed-in users 2026-08-27 after the path passed its full
    // production proof. Same surface id as the admin tool below — one
    // generation path, one report bucket.
    id: "gpu_video_ai_output",
    screen: "Lores — Stories studio (video clips panel)",
    file: "src/components/stories/VideoClips.tsx",
  },
  {
    // The in-house GPU generation tool's ADMIN operator view. Declared
    // BEFORE the wider rollout above — the ordering Lores originally got
    // wrong.
    id: "gpu_video_ai_output",
    screen: "Admin — in-house GPU video tool (moderation-inbox panel)",
    // Moved from the standalone route (which stays as a fallback surface and
    // still renders the same label + report control) when the tool became an
    // inline inbox panel, 2026-08-26.
    file: "src/components/admin/GpuVideoPanel.tsx",
  },
  {
    // The standalone route remains as a fallback surface for the same tool;
    // it renders the identical label + report control.
    //
    // THE UNDERSCORE IN THE FILENAME IS LOAD-BEARING, not a typo. It opts the
    // route out of nesting under app.admin.tsx, which has no <Outlet /> and so
    // swallowed all three admin tools whole — see routeNesting.test.ts. The
    // URL is unchanged; only the route id moves.
    id: "gpu_video_ai_output",
    screen: "Admin — in-house GPU video tool (standalone fallback page)",
    file: "src/routes/_authenticated/app.admin_.gpu-video.tsx",
  },
  {
    // "Your videos" — the library where a finished Story is watched and saved.
    // A SEPARATE SURFACE FROM THE STUDIO, because it is where the generated
    // video is actually WATCHED. The studio only ever shows a progress line;
    // this is the screen someone could screenshot and pass off as filmed, which
    // is precisely what the label is for.
    id: "stories_library_output",
    screen: "Lores — Your videos",
    file: "src/components/stories/YourVideos.tsx",
  },
  {
    id: "runway_admin_output",
    screen: "Admin — Runway video tool (internal)",
    file: "src/routes/_authenticated/app.admin_.video.tsx",
  },
  {
    // The Watch library's "Ask ONIQ about this video" (owner mission,
    // 2026-09-03). The answer is generated from the person's own notes and
    // the video's metadata — never a transcript, never the video — and it is
    // labelled where it renders.
    id: "watch_ai_output",
    screen: "Watch — library (Ask ONIQ about a video)",
    file: "src/components/watch/library/ItemSheet.tsx",
  },
  {
    // The Home loop's Originals face — the same generated season, autoplaying
    // on the app's front door, which is exactly where the label matters most.
    id: "home_originals_loop",
    screen: "Home — Originals loop",
    file: "src/routes/_authenticated/app.index.tsx",
  },
  {
    // ONIQ HEALTH, Phase 2 (dark). The timeline renders AI-read rows — a
    // confirmed candidate keeps its document_extraction provenance — and the
    // gateway's answers. Declared BEFORE the flag flips, which is the ordering
    // Lores got wrong; docs/health/02 §12a said this line would be needed the
    // day the first AI-derived row could exist, and that day is Phase 2.
    id: "health_ai_output",
    screen: "Health — timeline (AI-read rows, answers)",
    file: "src/routes/_authenticated/app.health.index.tsx",
  },
  {
    // The Documents tab's "Suggested records": what the extractor read,
    // waiting on the person's confirm or reject. AI output by definition.
    id: "health_ai_output",
    screen: "Health — documents (suggested records)",
    file: "src/routes/_authenticated/app.health.records.tsx",
  },
  {
    // The admin verification door for the Health AI gateway. An admin screen
    // still shows generated output, and the label goes where the output goes.
    // Underscore in the filename: opts out of nesting under app.admin.tsx,
    // which has no <Outlet /> (routeNesting.test.ts).
    id: "health_ai_output",
    screen: "Admin — Health AI verification (standalone page)",
    file: "src/routes/_authenticated/app.admin_.health-ai.tsx",
  },
] as const;

/**
 * Surfaces whose label is NOT the app-wide AI_OUTPUT_LABEL, by owner directive.
 *
 * ONIQ Health renders "AI-assisted" — HEALTH_AI_LABEL in src/health/labels.ts,
 * owner directive 2026-09-08 (B12): "clear and non-alarming", never "AI
 * Doctor", "Medical AI" or "Diagnosis" — under a disclosure that sends the
 * person to their records and a qualified professional. The value here is the
 * IDENTIFIER the surface's file must carry; playCompliance.test.ts requires it
 * in place of the app-wide one, so a health screen that drops its label still
 * fails the same guard every other AI surface fails. The wording itself lives
 * once, in labels.ts, and src/health/__tests__/ai/surfaces.test.ts bans the
 * alternatives the directive names.
 */
export const AI_LABEL_OVERRIDES: Readonly<Record<string, string>> = {
  health_ai_output: "HEALTH_AI_LABEL",
};

/**
 * Modules whose CONTENT is AI-generated. Any screen rendering one of these is
 * a generative surface and must appear in AI_SURFACES above.
 *
 * This list exists because the "none missed" guard could not see Lores.
 * That guard looks for files which already render <AiOutputReport /> but are
 * undeclared — so it catches a stale list, and is blind to the failure its own
 * comment names: a surface that renders NO label at all imports nothing to
 * match on. Lores shipped a hub of entirely Runway-generated video and the
 * guard had nothing to grep for.
 *
 * Naming the data modules fixes the direction. A generative surface has to get
 * its content from somewhere, and that somewhere is far easier to enumerate
 * than every way a screen might render it.
 *
 * `@/data/ep3Shots` is the episode 3 shot list — sixty prompts that produce
 * sixty generated video clips. Nothing renders it today; it is declared anyway,
 * because the entire point of enumerating sources is that the declaration
 * exists BEFORE the screen does. That ordering is what Lores got wrong.
 */
export const AI_CONTENT_MODULES = [
  "@/data/lores",
  "@/data/originals",
  "@/data/ep3Shots",
  // Episode 4's shot list — declared before anything renders it, which is the
  // ordering Lores originally got wrong and this list exists to enforce.
  "@/data/ep4Shots",
] as const;

/**
 * DATA SAFETY — WHAT ONIQ ACTUALLY COLLECTS, as the Play form, in code.
 *
 * The declaration must match reality. Data that never leaves the device is not
 * "collected" — but anything that does leave has to be listed, including
 * third-party requests made by decorative elements, which is the part people
 * forget.
 *
 * This exists because the form was about to be filled in from a false premise.
 * NATIVE_CAPABILITIES used to claim health readings never left the device,
 * which would have become a "no health data collected" declaration while
 * health_profiles, health_checkins and cycle_logs held real rows.
 *
 * A wrong Data safety declaration is not a paperwork error. Play treats it as
 * a policy violation in its own right, independently of whatever the app does
 * — you can be removed for declaring incorrectly even where the underlying
 * processing would have been fine if declared.
 *
 * So: declare it, then say honestly what protects it. The protections here are
 * real and checkable, which is the only kind worth listing.
 */
export type CollectedData = {
  category: string;
  /** Play's own taxonomy word, so the form can be filled straight from this. */
  playType: string;
  what: string;
  /** Why it leaves the device at all. */
  purpose: string;
  /** True where the user can use ONIQ without providing it. */
  optional: boolean;
  /** The controls that actually apply. No aspirations. */
  protection: string;
};

export const DATA_COLLECTED: CollectedData[] = [
  {
    category: "Health and fitness",
    playType: "Health info",
    what: "Mood, sleep, energy, water and exercise check-ins, and cycle logs.",
    purpose:
      "Rendering the user's own history back to them. Never used for advertising, never sold, never shared with a third party.",
    optional: true,
    protection:
      "Row-level security: readable and writable only by the account that created it. A two-axis UAE block enforced in Postgres by health_data_allowed() refuses the write outright where the data would be generated in the UAE. Included in data export and account deletion.",
  },
  {
    category: "Health and fitness",
    playType: "Health info",
    // Phase 3b (owner directive 2026-09-09, "A, B and C"): uploads are ON.
    // playDeclaration.test.ts requires an entry naming reports exactly when
    // HEALTH_UPLOADS_ENABLED is true; this is that entry.
    what: "Medical reports, prescriptions and discharge summaries the person chooses to upload to ONIQ Health (a PDF or a photo), and the readings ONIQ's AI reads out of them, which join the person's records only after they confirm each one.",
    purpose:
      "Keeping the person's own reports in one place and reading the values out of them at their request. Never used for advertising, never sold.",
    optional: true,
    protection:
      "Stored in a private bucket under the person's own prefix, reachable only through 60-second signed URLs minted by ONIQ's server after the storage consent. Read by the AI only under the separate AI consent, after which the report's text — or, for a photo or a scan, the file itself — is sent to Google Cloud Vertex AI (Gemini), receipted and audited. Deleted on request and by the retention policy.",
  },
  {
    category: "Personal identifiers",
    playType: "Personal info",
    what: "Display name, username, avatar, country, and date of birth where given.",
    purpose: "Account identity, the 18+ gate, and country-correct content.",
    optional: false,
    protection:
      "Date of birth is write-once and drives is_adult_18, which is enforced in RESTRICTIVE row-level security rather than only in the UI.",
  },
  {
    category: "Messages",
    playType: "Messages",
    what: "Chat messages, call metadata and any media the user attaches.",
    purpose: "Delivering the conversation.",
    optional: true,
    protection:
      "Readable only by conversation participants. WebRTC voice and video are peer-to-peer and are not recorded.",
  },
  {
    category: "User content",
    playType: "Photos and videos",
    what: "Moments, clips and profile images the user uploads.",
    purpose: "Showing them to the audience the user chose.",
    optional: true,
    protection: "Deleted with the account; reportable in-app.",
  },
  {
    // PRECISE, not approximate. The manifest declares ACCESS_FINE_LOCATION and
    // the code asks for it: miniapps.ts and app.learn.tsx both call
    // getCurrentPosition with enableHighAccuracy:true and read
    // coords.latitude/longitude. Declaring this as merely "approximate" was
    // wrong, and Play's 15 July 2026 announcement specifically called out
    // precise-versus-approximate disclosure as an area it is tightening.
    category: "Precise location",
    playType: "Precise location",
    what: "Exact latitude and longitude, read only when the user taps to use their current location for a ride, delivery or nearby lookup.",
    purpose:
      "Setting a pickup point or finding what is nearby. Never used for advertising, never sold, never stored on ONIQ's servers.",
    optional: true,
    protection:
      "Requested at the moment of use, not at launch. The coordinates go to the geocoder to resolve a place and are not persisted by ONIQ.",
  },
  {
    category: "Approximate location",
    playType: "Approximate location",
    what: "A typed address, and the country-level region signal.",
    purpose: "Turning a place name into coordinates, and showing country-correct content.",
    optional: true,
    protection:
      "The country-level signal comes from the Cloudflare edge header, is used for the decision and discarded, and is never stored.",
  },
  {
    // READ_CONTACTS is in the manifest and getNativeContacts() uses it. It was
    // undeclared, which is the same class of error as the health claim.
    category: "Contacts",
    playType: "Contacts",
    what: "Phone numbers from the device address book, when the user chooses to find friends already on ONIQ.",
    purpose: "Matching contacts to existing ONIQ accounts.",
    optional: true,
    protection:
      "Only on an explicit tap — never read at launch or in the background. Numbers are normalised and matched, and the address book is not uploaded wholesale or retained as a contact graph.",
  },
  {
    // Play's 15 July 2026 clarification: the User Data policy applies to
    // third-party AI integrations, and the developer stays responsible for
    // limited use, disclosure and consent. ONIQ's generative surfaces send
    // user input to Anthropic. That has to be disclosed like any other
    // third-party processing, because it is.
    category: "AI processing",
    playType: "App activity / user-generated content",
    what: "What the user types into Ting, Study Buddy, or the CV builder — including the facts they enter about themselves for a CV — is sent to Anthropic's API to generate a response. Separately, the ONIQ Health AI features send the health readings a person chooses to ask about (kind, name, value, unit, date), and any uploaded report the person asks the AI to read (its text, or the photo or PDF itself), to Google Cloud Vertex AI (Gemini), under a consent granted in Health settings.",
    purpose:
      "Producing the answer, the practice paper or the CV the user asked for. Not used to train a model, not used for advertising, not sold.",
    optional: true,
    // Owner directive 2026-09-09: the absolute "never sent to any AI surface" is
    // gone with the privacy notice's sentence. Health data is no part of the
    // three Anthropic surfaces; the health features' own position is the
    // consent-conditioned statement the notice now carries
    // (HEALTH_AI_PRIVACY_STATEMENT in src/config/privacy.ts) plus the
    // recipient sentence Phase 3 added (HEALTH_AI_RECIPIENT_SENTENCE),
    // mirrored here so the three cannot disagree.
    protection:
      "Health data is not part of the three Anthropic surfaces. ONIQ's AI-assisted health features may process health data only when the person chooses to use them and provides the required consent, under the privacy, security, consent, audit and safety controls the privacy notice describes. When they use them, the records they ask about, and any report they ask it to read (its text, or the photo or PDF itself), are sent to Google Cloud Vertex AI (Gemini), operated by Google, to produce the answer, and are not used to train Google's models. Output is labelled AI-assisted and reportable in-app.",
  },
];

/** Health data IS collected. Anything claiming otherwise is a bug — see the test. */
export const HEALTH_DATA_IS_COLLECTED = true;

export type ThirdPartyRequest = {
  host: string;
  triggeredBy: string;
  sends: string;
  purpose: string;
  avoidable: boolean;
};

export const THIRD_PARTY_REQUESTS: ThirdPartyRequest[] = [
  {
    host: "images.dmca.com",
    triggeredBy: "The DMCA.com protection badge in the landing-page footer.",
    sends: "IP address and user-agent, on every landing-page view.",
    purpose:
      "Renders the badge. Hotlinked deliberately — dmca.com serves it against the protection ID so it cannot be faked or outlive a lapsed subscription.",
    avoidable: true,
  },
  {
    // BACK, because the player is back (owner directive, 2026-08-16 evening).
    //
    // This entry was removed earlier the same day when Watch became a list of
    // links, on the reasoning that a destination the user taps is not a
    // request ONIQ makes. That reasoning still holds for the LIST — no row
    // contacts Google until it is tapped — but stops holding the moment a
    // frame renders, so the declaration comes back with it.
    //
    // AUTOMATIC, and declared as such. An earlier version of this entry said
    // the request fired "only after a deliberate tap". That stopped being true
    // on 2026-08-16 evening, when the owner restored the Home loop player with
    // autoplay: opening Watch, or selecting the watch face of the Home banner
    // toggle, starts a muted playlist without any further tap. The narrower
    // wording is not kept, because a declaration that is nearly true is the
    // Play problem this file exists to prevent.
    //
    // What is still true: the Home banner defaults to `study`, so a user who
    // never selects the watch face never reaches Google from Home; and no
    // thumbnail or artwork is loaded from Google anywhere, on any screen.
    host: "www.youtube-nocookie.com",
    triggeredBy:
      "Opening Watch (src/routes/_authenticated/app.watch.tsx), or selecting the watch face of the Home banner toggle (src/routes/_authenticated/app.index.tsx) — both autoplay a muted playlist on load, including the devotional loop, which by design keeps playing for a duration the user picks. Also on tapping a channel in Faith → watch (src/routes/_authenticated/app.faith.tsx), which does NOT autoplay.",
    sends:
      "IP address and user-agent, plus the playlist id being watched. The -nocookie origin means no viewing history is written to a Google advertising profile unless playback starts.",
    purpose:
      "Plays the channel in YouTube's own player. ONIQ resolves no stream URL and proxies no video; YouTube serves the content, its ads, and its own geo and age restrictions.",
    avoidable: true,
  },
  {
    // The IFrame Player API itself, which is a SCRIPT from a Google host and
    // therefore its own automatic request — distinct from the frame above and
    // easy to leave undeclared because it is loaded by a helper rather than
    // written into any screen's markup.
    host: "www.youtube.com",
    triggeredBy:
      "Loading the IFrame Player API (src/components/watch/WatchPlayer.tsx), on the first Watch screen or Home watch face of a session.",
    sends: "IP address and user-agent, to www.youtube.com and s.ytimg.com.",
    purpose:
      "Operates YouTube's own player — play, pause, mute, and the ended/error events the channel loop rotates on. It does not deliver video to ONIQ.",
    avoidable: true,
  },
  // FOUR MORE PLAYERS, owner directive 2026-09-03 (afternoon): "make them
  // just like we have youtube in watch, also include them in watch tab of
  // home screen". Each is the platform's OWN player in a frame, the same
  // shape as YouTube's above, and each is AUTOMATIC in the same way: a card
  // from that platform starts muted when it becomes the current item on the
  // Watch screen or on the Home watch face. No SDK script is loaded for any
  // of them — src/data/watchEmbeds.ts, and the test that holds it.
  {
    host: "player.vimeo.com",
    triggeredBy:
      "A Vimeo card becoming the current item on Watch (src/routes/_authenticated/app.watch.tsx) or on the Home watch face (src/routes/_authenticated/app.index.tsx), or a Vimeo link the user added to a genre of their own.",
    sends:
      "IP address and user-agent, plus the video id being watched. The frame carries Vimeo's dnt=1 flag, so Vimeo sets no session cookie and records no viewing analytics.",
    purpose:
      "Plays the video in Vimeo's own player. ONIQ resolves no stream URL and proxies no video; Vimeo serves the content and its own restrictions.",
    avoidable: true,
  },
  {
    host: "geo.dailymotion.com",
    triggeredBy:
      "A Dailymotion card becoming the current item on Watch or on the Home watch face, or a Dailymotion link the user added to a genre of their own.",
    sends:
      "IP address and user-agent, plus the video or playlist id being watched. Dailymotion's player sets its own cookies and serves its own ads.",
    purpose:
      "Plays the video or playlist in Dailymotion's own player. ONIQ resolves no stream URL and proxies no video.",
    avoidable: true,
  },
  {
    host: "player.twitch.tv",
    triggeredBy:
      "A Twitch card becoming the current item on Watch or on the Home watch face, or a Twitch link the user added to a genre of their own.",
    sends:
      "IP address and user-agent, the channel or video id being watched, and the embedding hostname, which Twitch requires as the `parent` parameter.",
    purpose:
      "Plays the live channel or video in Twitch's own player. ONIQ resolves no stream URL and proxies no video.",
    avoidable: true,
  },
  {
    host: "archive.org",
    triggeredBy:
      "An Internet Archive card becoming the current item on Watch or on the Home watch face, or an archive.org link the user added to a genre of their own. The Archive's player does not autoplay; it waits for a tap.",
    sends: "IP address and user-agent, plus the item identifier being watched.",
    purpose:
      "Plays a public-domain film in the Internet Archive's own player. ONIQ resolves no stream URL and proxies no video.",
    avoidable: true,
  },
  // THE WATCH LIBRARY'S METADATA LOOKUPS (owner mission, 2026-09-03) are made
  // FROM THE SERVER (supabase/functions/watch-resolve), once, when a person
  // saves a link or opens the Movies shelf — the device reaches only ONIQ's
  // own backend. Declared anyway, the way places.googleapis.com is: the
  // provider still receives ONIQ's server IP and the id being looked up.
  {
    // ONIQ HEALTH AI (Phase 3, owner directive 2026-09-09). Made FROM THE
    // SERVER (supabase/functions/_shared/health/ai/vertex.ts, reached only
    // through the health-ai gateway), with the Firebase project's service
    // account — the device reaches only ONIQ's own backend. Declared like the
    // Watch lookups above, and heavier than them: what travels is HEALTH
    // data, under the consent granted in Health settings and the privacy
    // notice's recipient sentence (HEALTH_AI_RECIPIENT_SENTENCE).
    host: "aiplatform.googleapis.com",
    triggeredBy:
      "Tapping Ask, Summarise or Explain on the Health tab, or Explain on an uploaded report, after granting the AI consent (src/routes/_authenticated/app.health.index.tsx, app.health.records.tsx).",
    sends:
      "The health records the person asked about — kind, name, value, unit and date, with identifiers scrubbed and record ids replaced by per-request aliases — and the question, from ONIQ's server to Google Cloud Vertex AI (Gemini). When the person taps Explain on an uploaded report, the report's text (read from the PDF on ONIQ's server) or, for a photo, a scan or a PDF with no text layer, the file itself, travels the same way, after the caps and the receipt. No user IP, no account, no record id.",
    purpose:
      "Producing the AI-assisted answer, which ONIQ validates before showing. Not used to train Google's models (Vertex AI data governance), not used for advertising, not sold.",
    avoidable: true,
  },
  {
    host: "vimeo.com",
    triggeredBy: "Saving a Vimeo link in the Watch library (server-side oEmbed lookup).",
    sends: "The video id, from ONIQ's server. No user IP, no account, no viewing history.",
    purpose: "Title, creator and length for the saved reference.",
    avoidable: true,
  },
  {
    host: "api.dailymotion.com",
    triggeredBy:
      "Saving a Dailymotion link in the Watch library (server-side public Data API lookup).",
    sends: "The video or playlist id, from ONIQ's server. No user IP, no account.",
    purpose: "Title, creator and length for the saved reference.",
    avoidable: true,
  },
  {
    host: "archive.org",
    triggeredBy:
      "Saving an Internet Archive link, checking its rights, or opening the Movies shelf in the Watch library (server-side metadata and search lookups).",
    sends:
      "The item identifier or the shelf's search terms, from ONIQ's server. No user IP, no account.",
    purpose:
      "Title, creator, length and the item's own licence and rights fields, so rights are shown as the source states them.",
    avoidable: true,
  },
  // One entry that used to sit here is deliberately still gone.
  //
  // date.nager.at and api.frankfurter.dev: both were Glance's, and Glance was
  // removed from the app. Nothing calls either host now.
  // The three below send LOCATION, not just an IP, which is a different and
  // heavier Data safety category. They were undeclared until the compliance
  // test went looking for automatic requests rather than link destinations.
  {
    host: "nominatim.openstreetmap.org",
    triggeredBy:
      "Address search and reverse geocoding in the mini-apps launcher (src/lib/miniapps.ts).",
    sends:
      "A typed search string, or latitude and longitude on reverse lookup, plus the IP address. Approximate location leaves the device.",
    purpose: "Turning a place name into coordinates and back, for ride and delivery hand-offs.",
    avoidable: false,
  },
  {
    host: "places.googleapis.com",
    triggeredBy: "Place autocomplete and place details (src/lib/places.functions.ts).",
    sends:
      "The partial address the user is typing and the selected place id, from the SERVER — the key never reaches the device. Google receives ONIQ's server IP, not the user's.",
    purpose: "Address autocomplete.",
    avoidable: false,
  },
  {
    host: "maps.googleapis.com",
    triggeredBy:
      "The route picture on Rides, once both pickup and destination are set (src/lib/mapImage.functions.ts). Same Maps Platform key as places.googleapis.com above — not a new provider, a second endpoint on the one already declared.",
    sends:
      "The pickup and destination coordinates, from the SERVER — the key never reaches the device. Google receives ONIQ's server IP, not the user's. The finished picture comes back to the server and is handed to the client as bytes, so the client never talks to Google directly.",
    purpose: "Drawing the two points and the road between them as a small map image.",
    avoidable: false,
  },
  {
    // REPLACED api.openweathermap.org, 2026-09-04. That entry described a
    // screen that had been dead since the licence review — the key was never
    // set, so nothing was ever sent. Owner directive 2026-09-04h chose Google
    // Weather on the Firebase service account, so there is now a live weather
    // source and this is it. The OpenWeather path and its server function are
    // deleted rather than left dormant: a declared host that sends nothing is
    // a declaration that goes stale silently.
    host: "weather.googleapis.com",
    triggeredBy:
      "The Home weather chip and the Weather screen, and only for a person who has explicitly tapped to add their location. Never at launch, never without that tap.",
    sends:
      "A latitude and longitude SNAPPED TO A ~11 KM GRID, from the SERVER (the `weather` edge function) — the credential never reaches the device, and Google receives ONIQ's server IP rather than the user's. The exact position is never sent: the grid cell is both the cache key and the coordinate in the request. Nothing identifies the person, and no user id is involved.",
    purpose: "Current conditions for the place the user chose.",
    avoidable: true,
  },
  {
    // A SEPARATE HOST AND A SEPARATE ENTRY, added with owner directive
    // 2026-09-04i. It travels with the weather lookup and is enabled
    // separately on the project, so one can be reachable while the other is
    // not — the same reason capabilityRegistry gives them a row each. Folding
    // it into the weather line would make this list say "one Google host" when
    // there are two, and a Data safety declaration that is approximately true
    // is the failure this file exists to prevent.
    host: "airquality.googleapis.com",
    triggeredBy:
      "The same tap as the weather lookup: the Home chip and the Weather screen, only for a person who has explicitly added their location. Never at launch.",
    sends:
      "The same latitude and longitude SNAPPED TO A ~11 KM GRID, from the SERVER (the `weather` edge function), in the same round as the weather call. The credential never reaches the device, the exact position is never sent, and nothing identifies the person.",
    purpose: "The air quality index for the place the user chose.",
    avoidable: true,
  },
];

/**
 * NO THIRD-PARTY LOGOS. Publisher, broadcaster, exchange, board and app names
 * are text only, with the standing not-affiliated disclaimer. The one
 * exception is the DMCA.com badge, which is a vendor mark ONIQ subscribes to
 * and displays deliberately.
 */
export const ALLOWED_REMOTE_IMAGE_HOSTS = ["images.dmca.com"] as const;

export const NOT_AFFILIATED_NOTICE =
  "Names are used to tell you where a link goes. ONIQ is not affiliated with, endorsed by, or sponsored by any of them.";
