/**
 * L3 — BSA s.63 sealed evidence export. Run manually with counsel, only for
 * an APPROVED legal_requests row (dual-control enforced here AND by the DB
 * trigger): `SUPABASE_URL=... SUPABASE_SERVICE_ROLE_KEY=... npx tsx
 * scripts/evidence-export.ts <legal_request_id>`
 *
 * Emits docs/evidence-exports/<id>/: records.json, hash-report.txt
 * (SHA-256, BSA Schedule default), certificate-63.md (Part A populated,
 * Part B scaffold — signatures are for humans/counsel), custody-note.md.
 * The export is scope-limited to the request's target identifier + window.
 */
import { createClient } from "@supabase/supabase-js";
import { createHash } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";

const url = process.env.SUPABASE_URL;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
const requestId = process.argv[2];
if (!url || !key || !requestId) {
  console.error("Usage: SUPABASE_URL=.. SUPABASE_SERVICE_ROLE_KEY=.. npx tsx scripts/evidence-export.ts <legal_request_id>");
  process.exit(2);
}
const admin = createClient(url, key, { auth: { persistSession: false } });

async function main() {
  const { data: req, error } = await admin.from("legal_requests").select("*").eq("id", requestId).maybeSingle();
  if (error || !req) throw new Error(`legal_request not found: ${error?.message}`);
  if (req.status !== "approved") throw new Error(`request status is '${req.status}' — export requires 'approved'`);
  if (!req.approver_1 || !req.approver_2 || req.approver_1 === req.approver_2) {
    throw new Error("dual-control violation: two distinct approvals required");
  }

  // Minimum-necessary scope: the operator lists exact tables/filters here per
  // the request's records_sought; this scaffold exports nothing by default.
  const records: Record<string, unknown[]> = {
    _scope: [{
      target_identifier: req.target_identifier,
      records_sought: req.records_sought,
      window_start: req.window_start,
      window_end: req.window_end,
      note: "Populate per-request with counsel; empty by default (no fishing).",
    }],
  };

  const dir = `docs/evidence-exports/${requestId}`;
  mkdirSync(dir, { recursive: true });
  const body = JSON.stringify(records, null, 2);
  const sha256 = createHash("sha256").update(body).digest("hex");
  writeFileSync(`${dir}/records.json`, body);
  writeFileSync(`${dir}/hash-report.txt`,
`BSA Schedule hash report
Algorithm: SHA-256 (BSA-named; SHA1/MD5 also named but not used)
File: records.json
SHA-256: ${sha256}
Generated: ${new Date().toISOString()}
`);
  writeFileSync(`${dir}/certificate-63.md`,
`# Certificate under Section 63(4), Bharatiya Sakshya Adhiniyam, 2023

## Part A — party producing the record
- Producing party: ONIQ (oniqhub.com), operator of the computer resource.
- Electronic record: records.json (this export), produced from ONIQ's
  production database (Supabase/PostgreSQL, project bqwttemnnoexadpwifcj).
- Device/source particulars: managed cloud database and object storage
  regularly used by ONIQ in the ordinary course of its activities; the
  computer resource was operating properly at the time of export.
- Legal request: ${requestId} (order ref: ${req.order_ref ?? "—"};
  issuer: ${req.issuer_kind}${req.issuer_name ? " — " + req.issuer_name : ""}).
- Hash (SHA-256): ${sha256}
- Signature: ______________________  Name/designation: ______________  Date: ______

## Part B — expert
[Scaffold — to be completed and signed by a person with computer-science /
cyber-forensics expertise, per the 2026 Supreme Court clarification
(Pune Bar Association matter); counsel to confirm the signatory.]
- Examination performed: ______________________________________________
- Hash verification result: ___________________________________________
- Signature: ______________________  Name/qualifications: ____________  Date: ______
`);
  writeFileSync(`${dir}/custody-note.md`,
`# Chain of custody
1. ${new Date().toISOString()} — export generated by scripts/evidence-export.ts
   for legal_request ${requestId}; SHA-256 computed at generation: ${sha256}.
2. Sealed: store this directory read-only; any transfer must re-verify the
   hash (sha256sum records.json) and append a line here (who/when/why).
`);

  await admin.from("legal_requests").update({ status: "fulfilled", fulfilled_at: new Date().toISOString() }).eq("id", requestId);
  console.log(`export written to ${dir}; sha256=${sha256}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
