/**
 * OQCA v1.7 — THE FIRST REAL ONIQ INCIDENT PUT TO THE AUTONOMOUS RUNTIME.
 *
 * Every observation OQCA has been given until now was about its OWN file tree:
 * `scripts/oqca-self-improve.ts` walks the OQCA trees, builds the import graph
 * and derives `unreachable_path` / `missing_telemetry` findings from that. So
 * the loop has never once been handed a fault in the PRODUCT. This host does
 * that, with the readings measured on production 2026-09-11:
 *
 *   story-dispatch cannot reach GitHub. Every `repository_dispatch` comes back
 *   401 Bad credentials, no story worker has run since 2026-09-05T14:24:04Z,
 *   and two films sit `queued` with no shots and no bytes.
 *
 * WHAT THIS IS A TEST OF, stated before the run so the result can disagree with
 * it. v1.6 added `capability_blocked` as a fourth stop beside idle/blind/stalled
 * and its entry claims the name "is the difference between 'ONIQ is stuck' and
 * 'a credential is missing'". This is exactly that case, and it has never been
 * exercised on anything real. If the runtime reaches the credential, the claim
 * holds. If it answers `stalled`, `idle`, or names a different capability, the
 * claim is wrong and that is the finding.
 *
 * NOTHING HERE TELLS IT THE ANSWER. The evidence carries readings — a count, a
 * locator, a severity — and never a diagnosis or a remedy. The corpus is the
 * REAL source of the functions involved, read off disk at their real hashes, so
 * anything the loop retrieves it retrieved itself. The owner's §hard rule:
 * _"The test must be able to prove that the decision was generated by the
 * runtime from observed state, rather than being preselected by the test."_
 *
 * AND IT CANNOT FIX THIS. `UPDATE_CONFIGURATION` is registered and NOT
 * authorized (selfModel.ts), the kernel has no network by construction
 * (`security.test.ts` walks both trees), and §22 forbids autonomous cognition
 * manufacturing a credential. Naming the blocker IS the whole deliverable.
 */
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";

import { type Observation } from "../src/oqca/autonomy/observation.ts";
import { type SystemIdentity } from "../src/oqca/autonomy/world.ts";
import { runAutonomousRuntime, DEFAULT_RUNTIME_BOUNDS } from "../src/oqca/autonomy/runtime.ts";
import { resourcesFor } from "../supabase/functions/_shared/oqcaRuntime/selfModel.ts";
import type {
  CapabilityExecutor,
  CapabilityRequest,
} from "../supabase/functions/_shared/oqcaRuntime/selfModel.ts";
import {
  type EvidenceItem,
  type SystemEvidence,
  makeSystemObserver,
} from "../supabase/functions/_shared/oqcaRuntime/observe.ts";
import {
  type SubstrateContext,
  makeSinkCheckpointStore,
  makeSubstrateSurvey,
} from "../supabase/functions/_shared/oqcaRuntime/autonomous.ts";
import { makeImprovementEpisode } from "../supabase/functions/_shared/oqcaRuntime/improvement.ts";
import {
  type CorpusDocument,
  makeLocalEvidenceResearch,
} from "../supabase/functions/_shared/oqcaRuntime/research.ts";
import { makeSinkDurableStore } from "../supabase/functions/_shared/oqcaRuntime/durableStore.ts";

const ROOT = resolve(dirname(new URL(import.meta.url).pathname), "..");

function arg(name: string, fallback: string): string {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
}
const HAS = (name: string) => process.argv.includes(`--${name}`);

const DIR = resolve(ROOT, arg("dir", "docs/oqca/dispatch-incident"));
const KNOWLEDGE_FILE = join(DIR, "knowledge.json");
const CHECKPOINT_FILE = join(DIR, "checkpoint.json");
const LOG_FILE = join(DIR, "console.txt");

const sha = (s: string) => createHash("sha256").update(s).digest("hex").slice(0, 16);

const lines: string[] = [];
function say(s: string) {
  lines.push(s);
  console.log(s);
}

/**
 * THE READINGS, MEASURED ON PRODUCTION 2026-09-11. Each is a count somebody can
 * re-run: the SQL or the API call that produced it is the `locator`.
 *
 * `severity` is the host's, and it is the one number here that is a judgement
 * rather than a count — so the two that are judgements say what they are. A
 * total outage of a user-facing path is 1; a gap that makes a failure silent
 * but breaks nothing is lower. `null` would mean "read, and cannot say", which
 * is not the case for any of these.
 */
const READINGS: readonly EvidenceItem[] = [
  {
    kind: "provider_failure",
    subject: "github_repository_dispatch",
    locator: "production:net._http_response where created > now() - interval '3 hours'",
    sourceVersion: "2026-09-11T07:04:00Z",
    contentHash: null,
    detail:
      'every dispatch that had a film to send answered 502 {"error":"github dispatch failed: 401",' +
      '"usingToken":"GITHUB_DISPATCH_TOKEN","detail":"Bad credentials"}; 159 ticks in the same ' +
      'window answered 200 {"dispatched":false,"reason":"nothing queued"}',
    value: 33,
    severity: 1,
    requires: ["UPDATE_CONFIGURATION"],
  },
  {
    kind: "configuration_mismatch",
    subject: "GITHUB_DISPATCH_TOKEN",
    locator: "production:client_error_reports where surface = 'story-dispatch'",
    sourceVersion: "2026-09-11T07:03:00Z",
    contentHash: null,
    detail:
      "38 reports carry Bad credentials, first 2026-09-09, newest 2026-09-11T07:03Z; the 401 is " +
      "an authentication status and not the 403 a scope refusal returns",
    value: 38,
    severity: 1,
    requires: ["UPDATE_CONFIGURATION"],
  },
  {
    kind: "generation_failure",
    subject: "story_jobs",
    locator: "production:story_jobs order by created_at desc",
    sourceVersion: "2026-09-11T07:05:01Z",
    contentHash: null,
    detail:
      "two films created 2026-09-09 are status=queued with shot_count null and storage_path null; " +
      "dispatched_at is re-stamped every ten minutes and seconds_charged is 0 on both",
    value: 2,
    severity: 1,
    requires: ["UPDATE_CONFIGURATION"],
  },
  {
    kind: "error_rate",
    subject: "story_worker_workflow",
    locator:
      "github:repos/siddharthamondal1002-droid/oniq-sparkle-pay/actions/workflows/story-worker.yml/runs",
    sourceVersion: "2026-09-11T07:10:00Z",
    contentHash: null,
    detail:
      "the most recent run is #162 at 2026-09-05T14:24:04Z with conclusion success; no run of any " +
      "conclusion exists after it",
    value: 0,
    severity: 1,
    requires: ["UPDATE_CONFIGURATION"],
  },
  {
    kind: "missing_telemetry",
    subject: "story_sweep_stale_queue",
    locator: "supabase/functions/story-sweep/index.ts",
    sourceVersion: null,
    contentHash: null,
    detail:
      "the dead-job query requires status=queued and updated_at older than 30 minutes, and the " +
      "dispatcher re-stamps dispatched_at before each GitHub call, which bumps updated_at every " +
      "ten; a film whose dispatch keeps failing is therefore never expired, failed or refunded",
    value: 2,
    severity: 0.6,
    requires: ["REBUILD_ARTIFACT"],
  },
  {
    kind: "resource_availability",
    subject: "story_dispatch_function",
    locator: "production:net._http_response where created > now() - interval '3 hours'",
    sourceVersion: "2026-09-11T07:04:00Z",
    contentHash: null,
    detail:
      "the edge function is deployed and ticking: 159 responses of 200 in three hours, so the " +
      "dispatcher is running and being refused rather than being down",
    value: 159,
    severity: 0,
    requires: [],
  },
];

/**
 * THE CORPUS IS THE REAL SOURCE, not a summary of it. Anything the loop cites
 * it retrieved from bytes on disk at the hash recorded here — a note written
 * for this run would be me handing it the answer and calling the echo a result.
 */
const CORPUS_FILES = [
  "supabase/functions/story-dispatch/index.ts",
  "supabase/functions/story-sweep/index.ts",
  "supabase/functions/_shared/oqcaRuntime/selfModel.ts",
];

function corpus(): readonly CorpusDocument[] {
  const out: CorpusDocument[] = [];
  for (const rel of CORPUS_FILES) {
    let text: string;
    try {
      text = readFileSync(resolve(ROOT, rel), "utf8");
    } catch {
      continue; // A file this host cannot read is absent, never invented.
    }
    out.push({ locator: rel, sourceVersion: null, contentHash: sha(text), text });
  }
  return out;
}

async function main() {
  if (HAS("reset")) {
    rmSync(DIR, { recursive: true, force: true });
    say(`reset: ${relative(ROOT, DIR)} removed`);
  }
  mkdirSync(DIR, { recursive: true });

  const docs = corpus();
  say(`${READINGS.length} measured reading(s); corpus ${docs.length} file(s)`);

  const evidence: SystemEvidence = { read: async () => ({ ok: true, items: READINGS }) };
  const started = Date.now();
  const ctx: SubstrateContext = {
    at: () => new Date(started).toISOString(),
    nowMs: () => started,
  };

  const readFile = async (p: string) => {
    try {
      return readFileSync(p, "utf8");
    } catch {
      return null;
    }
  };
  const writeFile = async (p: string, json: string) => {
    writeFileSync(p, json);
    return true;
  };

  /** Same honest executor as the v1.7 host: it permits a knowledge write and runs nothing else. */
  const executor: CapabilityExecutor = async (req: CapabilityRequest) => {
    if (req.id === "UPDATE_KNOWLEDGE") {
      return {
        ok: true,
        value: Number(req.args.records ?? 0),
        unit: "records",
        detail: "permitted",
      };
    }
    return { ok: false, reason: `${req.id} is authorized but this host does not execute it` };
  };

  const identity: SystemIdentity = {
    name: "ONIQ",
    version: "oqca-v1.7",
    branch: arg("branch", "claude/check-56jtg5"),
    commit: null,
  };

  const report = await runAutonomousRuntime({
    survey: makeSubstrateSurvey(ctx),
    observe: makeSystemObserver(evidence, ctx.at),
    identity,
    needs: (o: Observation) => resourcesFor(o.requires),
    runEpisode: makeImprovementEpisode(ctx, {
      research: makeLocalEvidenceResearch(docs),
      durable: makeSinkDurableStore({
        read: () => readFile(KNOWLEDGE_FILE),
        write: (json) => writeFile(KNOWLEDGE_FILE, json),
        note: (m) => say(`  durable: ${m}`),
      }),
      executor,
    }),
    store: makeSinkCheckpointStore({
      read: () => readFile(CHECKPOINT_FILE),
      write: (json) => writeFile(CHECKPOINT_FILE, json),
      note: (m) => say(`  checkpoint: ${m}`),
    }),
    clock: () => Date.now(),
    bounds: { ...DEFAULT_RUNTIME_BOUNDS, maxEpisodes: Number(arg("episodes", "3")) },
  });

  say("");
  say(`restored      ${report.restored}`);
  say(`episodes      ${report.episodes}`);
  say(`stop          ${report.stop} — ${report.stopDetail}`);
  say(`generated     ${report.generated} objective(s)`);
  say(`concerns      ${report.concerns.length} ranked`);
  for (const c of report.concerns) {
    const f = c.planning;
    say(
      `  ${c.score.toFixed(5)} tgt=${c.target.score.toFixed(5)}` +
        ` cap=${f.capability.toFixed(2)} cost=${f.cost.toFixed(2)} rev=${f.reversibility.toFixed(2)}` +
        ` risk=${f.risk.toFixed(2)} dep=${f.dependencies.toFixed(2)} exp=${f.expectedImprovement.toFixed(2)}` +
        `  ${c.observation.state.padEnd(10)} ${c.goal.id}`,
    );
    const t = c.target.factors;
    say(
      `          learn[imp=${t.importance.toFixed(3)} unc=${t.uncertainty.toFixed(3)}` +
        ` dep=${t.dependency.toFixed(3)} gain=${t.informationGain.toFixed(3)}` +
        ` stale=${t.staleness.toFixed(3)} rel=${t.relevance.toFixed(3)}] ${c.target.status}`,
    );
  }
  say(
    `observed      ${report.observations.filter((o) => o.state === "OBSERVED").length}/${report.observations.length} kinds`,
  );
  say(`settled       ${report.settled.length}`);
  say(`learned       ${report.learned.length}`);
  say(`persisted     ${report.persisted.length}`);
  say(`checkpoints   ${report.checkpoints}/${report.checkpointAttempts}`);
  for (const h of report.history.slice(-Number(arg("episodes", "3")))) {
    say(`  #${h.episode} ${h.goalId} ${h.status} [${h.experimentVerdict ?? "no experiment"}]`);
    say(`      ${h.note}`);
    if (h.selfEvaluation) say(`      ${h.selfEvaluation.summary}`);
  }

  const prior = (await readFile(LOG_FILE)) ?? "";
  writeFileSync(LOG_FILE, `${prior}${prior ? "\n" : ""}${lines.join("\n")}\n`);
}

void main();
