/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as McpSigninRouteImport } from './routes/mcp-signin'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthNativeCallbackRouteImport } from './routes/auth-native-callback'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogWhatIsASuperAppRouteImport } from './routes/blog.what-is-a-super-app'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppWeatherRouteImport } from './routes/_authenticated/app.weather'
import { Route as AuthenticatedAppWalletRouteImport } from './routes/_authenticated/app.wallet'
import { Route as AuthenticatedAppVitalsRouteImport } from './routes/_authenticated/app.vitals'
import { Route as AuthenticatedAppUpiRouteImport } from './routes/_authenticated/app.upi'
import { Route as AuthenticatedAppTravelRouteImport } from './routes/_authenticated/app.travel'
import { Route as AuthenticatedAppScanRouteImport } from './routes/_authenticated/app.scan'
import { Route as AuthenticatedAppRidesRouteImport } from './routes/_authenticated/app.rides'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppNewsRouteImport } from './routes/_authenticated/app.news'
import { Route as AuthenticatedAppMiniappsRouteImport } from './routes/_authenticated/app.miniapps'
import { Route as AuthenticatedAppLearnRouteImport } from './routes/_authenticated/app.learn'
import { Route as AuthenticatedAppFaithRouteImport } from './routes/_authenticated/app.faith'
import { Route as AuthenticatedAppDiscoverRouteImport } from './routes/_authenticated/app.discover'
import { Route as AuthenticatedAppClipsRouteImport } from './routes/_authenticated/app.clips'
import { Route as AuthenticatedAppChatRouteImport } from './routes/_authenticated/app.chat'
import { Route as AuthenticatedAppBanksRouteImport } from './routes/_authenticated/app.banks'
import { Route as AuthenticatedAppAiRouteImport } from './routes/_authenticated/app.ai'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app.admin'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedAppFoodIndexRouteImport } from './routes/_authenticated/app.food.index'
import { Route as AuthenticatedAppChatIndexRouteImport } from './routes/_authenticated/app.chat.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as AuthenticatedAppFoodIdRouteImport } from './routes/_authenticated/app.food.$id'
import { Route as AuthenticatedAppChatConversationIdRouteImport } from './routes/_authenticated/app.chat.$conversationId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const McpSigninRoute = McpSigninRouteImport.update({
  id: '/mcp-signin',
  path: '/mcp-signin',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthNativeCallbackRoute = AuthNativeCallbackRouteImport.update({
  id: '/auth-native-callback',
  path: '/auth-native-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogWhatIsASuperAppRoute = BlogWhatIsASuperAppRouteImport.update({
  id: '/blog/what-is-a-super-app',
  path: '/blog/what-is-a-super-app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppWeatherRoute = AuthenticatedAppWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppWalletRoute = AuthenticatedAppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppVitalsRoute = AuthenticatedAppVitalsRouteImport.update({
  id: '/vitals',
  path: '/vitals',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppUpiRoute = AuthenticatedAppUpiRouteImport.update({
  id: '/upi',
  path: '/upi',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTravelRoute = AuthenticatedAppTravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppScanRoute = AuthenticatedAppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRidesRoute = AuthenticatedAppRidesRouteImport.update({
  id: '/rides',
  path: '/rides',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNewsRoute = AuthenticatedAppNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMiniappsRoute =
  AuthenticatedAppMiniappsRouteImport.update({
    id: '/miniapps',
    path: '/miniapps',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLearnRoute = AuthenticatedAppLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppFaithRoute = AuthenticatedAppFaithRouteImport.update({
  id: '/faith',
  path: '/faith',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDiscoverRoute =
  AuthenticatedAppDiscoverRouteImport.update({
    id: '/discover',
    path: '/discover',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppClipsRoute = AuthenticatedAppClipsRouteImport.update({
  id: '/clips',
  path: '/clips',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppChatRoute = AuthenticatedAppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBanksRoute = AuthenticatedAppBanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAiRoute = AuthenticatedAppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppFoodIndexRoute =
  AuthenticatedAppFoodIndexRouteImport.update({
    id: '/food/',
    path: '/food/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppChatIndexRoute =
  AuthenticatedAppChatIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppChatRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppFoodIdRoute = AuthenticatedAppFoodIdRouteImport.update({
  id: '/food/$id',
  path: '/food/$id',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppChatConversationIdRoute =
  AuthenticatedAppChatConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedAppChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auth-native-callback': typeof AuthNativeCallbackRoute
  '/mcp': typeof McpRoute
  '/mcp-signin': typeof McpSigninRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/blog/what-is-a-super-app': typeof BlogWhatIsASuperAppRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/ai': typeof AuthenticatedAppAiRoute
  '/app/banks': typeof AuthenticatedAppBanksRoute
  '/app/chat': typeof AuthenticatedAppChatRouteWithChildren
  '/app/clips': typeof AuthenticatedAppClipsRoute
  '/app/discover': typeof AuthenticatedAppDiscoverRoute
  '/app/faith': typeof AuthenticatedAppFaithRoute
  '/app/learn': typeof AuthenticatedAppLearnRoute
  '/app/miniapps': typeof AuthenticatedAppMiniappsRoute
  '/app/news': typeof AuthenticatedAppNewsRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/rides': typeof AuthenticatedAppRidesRoute
  '/app/scan': typeof AuthenticatedAppScanRoute
  '/app/travel': typeof AuthenticatedAppTravelRoute
  '/app/upi': typeof AuthenticatedAppUpiRoute
  '/app/vitals': typeof AuthenticatedAppVitalsRoute
  '/app/wallet': typeof AuthenticatedAppWalletRoute
  '/app/weather': typeof AuthenticatedAppWeatherRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/chat/$conversationId': typeof AuthenticatedAppChatConversationIdRoute
  '/app/food/$id': typeof AuthenticatedAppFoodIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/app/chat/': typeof AuthenticatedAppChatIndexRoute
  '/app/food/': typeof AuthenticatedAppFoodIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auth-native-callback': typeof AuthNativeCallbackRoute
  '/mcp': typeof McpRoute
  '/mcp-signin': typeof McpSigninRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/what-is-a-super-app': typeof BlogWhatIsASuperAppRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/ai': typeof AuthenticatedAppAiRoute
  '/app/banks': typeof AuthenticatedAppBanksRoute
  '/app/clips': typeof AuthenticatedAppClipsRoute
  '/app/discover': typeof AuthenticatedAppDiscoverRoute
  '/app/faith': typeof AuthenticatedAppFaithRoute
  '/app/learn': typeof AuthenticatedAppLearnRoute
  '/app/miniapps': typeof AuthenticatedAppMiniappsRoute
  '/app/news': typeof AuthenticatedAppNewsRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/rides': typeof AuthenticatedAppRidesRoute
  '/app/scan': typeof AuthenticatedAppScanRoute
  '/app/travel': typeof AuthenticatedAppTravelRoute
  '/app/upi': typeof AuthenticatedAppUpiRoute
  '/app/vitals': typeof AuthenticatedAppVitalsRoute
  '/app/wallet': typeof AuthenticatedAppWalletRoute
  '/app/weather': typeof AuthenticatedAppWeatherRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/chat/$conversationId': typeof AuthenticatedAppChatConversationIdRoute
  '/app/food/$id': typeof AuthenticatedAppFoodIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/app/chat': typeof AuthenticatedAppChatIndexRoute
  '/app/food': typeof AuthenticatedAppFoodIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/auth-native-callback': typeof AuthNativeCallbackRoute
  '/mcp': typeof McpRoute
  '/mcp-signin': typeof McpSigninRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/blog/what-is-a-super-app': typeof BlogWhatIsASuperAppRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRoute
  '/_authenticated/app/ai': typeof AuthenticatedAppAiRoute
  '/_authenticated/app/banks': typeof AuthenticatedAppBanksRoute
  '/_authenticated/app/chat': typeof AuthenticatedAppChatRouteWithChildren
  '/_authenticated/app/clips': typeof AuthenticatedAppClipsRoute
  '/_authenticated/app/discover': typeof AuthenticatedAppDiscoverRoute
  '/_authenticated/app/faith': typeof AuthenticatedAppFaithRoute
  '/_authenticated/app/learn': typeof AuthenticatedAppLearnRoute
  '/_authenticated/app/miniapps': typeof AuthenticatedAppMiniappsRoute
  '/_authenticated/app/news': typeof AuthenticatedAppNewsRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/rides': typeof AuthenticatedAppRidesRoute
  '/_authenticated/app/scan': typeof AuthenticatedAppScanRoute
  '/_authenticated/app/travel': typeof AuthenticatedAppTravelRoute
  '/_authenticated/app/upi': typeof AuthenticatedAppUpiRoute
  '/_authenticated/app/vitals': typeof AuthenticatedAppVitalsRoute
  '/_authenticated/app/wallet': typeof AuthenticatedAppWalletRoute
  '/_authenticated/app/weather': typeof AuthenticatedAppWeatherRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/chat/$conversationId': typeof AuthenticatedAppChatConversationIdRoute
  '/_authenticated/app/food/$id': typeof AuthenticatedAppFoodIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/app/chat/': typeof AuthenticatedAppChatIndexRoute
  '/_authenticated/app/food/': typeof AuthenticatedAppFoodIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth-native-callback'
    | '/mcp'
    | '/mcp-signin'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app'
    | '/blog/what-is-a-super-app'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/admin'
    | '/app/ai'
    | '/app/banks'
    | '/app/chat'
    | '/app/clips'
    | '/app/discover'
    | '/app/faith'
    | '/app/learn'
    | '/app/miniapps'
    | '/app/news'
    | '/app/profile'
    | '/app/rides'
    | '/app/scan'
    | '/app/travel'
    | '/app/upi'
    | '/app/vitals'
    | '/app/wallet'
    | '/app/weather'
    | '/app/'
    | '/app/chat/$conversationId'
    | '/app/food/$id'
    | '/lovable/email/queue/process'
    | '/app/chat/'
    | '/app/food/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth-native-callback'
    | '/mcp'
    | '/mcp-signin'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/blog/what-is-a-super-app'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/admin'
    | '/app/ai'
    | '/app/banks'
    | '/app/clips'
    | '/app/discover'
    | '/app/faith'
    | '/app/learn'
    | '/app/miniapps'
    | '/app/news'
    | '/app/profile'
    | '/app/rides'
    | '/app/scan'
    | '/app/travel'
    | '/app/upi'
    | '/app/vitals'
    | '/app/wallet'
    | '/app/weather'
    | '/app'
    | '/app/chat/$conversationId'
    | '/app/food/$id'
    | '/lovable/email/queue/process'
    | '/app/chat'
    | '/app/food'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/auth-native-callback'
    | '/mcp'
    | '/mcp-signin'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/app'
    | '/blog/what-is-a-super-app'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/ai'
    | '/_authenticated/app/banks'
    | '/_authenticated/app/chat'
    | '/_authenticated/app/clips'
    | '/_authenticated/app/discover'
    | '/_authenticated/app/faith'
    | '/_authenticated/app/learn'
    | '/_authenticated/app/miniapps'
    | '/_authenticated/app/news'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/rides'
    | '/_authenticated/app/scan'
    | '/_authenticated/app/travel'
    | '/_authenticated/app/upi'
    | '/_authenticated/app/vitals'
    | '/_authenticated/app/wallet'
    | '/_authenticated/app/weather'
    | '/_authenticated/app/'
    | '/_authenticated/app/chat/$conversationId'
    | '/_authenticated/app/food/$id'
    | '/lovable/email/queue/process'
    | '/_authenticated/app/chat/'
    | '/_authenticated/app/food/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AuthNativeCallbackRoute: typeof AuthNativeCallbackRoute
  McpRoute: typeof McpRoute
  McpSigninRoute: typeof McpSigninRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  BlogWhatIsASuperAppRoute: typeof BlogWhatIsASuperAppRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp-signin': {
      id: '/mcp-signin'
      path: '/mcp-signin'
      fullPath: '/mcp-signin'
      preLoaderRoute: typeof McpSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-native-callback': {
      id: '/auth-native-callback'
      path: '/auth-native-callback'
      fullPath: '/auth-native-callback'
      preLoaderRoute: typeof AuthNativeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/what-is-a-super-app': {
      id: '/blog/what-is-a-super-app'
      path: '/blog/what-is-a-super-app'
      fullPath: '/blog/what-is-a-super-app'
      preLoaderRoute: typeof BlogWhatIsASuperAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/weather': {
      id: '/_authenticated/app/weather'
      path: '/weather'
      fullPath: '/app/weather'
      preLoaderRoute: typeof AuthenticatedAppWeatherRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/wallet': {
      id: '/_authenticated/app/wallet'
      path: '/wallet'
      fullPath: '/app/wallet'
      preLoaderRoute: typeof AuthenticatedAppWalletRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/vitals': {
      id: '/_authenticated/app/vitals'
      path: '/vitals'
      fullPath: '/app/vitals'
      preLoaderRoute: typeof AuthenticatedAppVitalsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/upi': {
      id: '/_authenticated/app/upi'
      path: '/upi'
      fullPath: '/app/upi'
      preLoaderRoute: typeof AuthenticatedAppUpiRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/travel': {
      id: '/_authenticated/app/travel'
      path: '/travel'
      fullPath: '/app/travel'
      preLoaderRoute: typeof AuthenticatedAppTravelRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/scan': {
      id: '/_authenticated/app/scan'
      path: '/scan'
      fullPath: '/app/scan'
      preLoaderRoute: typeof AuthenticatedAppScanRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/rides': {
      id: '/_authenticated/app/rides'
      path: '/rides'
      fullPath: '/app/rides'
      preLoaderRoute: typeof AuthenticatedAppRidesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/news': {
      id: '/_authenticated/app/news'
      path: '/news'
      fullPath: '/app/news'
      preLoaderRoute: typeof AuthenticatedAppNewsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/miniapps': {
      id: '/_authenticated/app/miniapps'
      path: '/miniapps'
      fullPath: '/app/miniapps'
      preLoaderRoute: typeof AuthenticatedAppMiniappsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/learn': {
      id: '/_authenticated/app/learn'
      path: '/learn'
      fullPath: '/app/learn'
      preLoaderRoute: typeof AuthenticatedAppLearnRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/faith': {
      id: '/_authenticated/app/faith'
      path: '/faith'
      fullPath: '/app/faith'
      preLoaderRoute: typeof AuthenticatedAppFaithRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/discover': {
      id: '/_authenticated/app/discover'
      path: '/discover'
      fullPath: '/app/discover'
      preLoaderRoute: typeof AuthenticatedAppDiscoverRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/clips': {
      id: '/_authenticated/app/clips'
      path: '/clips'
      fullPath: '/app/clips'
      preLoaderRoute: typeof AuthenticatedAppClipsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/chat': {
      id: '/_authenticated/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AuthenticatedAppChatRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/banks': {
      id: '/_authenticated/app/banks'
      path: '/banks'
      fullPath: '/app/banks'
      preLoaderRoute: typeof AuthenticatedAppBanksRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ai': {
      id: '/_authenticated/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AuthenticatedAppAiRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/food/': {
      id: '/_authenticated/app/food/'
      path: '/food'
      fullPath: '/app/food/'
      preLoaderRoute: typeof AuthenticatedAppFoodIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/chat/': {
      id: '/_authenticated/app/chat/'
      path: '/'
      fullPath: '/app/chat/'
      preLoaderRoute: typeof AuthenticatedAppChatIndexRouteImport
      parentRoute: typeof AuthenticatedAppChatRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/food/$id': {
      id: '/_authenticated/app/food/$id'
      path: '/food/$id'
      fullPath: '/app/food/$id'
      preLoaderRoute: typeof AuthenticatedAppFoodIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/chat/$conversationId': {
      id: '/_authenticated/app/chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/app/chat/$conversationId'
      preLoaderRoute: typeof AuthenticatedAppChatConversationIdRouteImport
      parentRoute: typeof AuthenticatedAppChatRoute
    }
  }
}

interface AuthenticatedAppChatRouteChildren {
  AuthenticatedAppChatConversationIdRoute: typeof AuthenticatedAppChatConversationIdRoute
  AuthenticatedAppChatIndexRoute: typeof AuthenticatedAppChatIndexRoute
}

const AuthenticatedAppChatRouteChildren: AuthenticatedAppChatRouteChildren = {
  AuthenticatedAppChatConversationIdRoute:
    AuthenticatedAppChatConversationIdRoute,
  AuthenticatedAppChatIndexRoute: AuthenticatedAppChatIndexRoute,
}

const AuthenticatedAppChatRouteWithChildren =
  AuthenticatedAppChatRoute._addFileChildren(AuthenticatedAppChatRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRoute
  AuthenticatedAppAiRoute: typeof AuthenticatedAppAiRoute
  AuthenticatedAppBanksRoute: typeof AuthenticatedAppBanksRoute
  AuthenticatedAppChatRoute: typeof AuthenticatedAppChatRouteWithChildren
  AuthenticatedAppClipsRoute: typeof AuthenticatedAppClipsRoute
  AuthenticatedAppDiscoverRoute: typeof AuthenticatedAppDiscoverRoute
  AuthenticatedAppFaithRoute: typeof AuthenticatedAppFaithRoute
  AuthenticatedAppLearnRoute: typeof AuthenticatedAppLearnRoute
  AuthenticatedAppMiniappsRoute: typeof AuthenticatedAppMiniappsRoute
  AuthenticatedAppNewsRoute: typeof AuthenticatedAppNewsRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppRidesRoute: typeof AuthenticatedAppRidesRoute
  AuthenticatedAppScanRoute: typeof AuthenticatedAppScanRoute
  AuthenticatedAppTravelRoute: typeof AuthenticatedAppTravelRoute
  AuthenticatedAppUpiRoute: typeof AuthenticatedAppUpiRoute
  AuthenticatedAppVitalsRoute: typeof AuthenticatedAppVitalsRoute
  AuthenticatedAppWalletRoute: typeof AuthenticatedAppWalletRoute
  AuthenticatedAppWeatherRoute: typeof AuthenticatedAppWeatherRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppFoodIdRoute: typeof AuthenticatedAppFoodIdRoute
  AuthenticatedAppFoodIndexRoute: typeof AuthenticatedAppFoodIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRoute,
  AuthenticatedAppAiRoute: AuthenticatedAppAiRoute,
  AuthenticatedAppBanksRoute: AuthenticatedAppBanksRoute,
  AuthenticatedAppChatRoute: AuthenticatedAppChatRouteWithChildren,
  AuthenticatedAppClipsRoute: AuthenticatedAppClipsRoute,
  AuthenticatedAppDiscoverRoute: AuthenticatedAppDiscoverRoute,
  AuthenticatedAppFaithRoute: AuthenticatedAppFaithRoute,
  AuthenticatedAppLearnRoute: AuthenticatedAppLearnRoute,
  AuthenticatedAppMiniappsRoute: AuthenticatedAppMiniappsRoute,
  AuthenticatedAppNewsRoute: AuthenticatedAppNewsRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppRidesRoute: AuthenticatedAppRidesRoute,
  AuthenticatedAppScanRoute: AuthenticatedAppScanRoute,
  AuthenticatedAppTravelRoute: AuthenticatedAppTravelRoute,
  AuthenticatedAppUpiRoute: AuthenticatedAppUpiRoute,
  AuthenticatedAppVitalsRoute: AuthenticatedAppVitalsRoute,
  AuthenticatedAppWalletRoute: AuthenticatedAppWalletRoute,
  AuthenticatedAppWeatherRoute: AuthenticatedAppWeatherRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppFoodIdRoute: AuthenticatedAppFoodIdRoute,
  AuthenticatedAppFoodIndexRoute: AuthenticatedAppFoodIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AuthNativeCallbackRoute: AuthNativeCallbackRoute,
  McpRoute: McpRoute,
  McpSigninRoute: McpSigninRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  BlogWhatIsASuperAppRoute: BlogWhatIsASuperAppRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
