/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppWeatherRouteImport } from './routes/_authenticated/app.weather'
import { Route as AuthenticatedAppWalletRouteImport } from './routes/_authenticated/app.wallet'
import { Route as AuthenticatedAppUpiRouteImport } from './routes/_authenticated/app.upi'
import { Route as AuthenticatedAppScanRouteImport } from './routes/_authenticated/app.scan'
import { Route as AuthenticatedAppRidesRouteImport } from './routes/_authenticated/app.rides'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppPayRouteImport } from './routes/_authenticated/app.pay'
import { Route as AuthenticatedAppMiniappsRouteImport } from './routes/_authenticated/app.miniapps'
import { Route as AuthenticatedAppDiscoverRouteImport } from './routes/_authenticated/app.discover'
import { Route as AuthenticatedAppChatRouteImport } from './routes/_authenticated/app.chat'
import { Route as AuthenticatedAppBanksRouteImport } from './routes/_authenticated/app.banks'
import { Route as AuthenticatedAppAiRouteImport } from './routes/_authenticated/app.ai'
import { Route as AuthenticatedAppFoodIndexRouteImport } from './routes/_authenticated/app.food.index'
import { Route as AuthenticatedAppChatIndexRouteImport } from './routes/_authenticated/app.chat.index'
import { Route as AuthenticatedAppFoodIdRouteImport } from './routes/_authenticated/app.food.$id'
import { Route as AuthenticatedAppChatConversationIdRouteImport } from './routes/_authenticated/app.chat.$conversationId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppWeatherRoute = AuthenticatedAppWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppWalletRoute = AuthenticatedAppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppUpiRoute = AuthenticatedAppUpiRouteImport.update({
  id: '/upi',
  path: '/upi',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppScanRoute = AuthenticatedAppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRidesRoute = AuthenticatedAppRidesRouteImport.update({
  id: '/rides',
  path: '/rides',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPayRoute = AuthenticatedAppPayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMiniappsRoute =
  AuthenticatedAppMiniappsRouteImport.update({
    id: '/miniapps',
    path: '/miniapps',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDiscoverRoute =
  AuthenticatedAppDiscoverRouteImport.update({
    id: '/discover',
    path: '/discover',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppChatRoute = AuthenticatedAppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBanksRoute = AuthenticatedAppBanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAiRoute = AuthenticatedAppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppFoodIndexRoute =
  AuthenticatedAppFoodIndexRouteImport.update({
    id: '/food/',
    path: '/food/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppChatIndexRoute =
  AuthenticatedAppChatIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppChatRoute,
  } as any)
const AuthenticatedAppFoodIdRoute = AuthenticatedAppFoodIdRouteImport.update({
  id: '/food/$id',
  path: '/food/$id',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppChatConversationIdRoute =
  AuthenticatedAppChatConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedAppChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/ai': typeof AuthenticatedAppAiRoute
  '/app/banks': typeof AuthenticatedAppBanksRoute
  '/app/chat': typeof AuthenticatedAppChatRouteWithChildren
  '/app/discover': typeof AuthenticatedAppDiscoverRoute
  '/app/miniapps': typeof AuthenticatedAppMiniappsRoute
  '/app/pay': typeof AuthenticatedAppPayRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/rides': typeof AuthenticatedAppRidesRoute
  '/app/scan': typeof AuthenticatedAppScanRoute
  '/app/upi': typeof AuthenticatedAppUpiRoute
  '/app/wallet': typeof AuthenticatedAppWalletRoute
  '/app/weather': typeof AuthenticatedAppWeatherRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/chat/$conversationId': typeof AuthenticatedAppChatConversationIdRoute
  '/app/food/$id': typeof AuthenticatedAppFoodIdRoute
  '/app/chat/': typeof AuthenticatedAppChatIndexRoute
  '/app/food/': typeof AuthenticatedAppFoodIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/ai': typeof AuthenticatedAppAiRoute
  '/app/banks': typeof AuthenticatedAppBanksRoute
  '/app/discover': typeof AuthenticatedAppDiscoverRoute
  '/app/miniapps': typeof AuthenticatedAppMiniappsRoute
  '/app/pay': typeof AuthenticatedAppPayRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/rides': typeof AuthenticatedAppRidesRoute
  '/app/scan': typeof AuthenticatedAppScanRoute
  '/app/upi': typeof AuthenticatedAppUpiRoute
  '/app/wallet': typeof AuthenticatedAppWalletRoute
  '/app/weather': typeof AuthenticatedAppWeatherRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/chat/$conversationId': typeof AuthenticatedAppChatConversationIdRoute
  '/app/food/$id': typeof AuthenticatedAppFoodIdRoute
  '/app/chat': typeof AuthenticatedAppChatIndexRoute
  '/app/food': typeof AuthenticatedAppFoodIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/ai': typeof AuthenticatedAppAiRoute
  '/_authenticated/app/banks': typeof AuthenticatedAppBanksRoute
  '/_authenticated/app/chat': typeof AuthenticatedAppChatRouteWithChildren
  '/_authenticated/app/discover': typeof AuthenticatedAppDiscoverRoute
  '/_authenticated/app/miniapps': typeof AuthenticatedAppMiniappsRoute
  '/_authenticated/app/pay': typeof AuthenticatedAppPayRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/rides': typeof AuthenticatedAppRidesRoute
  '/_authenticated/app/scan': typeof AuthenticatedAppScanRoute
  '/_authenticated/app/upi': typeof AuthenticatedAppUpiRoute
  '/_authenticated/app/wallet': typeof AuthenticatedAppWalletRoute
  '/_authenticated/app/weather': typeof AuthenticatedAppWeatherRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/chat/$conversationId': typeof AuthenticatedAppChatConversationIdRoute
  '/_authenticated/app/food/$id': typeof AuthenticatedAppFoodIdRoute
  '/_authenticated/app/chat/': typeof AuthenticatedAppChatIndexRoute
  '/_authenticated/app/food/': typeof AuthenticatedAppFoodIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/app/ai'
    | '/app/banks'
    | '/app/chat'
    | '/app/discover'
    | '/app/miniapps'
    | '/app/pay'
    | '/app/profile'
    | '/app/rides'
    | '/app/scan'
    | '/app/upi'
    | '/app/wallet'
    | '/app/weather'
    | '/app/'
    | '/app/chat/$conversationId'
    | '/app/food/$id'
    | '/app/chat/'
    | '/app/food/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/ai'
    | '/app/banks'
    | '/app/discover'
    | '/app/miniapps'
    | '/app/pay'
    | '/app/profile'
    | '/app/rides'
    | '/app/scan'
    | '/app/upi'
    | '/app/wallet'
    | '/app/weather'
    | '/app'
    | '/app/chat/$conversationId'
    | '/app/food/$id'
    | '/app/chat'
    | '/app/food'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/app/ai'
    | '/_authenticated/app/banks'
    | '/_authenticated/app/chat'
    | '/_authenticated/app/discover'
    | '/_authenticated/app/miniapps'
    | '/_authenticated/app/pay'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/rides'
    | '/_authenticated/app/scan'
    | '/_authenticated/app/upi'
    | '/_authenticated/app/wallet'
    | '/_authenticated/app/weather'
    | '/_authenticated/app/'
    | '/_authenticated/app/chat/$conversationId'
    | '/_authenticated/app/food/$id'
    | '/_authenticated/app/chat/'
    | '/_authenticated/app/food/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/weather': {
      id: '/_authenticated/app/weather'
      path: '/weather'
      fullPath: '/app/weather'
      preLoaderRoute: typeof AuthenticatedAppWeatherRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/wallet': {
      id: '/_authenticated/app/wallet'
      path: '/wallet'
      fullPath: '/app/wallet'
      preLoaderRoute: typeof AuthenticatedAppWalletRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/upi': {
      id: '/_authenticated/app/upi'
      path: '/upi'
      fullPath: '/app/upi'
      preLoaderRoute: typeof AuthenticatedAppUpiRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/scan': {
      id: '/_authenticated/app/scan'
      path: '/scan'
      fullPath: '/app/scan'
      preLoaderRoute: typeof AuthenticatedAppScanRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/rides': {
      id: '/_authenticated/app/rides'
      path: '/rides'
      fullPath: '/app/rides'
      preLoaderRoute: typeof AuthenticatedAppRidesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pay': {
      id: '/_authenticated/app/pay'
      path: '/pay'
      fullPath: '/app/pay'
      preLoaderRoute: typeof AuthenticatedAppPayRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/miniapps': {
      id: '/_authenticated/app/miniapps'
      path: '/miniapps'
      fullPath: '/app/miniapps'
      preLoaderRoute: typeof AuthenticatedAppMiniappsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/discover': {
      id: '/_authenticated/app/discover'
      path: '/discover'
      fullPath: '/app/discover'
      preLoaderRoute: typeof AuthenticatedAppDiscoverRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/chat': {
      id: '/_authenticated/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AuthenticatedAppChatRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/banks': {
      id: '/_authenticated/app/banks'
      path: '/banks'
      fullPath: '/app/banks'
      preLoaderRoute: typeof AuthenticatedAppBanksRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ai': {
      id: '/_authenticated/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AuthenticatedAppAiRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/food/': {
      id: '/_authenticated/app/food/'
      path: '/food'
      fullPath: '/app/food/'
      preLoaderRoute: typeof AuthenticatedAppFoodIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/chat/': {
      id: '/_authenticated/app/chat/'
      path: '/'
      fullPath: '/app/chat/'
      preLoaderRoute: typeof AuthenticatedAppChatIndexRouteImport
      parentRoute: typeof AuthenticatedAppChatRoute
    }
    '/_authenticated/app/food/$id': {
      id: '/_authenticated/app/food/$id'
      path: '/food/$id'
      fullPath: '/app/food/$id'
      preLoaderRoute: typeof AuthenticatedAppFoodIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/chat/$conversationId': {
      id: '/_authenticated/app/chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/app/chat/$conversationId'
      preLoaderRoute: typeof AuthenticatedAppChatConversationIdRouteImport
      parentRoute: typeof AuthenticatedAppChatRoute
    }
  }
}

interface AuthenticatedAppChatRouteChildren {
  AuthenticatedAppChatConversationIdRoute: typeof AuthenticatedAppChatConversationIdRoute
  AuthenticatedAppChatIndexRoute: typeof AuthenticatedAppChatIndexRoute
}

const AuthenticatedAppChatRouteChildren: AuthenticatedAppChatRouteChildren = {
  AuthenticatedAppChatConversationIdRoute:
    AuthenticatedAppChatConversationIdRoute,
  AuthenticatedAppChatIndexRoute: AuthenticatedAppChatIndexRoute,
}

const AuthenticatedAppChatRouteWithChildren =
  AuthenticatedAppChatRoute._addFileChildren(AuthenticatedAppChatRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAiRoute: typeof AuthenticatedAppAiRoute
  AuthenticatedAppBanksRoute: typeof AuthenticatedAppBanksRoute
  AuthenticatedAppChatRoute: typeof AuthenticatedAppChatRouteWithChildren
  AuthenticatedAppDiscoverRoute: typeof AuthenticatedAppDiscoverRoute
  AuthenticatedAppMiniappsRoute: typeof AuthenticatedAppMiniappsRoute
  AuthenticatedAppPayRoute: typeof AuthenticatedAppPayRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppRidesRoute: typeof AuthenticatedAppRidesRoute
  AuthenticatedAppScanRoute: typeof AuthenticatedAppScanRoute
  AuthenticatedAppUpiRoute: typeof AuthenticatedAppUpiRoute
  AuthenticatedAppWalletRoute: typeof AuthenticatedAppWalletRoute
  AuthenticatedAppWeatherRoute: typeof AuthenticatedAppWeatherRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppFoodIdRoute: typeof AuthenticatedAppFoodIdRoute
  AuthenticatedAppFoodIndexRoute: typeof AuthenticatedAppFoodIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAiRoute: AuthenticatedAppAiRoute,
  AuthenticatedAppBanksRoute: AuthenticatedAppBanksRoute,
  AuthenticatedAppChatRoute: AuthenticatedAppChatRouteWithChildren,
  AuthenticatedAppDiscoverRoute: AuthenticatedAppDiscoverRoute,
  AuthenticatedAppMiniappsRoute: AuthenticatedAppMiniappsRoute,
  AuthenticatedAppPayRoute: AuthenticatedAppPayRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppRidesRoute: AuthenticatedAppRidesRoute,
  AuthenticatedAppScanRoute: AuthenticatedAppScanRoute,
  AuthenticatedAppUpiRoute: AuthenticatedAppUpiRoute,
  AuthenticatedAppWalletRoute: AuthenticatedAppWalletRoute,
  AuthenticatedAppWeatherRoute: AuthenticatedAppWeatherRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppFoodIdRoute: AuthenticatedAppFoodIdRoute,
  AuthenticatedAppFoodIndexRoute: AuthenticatedAppFoodIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
