/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthNativeCallbackRouteImport } from './routes/auth-native-callback'
import { Route as ChildSafetyRouteImport } from './routes/child-safety'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as DmcaRouteImport } from './routes/dmca'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as McpSigninRouteImport } from './routes/mcp-signin'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as BlogSuperAppsInIndiaRouteImport } from './routes/blog.super-apps-in-india'
import { Route as BlogWhatIsASuperAppRouteImport } from './routes/blog.what-is-a-super-app'
import { Route as MPostIdRouteImport } from './routes/m.$postId'
import { Route as PayStoryRouteImport } from './routes/pay.story'
import { Route as QTokenRouteImport } from './routes/q.$token'
import { Route as RClipIdRouteImport } from './routes/r.$clipId'
import { Route as UUserIdRouteImport } from './routes/u.$userId'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app.admin'
import { Route as AuthenticatedAppAiRouteImport } from './routes/_authenticated/app.ai'
import { Route as AuthenticatedAppAttributionsRouteImport } from './routes/_authenticated/app.attributions'
import { Route as AuthenticatedAppChatRouteImport } from './routes/_authenticated/app.chat'
import { Route as AuthenticatedAppClipsRouteImport } from './routes/_authenticated/app.clips'
import { Route as AuthenticatedAppCreatorRouteImport } from './routes/_authenticated/app.creator'
import { Route as AuthenticatedAppDiagRouteImport } from './routes/_authenticated/app.diag'
import { Route as AuthenticatedAppEarnRouteImport } from './routes/_authenticated/app.earn'
import { Route as AuthenticatedAppFaithRouteImport } from './routes/_authenticated/app.faith'
import { Route as AuthenticatedAppJobsRouteImport } from './routes/_authenticated/app.jobs'
import { Route as AuthenticatedAppJobsAppsRouteImport } from './routes/_authenticated/app.jobs-apps'
import { Route as AuthenticatedAppLearnRouteImport } from './routes/_authenticated/app.learn'
import { Route as AuthenticatedAppLoresRouteImport } from './routes/_authenticated/app.lores'
import { Route as AuthenticatedAppMiniappsRouteImport } from './routes/_authenticated/app.miniapps'
import { Route as AuthenticatedAppNewsRouteImport } from './routes/_authenticated/app.news'
import { Route as AuthenticatedAppOfficialRouteImport } from './routes/_authenticated/app.official'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppRidesRouteImport } from './routes/_authenticated/app.rides'
import { Route as AuthenticatedAppSafetyPlanRouteImport } from './routes/_authenticated/app.safety-plan'
import { Route as AuthenticatedAppScanRouteImport } from './routes/_authenticated/app.scan'
import { Route as AuthenticatedAppStudyRouteImport } from './routes/_authenticated/app.study'
import { Route as AuthenticatedAppTravelRouteImport } from './routes/_authenticated/app.travel'
import { Route as AuthenticatedAppUniversityRouteImport } from './routes/_authenticated/app.university'
import { Route as AuthenticatedAppUpiRouteImport } from './routes/_authenticated/app.upi'
import { Route as AuthenticatedAppVitalsRouteImport } from './routes/_authenticated/app.vitals'
import { Route as AuthenticatedAppWeatherRouteImport } from './routes/_authenticated/app.weather'
import { Route as AuthenticatedAppAdminVideoRouteImport } from './routes/_authenticated/app.admin.video'
import { Route as AuthenticatedAppChatIndexRouteImport } from './routes/_authenticated/app.chat.index'
import { Route as AuthenticatedAppChatConversationIdRouteImport } from './routes/_authenticated/app.chat.$conversationId'
import { Route as AuthenticatedAppChatCallsRouteImport } from './routes/_authenticated/app.chat.calls'
import { Route as AuthenticatedAppChatMeRouteImport } from './routes/_authenticated/app.chat.me'
import { Route as AuthenticatedAppChatMomentsRouteImport } from './routes/_authenticated/app.chat.moments'
import { Route as AuthenticatedAppChatReelsRouteImport } from './routes/_authenticated/app.chat.reels'
import { Route as AuthenticatedAppChatUpdatesRouteImport } from './routes/_authenticated/app.chat.updates'
import { Route as AuthenticatedAppFoodIndexRouteImport } from './routes/_authenticated/app.food.index'
import { Route as AuthenticatedAppFoodIdRouteImport } from './routes/_authenticated/app.food.$id'
import { Route as AuthenticatedAppPrivacyDataRightsRouteImport } from './routes/_authenticated/app.privacy.data-rights'
import { Route as AuthenticatedAppPrivacyGrievanceRouteImport } from './routes/_authenticated/app.privacy.grievance'
import { Route as AuthenticatedAppPrivacyNoticeRouteImport } from './routes/_authenticated/app.privacy.notice'
import { Route as AuthenticatedAppPrivacyParentalConsentRouteImport } from './routes/_authenticated/app.privacy.parental-consent'
import { Route as AuthenticatedAppUUserIdRouteImport } from './routes/_authenticated/app.u.$userId'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthNativeCallbackRoute = AuthNativeCallbackRouteImport.update({
  id: '/auth-native-callback',
  path: '/auth-native-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildSafetyRoute = ChildSafetyRouteImport.update({
  id: '/child-safety',
  path: '/child-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const DmcaRoute = DmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const McpSigninRoute = McpSigninRouteImport.update({
  id: '/mcp-signin',
  path: '/mcp-signin',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BlogSuperAppsInIndiaRoute = BlogSuperAppsInIndiaRouteImport.update({
  id: '/blog/super-apps-in-india',
  path: '/blog/super-apps-in-india',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogWhatIsASuperAppRoute = BlogWhatIsASuperAppRouteImport.update({
  id: '/blog/what-is-a-super-app',
  path: '/blog/what-is-a-super-app',
  getParentRoute: () => rootRouteImport,
} as any)
const MPostIdRoute = MPostIdRouteImport.update({
  id: '/m/$postId',
  path: '/m/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const PayStoryRoute = PayStoryRouteImport.update({
  id: '/pay/story',
  path: '/pay/story',
  getParentRoute: () => rootRouteImport,
} as any)
const QTokenRoute = QTokenRouteImport.update({
  id: '/q/$token',
  path: '/q/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RClipIdRoute = RClipIdRouteImport.update({
  id: '/r/$clipId',
  path: '/r/$clipId',
  getParentRoute: () => rootRouteImport,
} as any)
const UUserIdRoute = UUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAiRoute = AuthenticatedAppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAttributionsRoute =
  AuthenticatedAppAttributionsRouteImport.update({
    id: '/attributions',
    path: '/attributions',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppChatRoute = AuthenticatedAppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppClipsRoute = AuthenticatedAppClipsRouteImport.update({
  id: '/clips',
  path: '/clips',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCreatorRoute = AuthenticatedAppCreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDiagRoute = AuthenticatedAppDiagRouteImport.update({
  id: '/diag',
  path: '/diag',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppEarnRoute = AuthenticatedAppEarnRouteImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppFaithRoute = AuthenticatedAppFaithRouteImport.update({
  id: '/faith',
  path: '/faith',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppJobsRoute = AuthenticatedAppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppJobsAppsRoute =
  AuthenticatedAppJobsAppsRouteImport.update({
    id: '/jobs-apps',
    path: '/jobs-apps',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLearnRoute = AuthenticatedAppLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppLoresRoute = AuthenticatedAppLoresRouteImport.update({
  id: '/lores',
  path: '/lores',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMiniappsRoute =
  AuthenticatedAppMiniappsRouteImport.update({
    id: '/miniapps',
    path: '/miniapps',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppNewsRoute = AuthenticatedAppNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppOfficialRoute =
  AuthenticatedAppOfficialRouteImport.update({
    id: '/official',
    path: '/official',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRidesRoute = AuthenticatedAppRidesRouteImport.update({
  id: '/rides',
  path: '/rides',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSafetyPlanRoute =
  AuthenticatedAppSafetyPlanRouteImport.update({
    id: '/safety-plan',
    path: '/safety-plan',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppScanRoute = AuthenticatedAppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppStudyRoute = AuthenticatedAppStudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTravelRoute = AuthenticatedAppTravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppUniversityRoute =
  AuthenticatedAppUniversityRouteImport.update({
    id: '/university',
    path: '/university',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppUpiRoute = AuthenticatedAppUpiRouteImport.update({
  id: '/upi',
  path: '/upi',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppVitalsRoute = AuthenticatedAppVitalsRouteImport.update({
  id: '/vitals',
  path: '/vitals',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppWeatherRoute = AuthenticatedAppWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAdminVideoRoute =
  AuthenticatedAppAdminVideoRouteImport.update({
    id: '/video',
    path: '/video',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppChatIndexRoute =
  AuthenticatedAppChatIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppChatRoute,
  } as any)
const AuthenticatedAppChatConversationIdRoute =
  AuthenticatedAppChatConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedAppChatRoute,
  } as any)
const AuthenticatedAppChatCallsRoute =
  AuthenticatedAppChatCallsRouteImport.update({
    id: '/calls',
    path: '/calls',
    getParentRoute: () => AuthenticatedAppChatRoute,
  } as any)
const AuthenticatedAppChatMeRoute = AuthenticatedAppChatMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedAppChatRoute,
} as any)
const AuthenticatedAppChatMomentsRoute =
  AuthenticatedAppChatMomentsRouteImport.update({
    id: '/moments',
    path: '/moments',
    getParentRoute: () => AuthenticatedAppChatRoute,
  } as any)
const AuthenticatedAppChatReelsRoute =
  AuthenticatedAppChatReelsRouteImport.update({
    id: '/reels',
    path: '/reels',
    getParentRoute: () => AuthenticatedAppChatRoute,
  } as any)
const AuthenticatedAppChatUpdatesRoute =
  AuthenticatedAppChatUpdatesRouteImport.update({
    id: '/updates',
    path: '/updates',
    getParentRoute: () => AuthenticatedAppChatRoute,
  } as any)
const AuthenticatedAppFoodIndexRoute =
  AuthenticatedAppFoodIndexRouteImport.update({
    id: '/food/',
    path: '/food/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFoodIdRoute = AuthenticatedAppFoodIdRouteImport.update({
  id: '/food/$id',
  path: '/food/$id',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPrivacyDataRightsRoute =
  AuthenticatedAppPrivacyDataRightsRouteImport.update({
    id: '/privacy/data-rights',
    path: '/privacy/data-rights',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPrivacyGrievanceRoute =
  AuthenticatedAppPrivacyGrievanceRouteImport.update({
    id: '/privacy/grievance',
    path: '/privacy/grievance',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPrivacyNoticeRoute =
  AuthenticatedAppPrivacyNoticeRouteImport.update({
    id: '/privacy/notice',
    path: '/privacy/notice',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPrivacyParentalConsentRoute =
  AuthenticatedAppPrivacyParentalConsentRouteImport.update({
    id: '/privacy/parental-consent',
    path: '/privacy/parental-consent',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppUUserIdRoute = AuthenticatedAppUUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auth-native-callback': typeof AuthNativeCallbackRoute
  '/child-safety': typeof ChildSafetyRoute
  '/delete-account': typeof DeleteAccountRoute
  '/dmca': typeof DmcaRoute
  '/mcp': typeof McpRoute
  '/mcp-signin': typeof McpSigninRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/blog/super-apps-in-india': typeof BlogSuperAppsInIndiaRoute
  '/blog/what-is-a-super-app': typeof BlogWhatIsASuperAppRoute
  '/m/$postId': typeof MPostIdRoute
  '/pay/story': typeof PayStoryRoute
  '/q/$token': typeof QTokenRoute
  '/r/$clipId': typeof RClipIdRoute
  '/u/$userId': typeof UUserIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/app/ai': typeof AuthenticatedAppAiRoute
  '/app/attributions': typeof AuthenticatedAppAttributionsRoute
  '/app/chat': typeof AuthenticatedAppChatRouteWithChildren
  '/app/clips': typeof AuthenticatedAppClipsRoute
  '/app/creator': typeof AuthenticatedAppCreatorRoute
  '/app/diag': typeof AuthenticatedAppDiagRoute
  '/app/earn': typeof AuthenticatedAppEarnRoute
  '/app/faith': typeof AuthenticatedAppFaithRoute
  '/app/jobs': typeof AuthenticatedAppJobsRoute
  '/app/jobs-apps': typeof AuthenticatedAppJobsAppsRoute
  '/app/learn': typeof AuthenticatedAppLearnRoute
  '/app/lores': typeof AuthenticatedAppLoresRoute
  '/app/miniapps': typeof AuthenticatedAppMiniappsRoute
  '/app/news': typeof AuthenticatedAppNewsRoute
  '/app/official': typeof AuthenticatedAppOfficialRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/rides': typeof AuthenticatedAppRidesRoute
  '/app/safety-plan': typeof AuthenticatedAppSafetyPlanRoute
  '/app/scan': typeof AuthenticatedAppScanRoute
  '/app/study': typeof AuthenticatedAppStudyRoute
  '/app/travel': typeof AuthenticatedAppTravelRoute
  '/app/university': typeof AuthenticatedAppUniversityRoute
  '/app/upi': typeof AuthenticatedAppUpiRoute
  '/app/vitals': typeof AuthenticatedAppVitalsRoute
  '/app/weather': typeof AuthenticatedAppWeatherRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/admin/video': typeof AuthenticatedAppAdminVideoRoute
  '/app/chat/$conversationId': typeof AuthenticatedAppChatConversationIdRoute
  '/app/chat/calls': typeof AuthenticatedAppChatCallsRoute
  '/app/chat/me': typeof AuthenticatedAppChatMeRoute
  '/app/chat/moments': typeof AuthenticatedAppChatMomentsRoute
  '/app/chat/reels': typeof AuthenticatedAppChatReelsRoute
  '/app/chat/updates': typeof AuthenticatedAppChatUpdatesRoute
  '/app/food/$id': typeof AuthenticatedAppFoodIdRoute
  '/app/privacy/data-rights': typeof AuthenticatedAppPrivacyDataRightsRoute
  '/app/privacy/grievance': typeof AuthenticatedAppPrivacyGrievanceRoute
  '/app/privacy/notice': typeof AuthenticatedAppPrivacyNoticeRoute
  '/app/privacy/parental-consent': typeof AuthenticatedAppPrivacyParentalConsentRoute
  '/app/u/$userId': typeof AuthenticatedAppUUserIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/app/chat/': typeof AuthenticatedAppChatIndexRoute
  '/app/food/': typeof AuthenticatedAppFoodIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auth-native-callback': typeof AuthNativeCallbackRoute
  '/child-safety': typeof ChildSafetyRoute
  '/delete-account': typeof DeleteAccountRoute
  '/dmca': typeof DmcaRoute
  '/mcp': typeof McpRoute
  '/mcp-signin': typeof McpSigninRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/super-apps-in-india': typeof BlogSuperAppsInIndiaRoute
  '/blog/what-is-a-super-app': typeof BlogWhatIsASuperAppRoute
  '/m/$postId': typeof MPostIdRoute
  '/pay/story': typeof PayStoryRoute
  '/q/$token': typeof QTokenRoute
  '/r/$clipId': typeof RClipIdRoute
  '/u/$userId': typeof UUserIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/app/ai': typeof AuthenticatedAppAiRoute
  '/app/attributions': typeof AuthenticatedAppAttributionsRoute
  '/app/clips': typeof AuthenticatedAppClipsRoute
  '/app/creator': typeof AuthenticatedAppCreatorRoute
  '/app/diag': typeof AuthenticatedAppDiagRoute
  '/app/earn': typeof AuthenticatedAppEarnRoute
  '/app/faith': typeof AuthenticatedAppFaithRoute
  '/app/jobs': typeof AuthenticatedAppJobsRoute
  '/app/jobs-apps': typeof AuthenticatedAppJobsAppsRoute
  '/app/learn': typeof AuthenticatedAppLearnRoute
  '/app/lores': typeof AuthenticatedAppLoresRoute
  '/app/miniapps': typeof AuthenticatedAppMiniappsRoute
  '/app/news': typeof AuthenticatedAppNewsRoute
  '/app/official': typeof AuthenticatedAppOfficialRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/rides': typeof AuthenticatedAppRidesRoute
  '/app/safety-plan': typeof AuthenticatedAppSafetyPlanRoute
  '/app/scan': typeof AuthenticatedAppScanRoute
  '/app/study': typeof AuthenticatedAppStudyRoute
  '/app/travel': typeof AuthenticatedAppTravelRoute
  '/app/university': typeof AuthenticatedAppUniversityRoute
  '/app/upi': typeof AuthenticatedAppUpiRoute
  '/app/vitals': typeof AuthenticatedAppVitalsRoute
  '/app/weather': typeof AuthenticatedAppWeatherRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/admin/video': typeof AuthenticatedAppAdminVideoRoute
  '/app/chat/$conversationId': typeof AuthenticatedAppChatConversationIdRoute
  '/app/chat/calls': typeof AuthenticatedAppChatCallsRoute
  '/app/chat/me': typeof AuthenticatedAppChatMeRoute
  '/app/chat/moments': typeof AuthenticatedAppChatMomentsRoute
  '/app/chat/reels': typeof AuthenticatedAppChatReelsRoute
  '/app/chat/updates': typeof AuthenticatedAppChatUpdatesRoute
  '/app/food/$id': typeof AuthenticatedAppFoodIdRoute
  '/app/privacy/data-rights': typeof AuthenticatedAppPrivacyDataRightsRoute
  '/app/privacy/grievance': typeof AuthenticatedAppPrivacyGrievanceRoute
  '/app/privacy/notice': typeof AuthenticatedAppPrivacyNoticeRoute
  '/app/privacy/parental-consent': typeof AuthenticatedAppPrivacyParentalConsentRoute
  '/app/u/$userId': typeof AuthenticatedAppUUserIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/app/chat': typeof AuthenticatedAppChatIndexRoute
  '/app/food': typeof AuthenticatedAppFoodIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/auth-native-callback': typeof AuthNativeCallbackRoute
  '/child-safety': typeof ChildSafetyRoute
  '/delete-account': typeof DeleteAccountRoute
  '/dmca': typeof DmcaRoute
  '/mcp': typeof McpRoute
  '/mcp-signin': typeof McpSigninRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/blog/super-apps-in-india': typeof BlogSuperAppsInIndiaRoute
  '/blog/what-is-a-super-app': typeof BlogWhatIsASuperAppRoute
  '/m/$postId': typeof MPostIdRoute
  '/pay/story': typeof PayStoryRoute
  '/q/$token': typeof QTokenRoute
  '/r/$clipId': typeof RClipIdRoute
  '/u/$userId': typeof UUserIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/_authenticated/app/ai': typeof AuthenticatedAppAiRoute
  '/_authenticated/app/attributions': typeof AuthenticatedAppAttributionsRoute
  '/_authenticated/app/chat': typeof AuthenticatedAppChatRouteWithChildren
  '/_authenticated/app/clips': typeof AuthenticatedAppClipsRoute
  '/_authenticated/app/creator': typeof AuthenticatedAppCreatorRoute
  '/_authenticated/app/diag': typeof AuthenticatedAppDiagRoute
  '/_authenticated/app/earn': typeof AuthenticatedAppEarnRoute
  '/_authenticated/app/faith': typeof AuthenticatedAppFaithRoute
  '/_authenticated/app/jobs': typeof AuthenticatedAppJobsRoute
  '/_authenticated/app/jobs-apps': typeof AuthenticatedAppJobsAppsRoute
  '/_authenticated/app/learn': typeof AuthenticatedAppLearnRoute
  '/_authenticated/app/lores': typeof AuthenticatedAppLoresRoute
  '/_authenticated/app/miniapps': typeof AuthenticatedAppMiniappsRoute
  '/_authenticated/app/news': typeof AuthenticatedAppNewsRoute
  '/_authenticated/app/official': typeof AuthenticatedAppOfficialRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/rides': typeof AuthenticatedAppRidesRoute
  '/_authenticated/app/safety-plan': typeof AuthenticatedAppSafetyPlanRoute
  '/_authenticated/app/scan': typeof AuthenticatedAppScanRoute
  '/_authenticated/app/study': typeof AuthenticatedAppStudyRoute
  '/_authenticated/app/travel': typeof AuthenticatedAppTravelRoute
  '/_authenticated/app/university': typeof AuthenticatedAppUniversityRoute
  '/_authenticated/app/upi': typeof AuthenticatedAppUpiRoute
  '/_authenticated/app/vitals': typeof AuthenticatedAppVitalsRoute
  '/_authenticated/app/weather': typeof AuthenticatedAppWeatherRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/admin/video': typeof AuthenticatedAppAdminVideoRoute
  '/_authenticated/app/chat/$conversationId': typeof AuthenticatedAppChatConversationIdRoute
  '/_authenticated/app/chat/calls': typeof AuthenticatedAppChatCallsRoute
  '/_authenticated/app/chat/me': typeof AuthenticatedAppChatMeRoute
  '/_authenticated/app/chat/moments': typeof AuthenticatedAppChatMomentsRoute
  '/_authenticated/app/chat/reels': typeof AuthenticatedAppChatReelsRoute
  '/_authenticated/app/chat/updates': typeof AuthenticatedAppChatUpdatesRoute
  '/_authenticated/app/food/$id': typeof AuthenticatedAppFoodIdRoute
  '/_authenticated/app/privacy/data-rights': typeof AuthenticatedAppPrivacyDataRightsRoute
  '/_authenticated/app/privacy/grievance': typeof AuthenticatedAppPrivacyGrievanceRoute
  '/_authenticated/app/privacy/notice': typeof AuthenticatedAppPrivacyNoticeRoute
  '/_authenticated/app/privacy/parental-consent': typeof AuthenticatedAppPrivacyParentalConsentRoute
  '/_authenticated/app/u/$userId': typeof AuthenticatedAppUUserIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/app/chat/': typeof AuthenticatedAppChatIndexRoute
  '/_authenticated/app/food/': typeof AuthenticatedAppFoodIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth-native-callback'
    | '/child-safety'
    | '/delete-account'
    | '/dmca'
    | '/mcp'
    | '/mcp-signin'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app'
    | '/blog/super-apps-in-india'
    | '/blog/what-is-a-super-app'
    | '/m/$postId'
    | '/pay/story'
    | '/q/$token'
    | '/r/$clipId'
    | '/u/$userId'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/admin'
    | '/app/ai'
    | '/app/attributions'
    | '/app/chat'
    | '/app/clips'
    | '/app/creator'
    | '/app/diag'
    | '/app/earn'
    | '/app/faith'
    | '/app/jobs'
    | '/app/jobs-apps'
    | '/app/learn'
    | '/app/lores'
    | '/app/miniapps'
    | '/app/news'
    | '/app/official'
    | '/app/profile'
    | '/app/rides'
    | '/app/safety-plan'
    | '/app/scan'
    | '/app/study'
    | '/app/travel'
    | '/app/university'
    | '/app/upi'
    | '/app/vitals'
    | '/app/weather'
    | '/app/'
    | '/app/admin/video'
    | '/app/chat/$conversationId'
    | '/app/chat/calls'
    | '/app/chat/me'
    | '/app/chat/moments'
    | '/app/chat/reels'
    | '/app/chat/updates'
    | '/app/food/$id'
    | '/app/privacy/data-rights'
    | '/app/privacy/grievance'
    | '/app/privacy/notice'
    | '/app/privacy/parental-consent'
    | '/app/u/$userId'
    | '/lovable/email/queue/process'
    | '/app/chat/'
    | '/app/food/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth-native-callback'
    | '/child-safety'
    | '/delete-account'
    | '/dmca'
    | '/mcp'
    | '/mcp-signin'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/blog/super-apps-in-india'
    | '/blog/what-is-a-super-app'
    | '/m/$postId'
    | '/pay/story'
    | '/q/$token'
    | '/r/$clipId'
    | '/u/$userId'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/admin'
    | '/app/ai'
    | '/app/attributions'
    | '/app/clips'
    | '/app/creator'
    | '/app/diag'
    | '/app/earn'
    | '/app/faith'
    | '/app/jobs'
    | '/app/jobs-apps'
    | '/app/learn'
    | '/app/lores'
    | '/app/miniapps'
    | '/app/news'
    | '/app/official'
    | '/app/profile'
    | '/app/rides'
    | '/app/safety-plan'
    | '/app/scan'
    | '/app/study'
    | '/app/travel'
    | '/app/university'
    | '/app/upi'
    | '/app/vitals'
    | '/app/weather'
    | '/app'
    | '/app/admin/video'
    | '/app/chat/$conversationId'
    | '/app/chat/calls'
    | '/app/chat/me'
    | '/app/chat/moments'
    | '/app/chat/reels'
    | '/app/chat/updates'
    | '/app/food/$id'
    | '/app/privacy/data-rights'
    | '/app/privacy/grievance'
    | '/app/privacy/notice'
    | '/app/privacy/parental-consent'
    | '/app/u/$userId'
    | '/lovable/email/queue/process'
    | '/app/chat'
    | '/app/food'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/auth-native-callback'
    | '/child-safety'
    | '/delete-account'
    | '/dmca'
    | '/mcp'
    | '/mcp-signin'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/app'
    | '/blog/super-apps-in-india'
    | '/blog/what-is-a-super-app'
    | '/m/$postId'
    | '/pay/story'
    | '/q/$token'
    | '/r/$clipId'
    | '/u/$userId'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/ai'
    | '/_authenticated/app/attributions'
    | '/_authenticated/app/chat'
    | '/_authenticated/app/clips'
    | '/_authenticated/app/creator'
    | '/_authenticated/app/diag'
    | '/_authenticated/app/earn'
    | '/_authenticated/app/faith'
    | '/_authenticated/app/jobs'
    | '/_authenticated/app/jobs-apps'
    | '/_authenticated/app/learn'
    | '/_authenticated/app/lores'
    | '/_authenticated/app/miniapps'
    | '/_authenticated/app/news'
    | '/_authenticated/app/official'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/rides'
    | '/_authenticated/app/safety-plan'
    | '/_authenticated/app/scan'
    | '/_authenticated/app/study'
    | '/_authenticated/app/travel'
    | '/_authenticated/app/university'
    | '/_authenticated/app/upi'
    | '/_authenticated/app/vitals'
    | '/_authenticated/app/weather'
    | '/_authenticated/app/'
    | '/_authenticated/app/admin/video'
    | '/_authenticated/app/chat/$conversationId'
    | '/_authenticated/app/chat/calls'
    | '/_authenticated/app/chat/me'
    | '/_authenticated/app/chat/moments'
    | '/_authenticated/app/chat/reels'
    | '/_authenticated/app/chat/updates'
    | '/_authenticated/app/food/$id'
    | '/_authenticated/app/privacy/data-rights'
    | '/_authenticated/app/privacy/grievance'
    | '/_authenticated/app/privacy/notice'
    | '/_authenticated/app/privacy/parental-consent'
    | '/_authenticated/app/u/$userId'
    | '/lovable/email/queue/process'
    | '/_authenticated/app/chat/'
    | '/_authenticated/app/food/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AuthNativeCallbackRoute: typeof AuthNativeCallbackRoute
  ChildSafetyRoute: typeof ChildSafetyRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  DmcaRoute: typeof DmcaRoute
  McpRoute: typeof McpRoute
  McpSigninRoute: typeof McpSigninRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  BlogSuperAppsInIndiaRoute: typeof BlogSuperAppsInIndiaRoute
  BlogWhatIsASuperAppRoute: typeof BlogWhatIsASuperAppRoute
  MPostIdRoute: typeof MPostIdRoute
  PayStoryRoute: typeof PayStoryRoute
  QTokenRoute: typeof QTokenRoute
  RClipIdRoute: typeof RClipIdRoute
  UUserIdRoute: typeof UUserIdRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-native-callback': {
      id: '/auth-native-callback'
      path: '/auth-native-callback'
      fullPath: '/auth-native-callback'
      preLoaderRoute: typeof AuthNativeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child-safety': {
      id: '/child-safety'
      path: '/child-safety'
      fullPath: '/child-safety'
      preLoaderRoute: typeof ChildSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmca': {
      id: '/dmca'
      path: '/dmca'
      fullPath: '/dmca'
      preLoaderRoute: typeof DmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp-signin': {
      id: '/mcp-signin'
      path: '/mcp-signin'
      fullPath: '/mcp-signin'
      preLoaderRoute: typeof McpSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blog/super-apps-in-india': {
      id: '/blog/super-apps-in-india'
      path: '/blog/super-apps-in-india'
      fullPath: '/blog/super-apps-in-india'
      preLoaderRoute: typeof BlogSuperAppsInIndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/what-is-a-super-app': {
      id: '/blog/what-is-a-super-app'
      path: '/blog/what-is-a-super-app'
      fullPath: '/blog/what-is-a-super-app'
      preLoaderRoute: typeof BlogWhatIsASuperAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$postId': {
      id: '/m/$postId'
      path: '/m/$postId'
      fullPath: '/m/$postId'
      preLoaderRoute: typeof MPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/story': {
      id: '/pay/story'
      path: '/pay/story'
      fullPath: '/pay/story'
      preLoaderRoute: typeof PayStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/$token': {
      id: '/q/$token'
      path: '/q/$token'
      fullPath: '/q/$token'
      preLoaderRoute: typeof QTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$clipId': {
      id: '/r/$clipId'
      path: '/r/$clipId'
      fullPath: '/r/$clipId'
      preLoaderRoute: typeof RClipIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$userId': {
      id: '/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof UUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ai': {
      id: '/_authenticated/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AuthenticatedAppAiRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/attributions': {
      id: '/_authenticated/app/attributions'
      path: '/attributions'
      fullPath: '/app/attributions'
      preLoaderRoute: typeof AuthenticatedAppAttributionsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/chat': {
      id: '/_authenticated/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AuthenticatedAppChatRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/clips': {
      id: '/_authenticated/app/clips'
      path: '/clips'
      fullPath: '/app/clips'
      preLoaderRoute: typeof AuthenticatedAppClipsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/creator': {
      id: '/_authenticated/app/creator'
      path: '/creator'
      fullPath: '/app/creator'
      preLoaderRoute: typeof AuthenticatedAppCreatorRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/diag': {
      id: '/_authenticated/app/diag'
      path: '/diag'
      fullPath: '/app/diag'
      preLoaderRoute: typeof AuthenticatedAppDiagRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/earn': {
      id: '/_authenticated/app/earn'
      path: '/earn'
      fullPath: '/app/earn'
      preLoaderRoute: typeof AuthenticatedAppEarnRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/faith': {
      id: '/_authenticated/app/faith'
      path: '/faith'
      fullPath: '/app/faith'
      preLoaderRoute: typeof AuthenticatedAppFaithRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/jobs': {
      id: '/_authenticated/app/jobs'
      path: '/jobs'
      fullPath: '/app/jobs'
      preLoaderRoute: typeof AuthenticatedAppJobsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/jobs-apps': {
      id: '/_authenticated/app/jobs-apps'
      path: '/jobs-apps'
      fullPath: '/app/jobs-apps'
      preLoaderRoute: typeof AuthenticatedAppJobsAppsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/learn': {
      id: '/_authenticated/app/learn'
      path: '/learn'
      fullPath: '/app/learn'
      preLoaderRoute: typeof AuthenticatedAppLearnRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/lores': {
      id: '/_authenticated/app/lores'
      path: '/lores'
      fullPath: '/app/lores'
      preLoaderRoute: typeof AuthenticatedAppLoresRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/miniapps': {
      id: '/_authenticated/app/miniapps'
      path: '/miniapps'
      fullPath: '/app/miniapps'
      preLoaderRoute: typeof AuthenticatedAppMiniappsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/news': {
      id: '/_authenticated/app/news'
      path: '/news'
      fullPath: '/app/news'
      preLoaderRoute: typeof AuthenticatedAppNewsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/official': {
      id: '/_authenticated/app/official'
      path: '/official'
      fullPath: '/app/official'
      preLoaderRoute: typeof AuthenticatedAppOfficialRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/rides': {
      id: '/_authenticated/app/rides'
      path: '/rides'
      fullPath: '/app/rides'
      preLoaderRoute: typeof AuthenticatedAppRidesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/safety-plan': {
      id: '/_authenticated/app/safety-plan'
      path: '/safety-plan'
      fullPath: '/app/safety-plan'
      preLoaderRoute: typeof AuthenticatedAppSafetyPlanRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/scan': {
      id: '/_authenticated/app/scan'
      path: '/scan'
      fullPath: '/app/scan'
      preLoaderRoute: typeof AuthenticatedAppScanRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/study': {
      id: '/_authenticated/app/study'
      path: '/study'
      fullPath: '/app/study'
      preLoaderRoute: typeof AuthenticatedAppStudyRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/travel': {
      id: '/_authenticated/app/travel'
      path: '/travel'
      fullPath: '/app/travel'
      preLoaderRoute: typeof AuthenticatedAppTravelRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/university': {
      id: '/_authenticated/app/university'
      path: '/university'
      fullPath: '/app/university'
      preLoaderRoute: typeof AuthenticatedAppUniversityRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/upi': {
      id: '/_authenticated/app/upi'
      path: '/upi'
      fullPath: '/app/upi'
      preLoaderRoute: typeof AuthenticatedAppUpiRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/vitals': {
      id: '/_authenticated/app/vitals'
      path: '/vitals'
      fullPath: '/app/vitals'
      preLoaderRoute: typeof AuthenticatedAppVitalsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/weather': {
      id: '/_authenticated/app/weather'
      path: '/weather'
      fullPath: '/app/weather'
      preLoaderRoute: typeof AuthenticatedAppWeatherRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin/video': {
      id: '/_authenticated/app/admin/video'
      path: '/video'
      fullPath: '/app/admin/video'
      preLoaderRoute: typeof AuthenticatedAppAdminVideoRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/chat/': {
      id: '/_authenticated/app/chat/'
      path: '/'
      fullPath: '/app/chat/'
      preLoaderRoute: typeof AuthenticatedAppChatIndexRouteImport
      parentRoute: typeof AuthenticatedAppChatRoute
    }
    '/_authenticated/app/chat/$conversationId': {
      id: '/_authenticated/app/chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/app/chat/$conversationId'
      preLoaderRoute: typeof AuthenticatedAppChatConversationIdRouteImport
      parentRoute: typeof AuthenticatedAppChatRoute
    }
    '/_authenticated/app/chat/calls': {
      id: '/_authenticated/app/chat/calls'
      path: '/calls'
      fullPath: '/app/chat/calls'
      preLoaderRoute: typeof AuthenticatedAppChatCallsRouteImport
      parentRoute: typeof AuthenticatedAppChatRoute
    }
    '/_authenticated/app/chat/me': {
      id: '/_authenticated/app/chat/me'
      path: '/me'
      fullPath: '/app/chat/me'
      preLoaderRoute: typeof AuthenticatedAppChatMeRouteImport
      parentRoute: typeof AuthenticatedAppChatRoute
    }
    '/_authenticated/app/chat/moments': {
      id: '/_authenticated/app/chat/moments'
      path: '/moments'
      fullPath: '/app/chat/moments'
      preLoaderRoute: typeof AuthenticatedAppChatMomentsRouteImport
      parentRoute: typeof AuthenticatedAppChatRoute
    }
    '/_authenticated/app/chat/reels': {
      id: '/_authenticated/app/chat/reels'
      path: '/reels'
      fullPath: '/app/chat/reels'
      preLoaderRoute: typeof AuthenticatedAppChatReelsRouteImport
      parentRoute: typeof AuthenticatedAppChatRoute
    }
    '/_authenticated/app/chat/updates': {
      id: '/_authenticated/app/chat/updates'
      path: '/updates'
      fullPath: '/app/chat/updates'
      preLoaderRoute: typeof AuthenticatedAppChatUpdatesRouteImport
      parentRoute: typeof AuthenticatedAppChatRoute
    }
    '/_authenticated/app/food/': {
      id: '/_authenticated/app/food/'
      path: '/food'
      fullPath: '/app/food/'
      preLoaderRoute: typeof AuthenticatedAppFoodIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/food/$id': {
      id: '/_authenticated/app/food/$id'
      path: '/food/$id'
      fullPath: '/app/food/$id'
      preLoaderRoute: typeof AuthenticatedAppFoodIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/privacy/data-rights': {
      id: '/_authenticated/app/privacy/data-rights'
      path: '/privacy/data-rights'
      fullPath: '/app/privacy/data-rights'
      preLoaderRoute: typeof AuthenticatedAppPrivacyDataRightsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/privacy/grievance': {
      id: '/_authenticated/app/privacy/grievance'
      path: '/privacy/grievance'
      fullPath: '/app/privacy/grievance'
      preLoaderRoute: typeof AuthenticatedAppPrivacyGrievanceRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/privacy/notice': {
      id: '/_authenticated/app/privacy/notice'
      path: '/privacy/notice'
      fullPath: '/app/privacy/notice'
      preLoaderRoute: typeof AuthenticatedAppPrivacyNoticeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/privacy/parental-consent': {
      id: '/_authenticated/app/privacy/parental-consent'
      path: '/privacy/parental-consent'
      fullPath: '/app/privacy/parental-consent'
      preLoaderRoute: typeof AuthenticatedAppPrivacyParentalConsentRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/u/$userId': {
      id: '/_authenticated/app/u/$userId'
      path: '/u/$userId'
      fullPath: '/app/u/$userId'
      preLoaderRoute: typeof AuthenticatedAppUUserIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAppAdminRouteChildren {
  AuthenticatedAppAdminVideoRoute: typeof AuthenticatedAppAdminVideoRoute
}

const AuthenticatedAppAdminRouteChildren: AuthenticatedAppAdminRouteChildren = {
  AuthenticatedAppAdminVideoRoute: AuthenticatedAppAdminVideoRoute,
}

const AuthenticatedAppAdminRouteWithChildren =
  AuthenticatedAppAdminRoute._addFileChildren(
    AuthenticatedAppAdminRouteChildren,
  )

interface AuthenticatedAppChatRouteChildren {
  AuthenticatedAppChatConversationIdRoute: typeof AuthenticatedAppChatConversationIdRoute
  AuthenticatedAppChatCallsRoute: typeof AuthenticatedAppChatCallsRoute
  AuthenticatedAppChatMeRoute: typeof AuthenticatedAppChatMeRoute
  AuthenticatedAppChatMomentsRoute: typeof AuthenticatedAppChatMomentsRoute
  AuthenticatedAppChatReelsRoute: typeof AuthenticatedAppChatReelsRoute
  AuthenticatedAppChatUpdatesRoute: typeof AuthenticatedAppChatUpdatesRoute
  AuthenticatedAppChatIndexRoute: typeof AuthenticatedAppChatIndexRoute
}

const AuthenticatedAppChatRouteChildren: AuthenticatedAppChatRouteChildren = {
  AuthenticatedAppChatConversationIdRoute:
    AuthenticatedAppChatConversationIdRoute,
  AuthenticatedAppChatCallsRoute: AuthenticatedAppChatCallsRoute,
  AuthenticatedAppChatMeRoute: AuthenticatedAppChatMeRoute,
  AuthenticatedAppChatMomentsRoute: AuthenticatedAppChatMomentsRoute,
  AuthenticatedAppChatReelsRoute: AuthenticatedAppChatReelsRoute,
  AuthenticatedAppChatUpdatesRoute: AuthenticatedAppChatUpdatesRoute,
  AuthenticatedAppChatIndexRoute: AuthenticatedAppChatIndexRoute,
}

const AuthenticatedAppChatRouteWithChildren =
  AuthenticatedAppChatRoute._addFileChildren(AuthenticatedAppChatRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRouteWithChildren
  AuthenticatedAppAiRoute: typeof AuthenticatedAppAiRoute
  AuthenticatedAppAttributionsRoute: typeof AuthenticatedAppAttributionsRoute
  AuthenticatedAppChatRoute: typeof AuthenticatedAppChatRouteWithChildren
  AuthenticatedAppClipsRoute: typeof AuthenticatedAppClipsRoute
  AuthenticatedAppCreatorRoute: typeof AuthenticatedAppCreatorRoute
  AuthenticatedAppDiagRoute: typeof AuthenticatedAppDiagRoute
  AuthenticatedAppEarnRoute: typeof AuthenticatedAppEarnRoute
  AuthenticatedAppFaithRoute: typeof AuthenticatedAppFaithRoute
  AuthenticatedAppJobsRoute: typeof AuthenticatedAppJobsRoute
  AuthenticatedAppJobsAppsRoute: typeof AuthenticatedAppJobsAppsRoute
  AuthenticatedAppLearnRoute: typeof AuthenticatedAppLearnRoute
  AuthenticatedAppLoresRoute: typeof AuthenticatedAppLoresRoute
  AuthenticatedAppMiniappsRoute: typeof AuthenticatedAppMiniappsRoute
  AuthenticatedAppNewsRoute: typeof AuthenticatedAppNewsRoute
  AuthenticatedAppOfficialRoute: typeof AuthenticatedAppOfficialRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppRidesRoute: typeof AuthenticatedAppRidesRoute
  AuthenticatedAppSafetyPlanRoute: typeof AuthenticatedAppSafetyPlanRoute
  AuthenticatedAppScanRoute: typeof AuthenticatedAppScanRoute
  AuthenticatedAppStudyRoute: typeof AuthenticatedAppStudyRoute
  AuthenticatedAppTravelRoute: typeof AuthenticatedAppTravelRoute
  AuthenticatedAppUniversityRoute: typeof AuthenticatedAppUniversityRoute
  AuthenticatedAppUpiRoute: typeof AuthenticatedAppUpiRoute
  AuthenticatedAppVitalsRoute: typeof AuthenticatedAppVitalsRoute
  AuthenticatedAppWeatherRoute: typeof AuthenticatedAppWeatherRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppFoodIdRoute: typeof AuthenticatedAppFoodIdRoute
  AuthenticatedAppPrivacyDataRightsRoute: typeof AuthenticatedAppPrivacyDataRightsRoute
  AuthenticatedAppPrivacyGrievanceRoute: typeof AuthenticatedAppPrivacyGrievanceRoute
  AuthenticatedAppPrivacyNoticeRoute: typeof AuthenticatedAppPrivacyNoticeRoute
  AuthenticatedAppPrivacyParentalConsentRoute: typeof AuthenticatedAppPrivacyParentalConsentRoute
  AuthenticatedAppUUserIdRoute: typeof AuthenticatedAppUUserIdRoute
  AuthenticatedAppFoodIndexRoute: typeof AuthenticatedAppFoodIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRouteWithChildren,
  AuthenticatedAppAiRoute: AuthenticatedAppAiRoute,
  AuthenticatedAppAttributionsRoute: AuthenticatedAppAttributionsRoute,
  AuthenticatedAppChatRoute: AuthenticatedAppChatRouteWithChildren,
  AuthenticatedAppClipsRoute: AuthenticatedAppClipsRoute,
  AuthenticatedAppCreatorRoute: AuthenticatedAppCreatorRoute,
  AuthenticatedAppDiagRoute: AuthenticatedAppDiagRoute,
  AuthenticatedAppEarnRoute: AuthenticatedAppEarnRoute,
  AuthenticatedAppFaithRoute: AuthenticatedAppFaithRoute,
  AuthenticatedAppJobsRoute: AuthenticatedAppJobsRoute,
  AuthenticatedAppJobsAppsRoute: AuthenticatedAppJobsAppsRoute,
  AuthenticatedAppLearnRoute: AuthenticatedAppLearnRoute,
  AuthenticatedAppLoresRoute: AuthenticatedAppLoresRoute,
  AuthenticatedAppMiniappsRoute: AuthenticatedAppMiniappsRoute,
  AuthenticatedAppNewsRoute: AuthenticatedAppNewsRoute,
  AuthenticatedAppOfficialRoute: AuthenticatedAppOfficialRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppRidesRoute: AuthenticatedAppRidesRoute,
  AuthenticatedAppSafetyPlanRoute: AuthenticatedAppSafetyPlanRoute,
  AuthenticatedAppScanRoute: AuthenticatedAppScanRoute,
  AuthenticatedAppStudyRoute: AuthenticatedAppStudyRoute,
  AuthenticatedAppTravelRoute: AuthenticatedAppTravelRoute,
  AuthenticatedAppUniversityRoute: AuthenticatedAppUniversityRoute,
  AuthenticatedAppUpiRoute: AuthenticatedAppUpiRoute,
  AuthenticatedAppVitalsRoute: AuthenticatedAppVitalsRoute,
  AuthenticatedAppWeatherRoute: AuthenticatedAppWeatherRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppFoodIdRoute: AuthenticatedAppFoodIdRoute,
  AuthenticatedAppPrivacyDataRightsRoute:
    AuthenticatedAppPrivacyDataRightsRoute,
  AuthenticatedAppPrivacyGrievanceRoute: AuthenticatedAppPrivacyGrievanceRoute,
  AuthenticatedAppPrivacyNoticeRoute: AuthenticatedAppPrivacyNoticeRoute,
  AuthenticatedAppPrivacyParentalConsentRoute:
    AuthenticatedAppPrivacyParentalConsentRoute,
  AuthenticatedAppUUserIdRoute: AuthenticatedAppUUserIdRoute,
  AuthenticatedAppFoodIndexRoute: AuthenticatedAppFoodIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AuthNativeCallbackRoute: AuthNativeCallbackRoute,
  ChildSafetyRoute: ChildSafetyRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  DmcaRoute: DmcaRoute,
  McpRoute: McpRoute,
  McpSigninRoute: McpSigninRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  BlogSuperAppsInIndiaRoute: BlogSuperAppsInIndiaRoute,
  BlogWhatIsASuperAppRoute: BlogWhatIsASuperAppRoute,
  MPostIdRoute: MPostIdRoute,
  PayStoryRoute: PayStoryRoute,
  QTokenRoute: QTokenRoute,
  RClipIdRoute: RClipIdRoute,
  UUserIdRoute: UUserIdRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
