// ONIQ Lores — the Originals hub.
//
// Data only: which episodes exist, and which of them already have a playable
// video. Episode metadata is read from the season shot list (originals.ts) so
// the two can never drift; this file only adds "is there a video yet, and
// where does it live".
import { ORIGINALS, type Episode } from "@/data/originals";
import fireflyAsset from "@/assets/lores-firefly-forest.mp4.asset.json";
import promoAsset from "@/assets/oniq-promo.mp4.asset.json";
import ep1Asset from "@/assets/oniq-ep1.mp4.asset.json";
import ep2Asset from "@/assets/oniq-ep2.mp4.asset.json";

// PROVENANCE. Recorded here because both clips were produced OUTSIDE this repo
// and neither went through the guarded Runway pipeline in runwayOps.server.ts
// — video_jobs is empty. Without this note the only record of where they came
// from is a chat log, which is no record at all.
//
//   oniq-promo          Remotion motion graphics, hand-authored in remotion/,
//                       rendered out-of-band and uploaded as an asset.
//   oniq-ep1            Episode 1, "The Fisherman and the Jinni". Twelve stills
//                       generated with the image tool (standard tier, 1080x1920)
//                       from stillPromptFor(scene) in src/data/originals.ts;
//                       narration generated via the Lovable AI Gateway with
//                       openai/gpt-4o-mini-tts, voice "ash"; motion (Ken Burns
//                       + cross-dissolves) and the final mux by Remotion
//                       (remotion/src/ep1, rendered with scripts/render-ep1.mjs).
//   oniq-ep2            Episode 2, "Ali Baba and the Forty Thieves". Sixteen
//                       stills generated from stillPromptFor(scene), which for
//                       this episode resolves STORYBOOK_STYLE rather than
//                       HOUSE_STYLE — a different look from episode 1, chosen
//                       by the project owner from a reference clip — plus the
//                       EP2_CAST appearance locks. Narration via the Lovable AI
//                       Gateway, openai/gpt-4o-mini-tts, voice "ash", the same
//                       narrator as episode 1. Music bed generated from EP2_BED
//                       and ducked under the narration by a precomputed gain
//                       curve (remotion/src/ep2/bedGain.json). Motion and mux
//                       by Remotion (remotion/src/ep2, scripts/render-ep2.mjs).
//                       Sixteen scenes, not the fourteen in the original shot
//                       list: S14 ran 65s on one still and was split three ways.
//   firefly-forest      AI-generated by Lovable's agent from ONIQ app images.
//                       Inputs are ONIQ's own, so the rights position is clean
//                       — but it IS generated, which is why the Lores screen
//                       carries the AI label (see AI_SURFACES).
//
// Anything added here that was generated, by any tool, needs the same two
// lines: what made it, and from what.

export type LoreVideo = {
  id: string;
  title: string;
  /** Short line under the title. */
  blurb: string;
  /** Playable source, or null while the episode is still in production. */
  url: string | null;
  runtime: string;
  /** Season/collection this belongs to. */
  collection: string;
};

/** Standalone clips that are not part of a scripted season. */
const STANDALONE: LoreVideo[] = [
  {
    id: "oniq-promo",
    title: "ONIQ — One App. Every World.",
    blurb: "The official ONIQ promo.",
    url: promoAsset.url,
    runtime: "0:23",
    collection: "ONIQ",
  },
  {
    id: "firefly-forest",
    title: "The Glowing Forest",
    blurb: "A child walks into a forest lit by fireflies. Warm illustrated short.",
    url: fireflyAsset.url,
    runtime: "0:05",
    collection: "Shorts",
  },
];

/**
 * Episodes that have actually been rendered, and how long they actually run.
 *
 * A map rather than a chain of ternaries on `ep.id`: there were two of those
 * for one episode, they had to agree with each other, and a third episode
 * would have made three. Runtime is the MEASURED length of the finished file,
 * not the estimate in originals.ts — that estimate says "~6 min" for an
 * episode that runs 5:35, which is fine as a planning figure and wrong as a
 * label under a play button.
 */
const RENDERED: Record<string, { url: string; runtime: string }> = {
  ep1: { url: ep1Asset.url, runtime: "4:47" },
  ep2: { url: ep2Asset.url, runtime: "5:35" },
};

function fromEpisode(ep: Episode): LoreVideo {
  const rendered = RENDERED[ep.id];
  return {
    id: ep.id,
    title: `Episode ${ep.number} — ${ep.title}`,
    blurb: `${ep.scenes.length} scenes`,
    url: rendered?.url ?? null,
    runtime: rendered?.runtime ?? ep.runtime,
    collection: "Arabian Nights — Season One",
  };
}

/** Everything Lores can show, newest/playable first. */
export const LORE_VIDEOS: LoreVideo[] = [...STANDALONE, ...ORIGINALS.map(fromEpisode)];

export const LORE_COLLECTIONS: { name: string; videos: LoreVideo[] }[] = [
  ...new Set(LORE_VIDEOS.map((v) => v.collection)),
].map((name) => ({ name, videos: LORE_VIDEOS.filter((v) => v.collection === name) }));
