// ONIQ Lores — the Originals hub.
//
// Data only: which episodes exist, and which of them already have a playable
// video. Episode metadata is read from the season shot list (originals.ts) so
// the two can never drift; this file only adds "is there a video yet, and
// where does it live".
import { ORIGINALS, type Episode } from "@/data/originals";
import fireflyAsset from "@/assets/lores-firefly-forest.mp4.asset.json";
import promoAsset from "@/assets/oniq-promo.mp4.asset.json";
import ep1Asset from "@/assets/oniq-ep1.mp4.asset.json";

// PROVENANCE. Recorded here because both clips were produced OUTSIDE this repo
// and neither went through the guarded Runway pipeline in runwayOps.server.ts
// — video_jobs is empty. Without this note the only record of where they came
// from is a chat log, which is no record at all.
//
//   oniq-promo          Remotion motion graphics, hand-authored in remotion/,
//                       rendered out-of-band and uploaded as an asset.
//   oniq-ep1            Episode 1, "The Fisherman and the Jinni". Twelve stills
//                       generated with the image tool (standard tier, 1080x1920)
//                       from stillPromptFor(scene) in src/data/originals.ts;
//                       narration generated via the Lovable AI Gateway with
//                       openai/gpt-4o-mini-tts, voice "ash"; motion (Ken Burns
//                       + cross-dissolves) and the final mux by Remotion
//                       (remotion/src/ep1, rendered with scripts/render-ep1.mjs).
//   firefly-forest      AI-generated by Lovable's agent from ONIQ app images.
//                       Inputs are ONIQ's own, so the rights position is clean
//                       — but it IS generated, which is why the Lores screen
//                       carries the AI label (see AI_SURFACES).
//
// Anything added here that was generated, by any tool, needs the same two
// lines: what made it, and from what.

export type LoreVideo = {
  id: string;
  title: string;
  /** Short line under the title. */
  blurb: string;
  /** Playable source, or null while the episode is still in production. */
  url: string | null;
  runtime: string;
  /** Season/collection this belongs to. */
  collection: string;
};

/** Standalone clips that are not part of a scripted season. */
const STANDALONE: LoreVideo[] = [
  {
    id: "oniq-promo",
    title: "ONIQ — One App. Every World.",
    blurb: "The official ONIQ promo.",
    url: promoAsset.url,
    runtime: "0:23",
    collection: "ONIQ",
  },
  {
    id: "firefly-forest",
    title: "The Glowing Forest",
    blurb: "A child walks into a forest lit by fireflies. Warm illustrated short.",
    url: fireflyAsset.url,
    runtime: "0:05",
    collection: "Shorts",
  },
];

function fromEpisode(ep: Episode): LoreVideo {
  return {
    id: ep.id,
    title: `Episode ${ep.number} — ${ep.title}`,
    blurb: `${ep.scenes.length} scenes`,
    url: ep.id === "ep1" ? ep1Asset.url : null,
    runtime: ep.id === "ep1" ? "4:47" : ep.runtime,
    collection: "Arabian Nights — Season One",
  };
}

/** Everything Lores can show, newest/playable first. */
export const LORE_VIDEOS: LoreVideo[] = [...STANDALONE, ...ORIGINALS.map(fromEpisode)];

export const LORE_COLLECTIONS: { name: string; videos: LoreVideo[] }[] = [
  ...new Set(LORE_VIDEOS.map((v) => v.collection)),
].map((name) => ({ name, videos: LORE_VIDEOS.filter((v) => v.collection === name) }));
